@server=http://localhost:4004


### projects
# @name projects_GET
GET {{server}}/odata/v4/projectsys/projects



### projects
# @name projects_POST
POST {{server}}/odata/v4/projectsys/projects
Content-Type: application/json

{
  "PSPNR": "s-390625",
  "PSPID": "PSPID-390625",
  "POST1": "POST1-390625",
  "OBJNR": "OBJNR-390625",
  "ERNAM": "ERNAM-390625",
  "ERDAT": "2006-08-30",
  "AENAM": "AENAM-390625",
  "AEDAT": "2008-05-13",
  "KIMSK": "KIMSK-390625",
  "AUTOD": "5",
  "STSPD": "D-390625",
  "STSPR": "R-390625",
  "VERNR": "R-390625",
  "VERNA": "VERNA-390625",
  "ASTNR": "R-390625",
  "ASTNA": "ASTNA-390625",
  "VBUKR": "0625",
  "VGSBR": "0625",
  "VKOKR": "0625",
  "PRCTR": "CTR-390625",
  "PWHIE": {
    "code": "801"
  },
  "ZUORD": "ZUORD-390625",
  "TRMEQ": "5",
  "PLFAZ": "2016-04-06",
  "PLSEZ": "2013-12-27",
  "WERKS": "0625",
  "KALID": "25",
  "VGPLF": "5",
  "EWPLF": "5",
  "ZTEHT": "625",
  "NZANZ": "5",
  "PLNAW": "5",
  "VPROF": "-390625",
  "PROFL": "-390625",
  "BPROF": "390625",
  "TXTSP": "5",
  "KOSTL": "STL-390625",
  "KTRG": "KTRG-390625",
  "AEDTE": "2020-11-13",
  "AEDTP": "2023-04-24",
  "BERST": "BERST-390625",
  "BERTR": "BERTR-390625",
  "BERKO": "BERKO-390625",
  "BERBU": "BERBU-390625",
  "SPSNR": "R-390625",
  "BESTA": "5",
  "SCOPE": "SCOPE-390625",
  "XSTAT": "5",
  "TXJCD": "TXJCD-390625",
  "ZSCHM": "-390625",
  "SCPRF": "SCPRF-390625",
  "IMPRF": "390625",
  "FMPRF": "390625",
  "ABGSL": "ABGSL-390625",
  "POSTU": "POSTU-390625",
  "PPROF": "390625",
  "PLINT": "5",
  "LOEVM": "5",
  "INACT": "5",
  "KZBWS": "5",
  "SMPRF": "-390625",
  "FLGVRG": "5",
  "GRTOP": "5",
  "PGPRF": "390625",
  "STORT": "ORT-390625",
  "LOGSYSTEM": "TEM-390625",
  "KZERB": "5",
  "PARGR": "0625",
  "FUNC_AREA": "FUNC_AREA-390625",
  "VKORG": "0625",
  "VTWEG": "25",
  "SPART": "25",
  "DPPPROF": "F-390625",
  "VPKSTU": "25",
  "PSPID_EDIT": "PSPID_EDIT-390625",
  "VNAME": "390625",
  "RECID": "25",
  "ETYPE": "625",
  "OTYPE": "0625",
  "JIBCL": "JIBCL-390625",
  "JIBSA": "90625",
  "EEW_PROJ_PS_DUMMY": "5",
  "ZZADMIN": "N-390625",
  "ZZADMINNAME": "ZZADMINNAME-390625",
  "ZZCNTRCD": "25",
  "ZZPGID": "ZZPGID-390625",
  "ZZPJSGST": "390625",
  "ZZLDPCID": "390625",
  "ZZOPPORID": "ZZOPPORID-390625",
  "ZZCUNO": "UNO-390625",
  "ZZ_PLAN_WAERS": {
    "code": "801"
  },
  "ZZMASTAGID": "625",
  "ZZ_COUNTRY_KEY": "5",
  "SCHTYP": "5",
  "SPROG": "2018-02-27",
  "EPROG": "2021-12-08",
  "ORDER_PROC_MODE": "5",
  "SETTLEMENTTYPE": "25",
  "SLWID": "-390625",
  "USR00": "USR00-390625",
  "USR01": "USR01-390625",
  "USR02": "R02-390625",
  "USR03": "R03-390625",
  "USR04": 3174255682.485,
  "USE04": "625",
  "USR05": 6796869305.919,
  "USE05": "625",
  "USR06": 4149775494.626,
  "USE06": "90625",
  "USR07": 4075842285.661,
  "USE07": "90625",
  "USR08": "2017-10-20",
  "USR09": "2006-06-18",
  "USR10": "90625",
  "USR11": "5",
  "CPD_UPDAT": "CPD_UPDAT-390625",
  "FERC_IND": "0625",
  "AVC_PROFILE": "390625",
  "AVC_ACTIVE": "5",
  "CPCURR": {
    "code": "801"
  },
  "PROJ_STATUS": "625",
  "to_WBSElement": [
    {
      "PSPNR": "25217717",
      "POSID": "POSID-25217717",
      "POST1": "POST1-25217717",
      "OBJNR": "OBJNR-25217717",
      "POSKI": "POSKI-25217717",
      "ERNAM": "NAM-25217717",
      "ERDAT": "2001-02-23",
      "AENAM": "NAM-25217717",
      "AEDAT": "2016-07-10",
      "VERNR": "25217717",
      "VERNA": "VERNA-25217717",
      "ASTNR": "25217717",
      "ASTNA": "ASTNA-25217717",
      "PBUKR": "7717",
      "PGSBR": "7717",
      "PKOKR": "7717",
      "PRCTR": "R-25217717",
      "PRART": "17",
      "STUFE": 28,
      "PLAKZ": "7",
      "BELKZ": "7",
      "FAKKZ": "7",
      "NPFAZ": "7",
      "ZUORD": "7",
      "TRMEQ": "7",
      "KVEWE": "7",
      "KAPPL": "17",
      "KALSM": "217717",
      "ZSCHL": "217717",
      "ABGSL": "217717",
      "AKOKR": "7717",
      "AKSTL": "L-25217717",
      "FKOKR": "7717",
      "FKSTL": "L-25217717",
      "FABKL": "17",
      "PSPRI": "7",
      "EQUNR": "EQUNR-25217717",
      "TPLNR": "TPLNR-25217717",
      "PWPOS": "17717",
      "WERKS": "7717",
      "TXTSP": "7",
      "SLWID": "5217717",
      "USR00": "USR00-25217717",
      "USR01": "USR01-25217717",
      "USR02": "2-25217717",
      "USR03": "3-25217717",
      "USR04": 288287178.517,
      "USE04": "717",
      "USR05": 4130478910.419,
      "USE05": "717",
      "USR06": 454017633.623,
      "USE06": "17717",
      "USR07": 8684295596.206,
      "USE07": "17717",
      "USR08": "2012-04-03",
      "USR09": "2007-03-03",
      "USR10": "7",
      "USR11": "7",
      "KOSTL": "L-25217717",
      "KTRG": "TRG-25217717",
      "BERST": "BERST-25217717",
      "BERTR": "BERTR-25217717",
      "BERKO": "BERKO-25217717",
      "BERBU": "BERBU-25217717",
      "CLASF": "7",
      "SPSNR": "25217717",
      "SCOPE": "SCOPE-25217717",
      "XSTAT": "7",
      "TXJCD": "TXJCD-25217717",
      "ZSCHM": "5217717",
      "IMPRF": "217717",
      "EVGEW": 334715.8,
      "AENNR": "NNR-25217717",
      "SUBPR": "BPR-25217717",
      "POSTU": "POSTU-25217717",
      "PLINT": "7",
      "LOEVM": "7",
      "KZBWS": "7",
      "FPLNR": "R-25217717",
      "TADAT": "2012-09-10",
      "IZWEK": "17",
      "ISIZE": "17",
      "IUMKZ": "17717",
      "ABUKR": "7717",
      "GRPKZ": "7",
      "PGPRF": "217717",
      "LOGSYSTEM": "M-25217717",
      "PSPNR_LOGS": "25217717",
      "STORT": "T-25217717",
      "FUNC_AREA": "NC_AREA-25217717",
      "KLVAR": "7717",
      "KALNR": "LNR-25217717",
      "POSID_EDIT": "POSID_EDIT-25217717",
      "PSPKZ": "7",
      "MATNR": "MATNR-25217717",
      "VLPSP": "25217717",
      "VLPKZ": "7",
      "SORT1": "1-25217717",
      "SORT2": "2-25217717",
      "SORT3": "3-25217717",
      "VNAME": "217717",
      "RECID": "17",
      "ETYPE": "717",
      "OTYPE": "7717",
      "JIBCL": "717",
      "JIBSA": "17717",
      "CGPL_GUID16": "CGPL_GUID16-25217717",
      "CGPL_LOGSYS": "S-25217717",
      "CGPL_OBJTYPE": "717",
      "ADPSP": "ADPSP-25217717",
      "RFIPPNT": "RFIPPNT-25217717",
      "EEW_PRPS_PS_DUMMY": "7",
      "RFUND": "D-25217717",
      "RGRANT_NBR": "RGRANT_NBR-25217717",
      "FUND_FIX_ASSIGN": "7",
      "GRANT_FIX_ASSIGNED": "7",
      "FUNC_AREA_FIX_ASSIGNED": "7",
      "SPONSOREDPROG": "ONSOREDPROG-25217717",
      "SETTLEMENTELEMENT": "7",
      "SETTLMTRULEINHERITED": "7",
      "SETTLEMENTOBJECT": "TLEMENTOBJECT-25217717",
      "CPD_UPDAT": 69024752725143,
      "FERC_IND": "7717",
      "PRPS_STATUS": 5,
      "POSNR_PRPS": "217717",
      "VBELN_PRPS": "S-25217717",
      "ZZADMIN": "25217717",
      "ZZADMINNAME": "ZZADMINNAME-25217717",
      "ZZCNTRCD": "17",
      "ZZPJSGST": "217717",
      "ZZLDPCID": "217717",
      "ZZOFFERING": "217717",
      "ZZSOLSEID": "217717",
      "ZZOPPORID": "ZZOPPORID-25217717",
      "ZZ_PLAN_WAERS": "17717",
      "ZZRAREFID": "ZZRAREFID-25217717",
      "ZZ_LINEITEM_ID": "217717",
      "ZZ_COUNTRY_KEY": "717",
      "ZCPM_AMR_FSST": "2016-12-01",
      "ZCPM_AMR_FSFT": "2000-02-18"
    },
    {
      "PSPNR": "25217718",
      "POSID": "POSID-25217718",
      "POST1": "POST1-25217718",
      "OBJNR": "OBJNR-25217718",
      "POSKI": "POSKI-25217718",
      "ERNAM": "NAM-25217718",
      "ERDAT": "2023-06-28",
      "AENAM": "NAM-25217718",
      "AEDAT": "2003-06-11",
      "VERNR": "25217718",
      "VERNA": "VERNA-25217718",
      "ASTNR": "25217718",
      "ASTNA": "ASTNA-25217718",
      "PBUKR": "7718",
      "PGSBR": "7718",
      "PKOKR": "7718",
      "PRCTR": "R-25217718",
      "PRART": "18",
      "STUFE": 14,
      "PLAKZ": "8",
      "BELKZ": "8",
      "FAKKZ": "8",
      "NPFAZ": "8",
      "ZUORD": "8",
      "TRMEQ": "8",
      "KVEWE": "8",
      "KAPPL": "18",
      "KALSM": "217718",
      "ZSCHL": "217718",
      "ABGSL": "217718",
      "AKOKR": "7718",
      "AKSTL": "L-25217718",
      "FKOKR": "7718",
      "FKSTL": "L-25217718",
      "FABKL": "18",
      "PSPRI": "8",
      "EQUNR": "EQUNR-25217718",
      "TPLNR": "TPLNR-25217718",
      "PWPOS": "17718",
      "WERKS": "7718",
      "TXTSP": "8",
      "SLWID": "5217718",
      "USR00": "USR00-25217718",
      "USR01": "USR01-25217718",
      "USR02": "2-25217718",
      "USR03": "3-25217718",
      "USR04": 6155061504.841,
      "USE04": "718",
      "USR05": 2148619700.403,
      "USE05": "718",
      "USR06": 6630734137.385,
      "USE06": "17718",
      "USR07": 98600585.244,
      "USE07": "17718",
      "USR08": "2008-07-21",
      "USR09": "2018-11-28",
      "USR10": "8",
      "USR11": "8",
      "KOSTL": "L-25217718",
      "KTRG": "TRG-25217718",
      "BERST": "BERST-25217718",
      "BERTR": "BERTR-25217718",
      "BERKO": "BERKO-25217718",
      "BERBU": "BERBU-25217718",
      "CLASF": "8",
      "SPSNR": "25217718",
      "SCOPE": "SCOPE-25217718",
      "XSTAT": "8",
      "TXJCD": "TXJCD-25217718",
      "ZSCHM": "5217718",
      "IMPRF": "217718",
      "EVGEW": 428646.73,
      "AENNR": "NNR-25217718",
      "SUBPR": "BPR-25217718",
      "POSTU": "POSTU-25217718",
      "PLINT": "8",
      "LOEVM": "8",
      "KZBWS": "8",
      "FPLNR": "R-25217718",
      "TADAT": "2022-08-09",
      "IZWEK": "18",
      "ISIZE": "18",
      "IUMKZ": "17718",
      "ABUKR": "7718",
      "GRPKZ": "8",
      "PGPRF": "217718",
      "LOGSYSTEM": "M-25217718",
      "PSPNR_LOGS": "25217718",
      "STORT": "T-25217718",
      "FUNC_AREA": "NC_AREA-25217718",
      "KLVAR": "7718",
      "KALNR": "LNR-25217718",
      "POSID_EDIT": "POSID_EDIT-25217718",
      "PSPKZ": "8",
      "MATNR": "MATNR-25217718",
      "VLPSP": "25217718",
      "VLPKZ": "8",
      "SORT1": "1-25217718",
      "SORT2": "2-25217718",
      "SORT3": "3-25217718",
      "VNAME": "217718",
      "RECID": "18",
      "ETYPE": "718",
      "OTYPE": "7718",
      "JIBCL": "718",
      "JIBSA": "17718",
      "CGPL_GUID16": "CGPL_GUID16-25217718",
      "CGPL_LOGSYS": "S-25217718",
      "CGPL_OBJTYPE": "718",
      "ADPSP": "ADPSP-25217718",
      "RFIPPNT": "RFIPPNT-25217718",
      "EEW_PRPS_PS_DUMMY": "8",
      "RFUND": "D-25217718",
      "RGRANT_NBR": "RGRANT_NBR-25217718",
      "FUND_FIX_ASSIGN": "8",
      "GRANT_FIX_ASSIGNED": "8",
      "FUNC_AREA_FIX_ASSIGNED": "8",
      "SPONSOREDPROG": "ONSOREDPROG-25217718",
      "SETTLEMENTELEMENT": "8",
      "SETTLMTRULEINHERITED": "8",
      "SETTLEMENTOBJECT": "TLEMENTOBJECT-25217718",
      "CPD_UPDAT": 16776157483490,
      "FERC_IND": "7718",
      "PRPS_STATUS": 90,
      "POSNR_PRPS": "217718",
      "VBELN_PRPS": "S-25217718",
      "ZZADMIN": "25217718",
      "ZZADMINNAME": "ZZADMINNAME-25217718",
      "ZZCNTRCD": "18",
      "ZZPJSGST": "217718",
      "ZZLDPCID": "217718",
      "ZZOFFERING": "217718",
      "ZZSOLSEID": "217718",
      "ZZOPPORID": "ZZOPPORID-25217718",
      "ZZ_PLAN_WAERS": "17718",
      "ZZRAREFID": "ZZRAREFID-25217718",
      "ZZ_LINEITEM_ID": "217718",
      "ZZ_COUNTRY_KEY": "718",
      "ZCPM_AMR_FSST": "2012-11-17",
      "ZCPM_AMR_FSFT": "2006-10-01"
    }
  ]
}


### projects
# @name projects_PATCH
PATCH {{server}}/odata/v4/projectsys/projects/s-390625
Content-Type: application/json

{
  "PSPNR": "s-390625",
  "PSPID": "PSPID-390625",
  "POST1": "POST1-390625",
  "OBJNR": "OBJNR-390625",
  "ERNAM": "ERNAM-390625",
  "ERDAT": "2006-08-30",
  "AENAM": "AENAM-390625",
  "AEDAT": "2008-05-13",
  "KIMSK": "KIMSK-390625",
  "AUTOD": "5",
  "STSPD": "D-390625",
  "STSPR": "R-390625",
  "VERNR": "R-390625",
  "VERNA": "VERNA-390625",
  "ASTNR": "R-390625",
  "ASTNA": "ASTNA-390625",
  "VBUKR": "0625",
  "VGSBR": "0625",
  "VKOKR": "0625",
  "PRCTR": "CTR-390625",
  "PWHIE": {
    "code": "801"
  },
  "ZUORD": "ZUORD-390625",
  "TRMEQ": "5",
  "PLFAZ": "2016-04-06",
  "PLSEZ": "2013-12-27",
  "WERKS": "0625",
  "KALID": "25",
  "VGPLF": "5",
  "EWPLF": "5",
  "ZTEHT": "625",
  "NZANZ": "5",
  "PLNAW": "5",
  "VPROF": "-390625",
  "PROFL": "-390625",
  "BPROF": "390625",
  "TXTSP": "5",
  "KOSTL": "STL-390625",
  "KTRG": "KTRG-390625",
  "AEDTE": "2020-11-13",
  "AEDTP": "2023-04-24",
  "BERST": "BERST-390625",
  "BERTR": "BERTR-390625",
  "BERKO": "BERKO-390625",
  "BERBU": "BERBU-390625",
  "SPSNR": "R-390625",
  "BESTA": "5",
  "SCOPE": "SCOPE-390625",
  "XSTAT": "5",
  "TXJCD": "TXJCD-390625",
  "ZSCHM": "-390625",
  "SCPRF": "SCPRF-390625",
  "IMPRF": "390625",
  "FMPRF": "390625",
  "ABGSL": "ABGSL-390625",
  "POSTU": "POSTU-390625",
  "PPROF": "390625",
  "PLINT": "5",
  "LOEVM": "5",
  "INACT": "5",
  "KZBWS": "5",
  "SMPRF": "-390625",
  "FLGVRG": "5",
  "GRTOP": "5",
  "PGPRF": "390625",
  "STORT": "ORT-390625",
  "LOGSYSTEM": "TEM-390625",
  "KZERB": "5",
  "PARGR": "0625",
  "FUNC_AREA": "FUNC_AREA-390625",
  "VKORG": "0625",
  "VTWEG": "25",
  "SPART": "25",
  "DPPPROF": "F-390625",
  "VPKSTU": "25",
  "PSPID_EDIT": "PSPID_EDIT-390625",
  "VNAME": "390625",
  "RECID": "25",
  "ETYPE": "625",
  "OTYPE": "0625",
  "JIBCL": "JIBCL-390625",
  "JIBSA": "90625",
  "EEW_PROJ_PS_DUMMY": "5",
  "ZZADMIN": "N-390625",
  "ZZADMINNAME": "ZZADMINNAME-390625",
  "ZZCNTRCD": "25",
  "ZZPGID": "ZZPGID-390625",
  "ZZPJSGST": "390625",
  "ZZLDPCID": "390625",
  "ZZOPPORID": "ZZOPPORID-390625",
  "ZZCUNO": "UNO-390625",
  "ZZ_PLAN_WAERS": {
    "code": "801"
  },
  "ZZMASTAGID": "625",
  "ZZ_COUNTRY_KEY": "5",
  "SCHTYP": "5",
  "SPROG": "2018-02-27",
  "EPROG": "2021-12-08",
  "ORDER_PROC_MODE": "5",
  "SETTLEMENTTYPE": "25",
  "SLWID": "-390625",
  "USR00": "USR00-390625",
  "USR01": "USR01-390625",
  "USR02": "R02-390625",
  "USR03": "R03-390625",
  "USR04": 3174255682.485,
  "USE04": "625",
  "USR05": 6796869305.919,
  "USE05": "625",
  "USR06": 4149775494.626,
  "USE06": "90625",
  "USR07": 4075842285.661,
  "USE07": "90625",
  "USR08": "2017-10-20",
  "USR09": "2006-06-18",
  "USR10": "90625",
  "USR11": "5",
  "CPD_UPDAT": "CPD_UPDAT-390625",
  "FERC_IND": "0625",
  "AVC_PROFILE": "390625",
  "AVC_ACTIVE": "5",
  "CPCURR": {
    "code": "801"
  },
  "PROJ_STATUS": "625",
  "to_WBSElement": [
    {
      "PSPNR": "25217717",
      "POSID": "POSID-25217717",
      "POST1": "POST1-25217717",
      "OBJNR": "OBJNR-25217717",
      "POSKI": "POSKI-25217717",
      "ERNAM": "NAM-25217717",
      "ERDAT": "2001-02-23",
      "AENAM": "NAM-25217717",
      "AEDAT": "2016-07-10",
      "VERNR": "25217717",
      "VERNA": "VERNA-25217717",
      "ASTNR": "25217717",
      "ASTNA": "ASTNA-25217717",
      "PBUKR": "7717",
      "PGSBR": "7717",
      "PKOKR": "7717",
      "PRCTR": "R-25217717",
      "PRART": "17",
      "STUFE": 28,
      "PLAKZ": "7",
      "BELKZ": "7",
      "FAKKZ": "7",
      "NPFAZ": "7",
      "ZUORD": "7",
      "TRMEQ": "7",
      "KVEWE": "7",
      "KAPPL": "17",
      "KALSM": "217717",
      "ZSCHL": "217717",
      "ABGSL": "217717",
      "AKOKR": "7717",
      "AKSTL": "L-25217717",
      "FKOKR": "7717",
      "FKSTL": "L-25217717",
      "FABKL": "17",
      "PSPRI": "7",
      "EQUNR": "EQUNR-25217717",
      "TPLNR": "TPLNR-25217717",
      "PWPOS": "17717",
      "WERKS": "7717",
      "TXTSP": "7",
      "SLWID": "5217717",
      "USR00": "USR00-25217717",
      "USR01": "USR01-25217717",
      "USR02": "2-25217717",
      "USR03": "3-25217717",
      "USR04": 288287178.517,
      "USE04": "717",
      "USR05": 4130478910.419,
      "USE05": "717",
      "USR06": 454017633.623,
      "USE06": "17717",
      "USR07": 8684295596.206,
      "USE07": "17717",
      "USR08": "2012-04-03",
      "USR09": "2007-03-03",
      "USR10": "7",
      "USR11": "7",
      "KOSTL": "L-25217717",
      "KTRG": "TRG-25217717",
      "BERST": "BERST-25217717",
      "BERTR": "BERTR-25217717",
      "BERKO": "BERKO-25217717",
      "BERBU": "BERBU-25217717",
      "CLASF": "7",
      "SPSNR": "25217717",
      "SCOPE": "SCOPE-25217717",
      "XSTAT": "7",
      "TXJCD": "TXJCD-25217717",
      "ZSCHM": "5217717",
      "IMPRF": "217717",
      "EVGEW": 334715.8,
      "AENNR": "NNR-25217717",
      "SUBPR": "BPR-25217717",
      "POSTU": "POSTU-25217717",
      "PLINT": "7",
      "LOEVM": "7",
      "KZBWS": "7",
      "FPLNR": "R-25217717",
      "TADAT": "2012-09-10",
      "IZWEK": "17",
      "ISIZE": "17",
      "IUMKZ": "17717",
      "ABUKR": "7717",
      "GRPKZ": "7",
      "PGPRF": "217717",
      "LOGSYSTEM": "M-25217717",
      "PSPNR_LOGS": "25217717",
      "STORT": "T-25217717",
      "FUNC_AREA": "NC_AREA-25217717",
      "KLVAR": "7717",
      "KALNR": "LNR-25217717",
      "POSID_EDIT": "POSID_EDIT-25217717",
      "PSPKZ": "7",
      "MATNR": "MATNR-25217717",
      "VLPSP": "25217717",
      "VLPKZ": "7",
      "SORT1": "1-25217717",
      "SORT2": "2-25217717",
      "SORT3": "3-25217717",
      "VNAME": "217717",
      "RECID": "17",
      "ETYPE": "717",
      "OTYPE": "7717",
      "JIBCL": "717",
      "JIBSA": "17717",
      "CGPL_GUID16": "CGPL_GUID16-25217717",
      "CGPL_LOGSYS": "S-25217717",
      "CGPL_OBJTYPE": "717",
      "ADPSP": "ADPSP-25217717",
      "RFIPPNT": "RFIPPNT-25217717",
      "EEW_PRPS_PS_DUMMY": "7",
      "RFUND": "D-25217717",
      "RGRANT_NBR": "RGRANT_NBR-25217717",
      "FUND_FIX_ASSIGN": "7",
      "GRANT_FIX_ASSIGNED": "7",
      "FUNC_AREA_FIX_ASSIGNED": "7",
      "SPONSOREDPROG": "ONSOREDPROG-25217717",
      "SETTLEMENTELEMENT": "7",
      "SETTLMTRULEINHERITED": "7",
      "SETTLEMENTOBJECT": "TLEMENTOBJECT-25217717",
      "CPD_UPDAT": 69024752725143,
      "FERC_IND": "7717",
      "PRPS_STATUS": 5,
      "POSNR_PRPS": "217717",
      "VBELN_PRPS": "S-25217717",
      "ZZADMIN": "25217717",
      "ZZADMINNAME": "ZZADMINNAME-25217717",
      "ZZCNTRCD": "17",
      "ZZPJSGST": "217717",
      "ZZLDPCID": "217717",
      "ZZOFFERING": "217717",
      "ZZSOLSEID": "217717",
      "ZZOPPORID": "ZZOPPORID-25217717",
      "ZZ_PLAN_WAERS": "17717",
      "ZZRAREFID": "ZZRAREFID-25217717",
      "ZZ_LINEITEM_ID": "217717",
      "ZZ_COUNTRY_KEY": "717",
      "ZCPM_AMR_FSST": "2016-12-01",
      "ZCPM_AMR_FSFT": "2000-02-18"
    },
    {
      "PSPNR": "25217718",
      "POSID": "POSID-25217718",
      "POST1": "POST1-25217718",
      "OBJNR": "OBJNR-25217718",
      "POSKI": "POSKI-25217718",
      "ERNAM": "NAM-25217718",
      "ERDAT": "2023-06-28",
      "AENAM": "NAM-25217718",
      "AEDAT": "2003-06-11",
      "VERNR": "25217718",
      "VERNA": "VERNA-25217718",
      "ASTNR": "25217718",
      "ASTNA": "ASTNA-25217718",
      "PBUKR": "7718",
      "PGSBR": "7718",
      "PKOKR": "7718",
      "PRCTR": "R-25217718",
      "PRART": "18",
      "STUFE": 14,
      "PLAKZ": "8",
      "BELKZ": "8",
      "FAKKZ": "8",
      "NPFAZ": "8",
      "ZUORD": "8",
      "TRMEQ": "8",
      "KVEWE": "8",
      "KAPPL": "18",
      "KALSM": "217718",
      "ZSCHL": "217718",
      "ABGSL": "217718",
      "AKOKR": "7718",
      "AKSTL": "L-25217718",
      "FKOKR": "7718",
      "FKSTL": "L-25217718",
      "FABKL": "18",
      "PSPRI": "8",
      "EQUNR": "EQUNR-25217718",
      "TPLNR": "TPLNR-25217718",
      "PWPOS": "17718",
      "WERKS": "7718",
      "TXTSP": "8",
      "SLWID": "5217718",
      "USR00": "USR00-25217718",
      "USR01": "USR01-25217718",
      "USR02": "2-25217718",
      "USR03": "3-25217718",
      "USR04": 6155061504.841,
      "USE04": "718",
      "USR05": 2148619700.403,
      "USE05": "718",
      "USR06": 6630734137.385,
      "USE06": "17718",
      "USR07": 98600585.244,
      "USE07": "17718",
      "USR08": "2008-07-21",
      "USR09": "2018-11-28",
      "USR10": "8",
      "USR11": "8",
      "KOSTL": "L-25217718",
      "KTRG": "TRG-25217718",
      "BERST": "BERST-25217718",
      "BERTR": "BERTR-25217718",
      "BERKO": "BERKO-25217718",
      "BERBU": "BERBU-25217718",
      "CLASF": "8",
      "SPSNR": "25217718",
      "SCOPE": "SCOPE-25217718",
      "XSTAT": "8",
      "TXJCD": "TXJCD-25217718",
      "ZSCHM": "5217718",
      "IMPRF": "217718",
      "EVGEW": 428646.73,
      "AENNR": "NNR-25217718",
      "SUBPR": "BPR-25217718",
      "POSTU": "POSTU-25217718",
      "PLINT": "8",
      "LOEVM": "8",
      "KZBWS": "8",
      "FPLNR": "R-25217718",
      "TADAT": "2022-08-09",
      "IZWEK": "18",
      "ISIZE": "18",
      "IUMKZ": "17718",
      "ABUKR": "7718",
      "GRPKZ": "8",
      "PGPRF": "217718",
      "LOGSYSTEM": "M-25217718",
      "PSPNR_LOGS": "25217718",
      "STORT": "T-25217718",
      "FUNC_AREA": "NC_AREA-25217718",
      "KLVAR": "7718",
      "KALNR": "LNR-25217718",
      "POSID_EDIT": "POSID_EDIT-25217718",
      "PSPKZ": "8",
      "MATNR": "MATNR-25217718",
      "VLPSP": "25217718",
      "VLPKZ": "8",
      "SORT1": "1-25217718",
      "SORT2": "2-25217718",
      "SORT3": "3-25217718",
      "VNAME": "217718",
      "RECID": "18",
      "ETYPE": "718",
      "OTYPE": "7718",
      "JIBCL": "718",
      "JIBSA": "17718",
      "CGPL_GUID16": "CGPL_GUID16-25217718",
      "CGPL_LOGSYS": "S-25217718",
      "CGPL_OBJTYPE": "718",
      "ADPSP": "ADPSP-25217718",
      "RFIPPNT": "RFIPPNT-25217718",
      "EEW_PRPS_PS_DUMMY": "8",
      "RFUND": "D-25217718",
      "RGRANT_NBR": "RGRANT_NBR-25217718",
      "FUND_FIX_ASSIGN": "8",
      "GRANT_FIX_ASSIGNED": "8",
      "FUNC_AREA_FIX_ASSIGNED": "8",
      "SPONSOREDPROG": "ONSOREDPROG-25217718",
      "SETTLEMENTELEMENT": "8",
      "SETTLMTRULEINHERITED": "8",
      "SETTLEMENTOBJECT": "TLEMENTOBJECT-25217718",
      "CPD_UPDAT": 16776157483490,
      "FERC_IND": "7718",
      "PRPS_STATUS": 90,
      "POSNR_PRPS": "217718",
      "VBELN_PRPS": "S-25217718",
      "ZZADMIN": "25217718",
      "ZZADMINNAME": "ZZADMINNAME-25217718",
      "ZZCNTRCD": "18",
      "ZZPJSGST": "217718",
      "ZZLDPCID": "217718",
      "ZZOFFERING": "217718",
      "ZZSOLSEID": "217718",
      "ZZOPPORID": "ZZOPPORID-25217718",
      "ZZ_PLAN_WAERS": "17718",
      "ZZRAREFID": "ZZRAREFID-25217718",
      "ZZ_LINEITEM_ID": "217718",
      "ZZ_COUNTRY_KEY": "718",
      "ZCPM_AMR_FSST": "2012-11-17",
      "ZCPM_AMR_FSFT": "2006-10-01"
    }
  ]
}


### projects
# @name projects_DELETE
DELETE {{server}}/odata/v4/projectsys/projects/s-390625
Content-Type: application/json


### Currencies
# @name Currencies_GET
GET {{server}}/odata/v4/projectsys/Currencies



### WBSElements
# @name WBSElements_GET
GET {{server}}/odata/v4/projectsys/WBSElements



### WBSElements
# @name WBSElements_POST
POST {{server}}/odata/v4/projectsys/WBSElements
Content-Type: application/json

{
  "PSPNR": "25217717",
  "POSID": "POSID-25217717",
  "POST1": "POST1-25217717",
  "OBJNR": "OBJNR-25217717",
  "POSKI": "POSKI-25217717",
  "ERNAM": "NAM-25217717",
  "ERDAT": "2001-02-23",
  "AENAM": "NAM-25217717",
  "AEDAT": "2016-07-10",
  "VERNR": "25217717",
  "VERNA": "VERNA-25217717",
  "ASTNR": "25217717",
  "ASTNA": "ASTNA-25217717",
  "PBUKR": "7717",
  "PGSBR": "7717",
  "PKOKR": "7717",
  "PRCTR": "R-25217717",
  "PRART": "17",
  "STUFE": 28,
  "PLAKZ": "7",
  "BELKZ": "7",
  "FAKKZ": "7",
  "NPFAZ": "7",
  "ZUORD": "7",
  "TRMEQ": "7",
  "KVEWE": "7",
  "KAPPL": "17",
  "KALSM": "217717",
  "ZSCHL": "217717",
  "ABGSL": "217717",
  "AKOKR": "7717",
  "AKSTL": "L-25217717",
  "FKOKR": "7717",
  "FKSTL": "L-25217717",
  "FABKL": "17",
  "PSPRI": "7",
  "EQUNR": "EQUNR-25217717",
  "TPLNR": "TPLNR-25217717",
  "PWPOS": "17717",
  "WERKS": "7717",
  "TXTSP": "7",
  "SLWID": "5217717",
  "USR00": "USR00-25217717",
  "USR01": "USR01-25217717",
  "USR02": "2-25217717",
  "USR03": "3-25217717",
  "USR04": 288287178.517,
  "USE04": "717",
  "USR05": 4130478910.419,
  "USE05": "717",
  "USR06": 454017633.623,
  "USE06": "17717",
  "USR07": 8684295596.206,
  "USE07": "17717",
  "USR08": "2012-04-03",
  "USR09": "2007-03-03",
  "USR10": "7",
  "USR11": "7",
  "KOSTL": "L-25217717",
  "KTRG": "TRG-25217717",
  "BERST": "BERST-25217717",
  "BERTR": "BERTR-25217717",
  "BERKO": "BERKO-25217717",
  "BERBU": "BERBU-25217717",
  "CLASF": "7",
  "SPSNR": "25217717",
  "SCOPE": "SCOPE-25217717",
  "XSTAT": "7",
  "TXJCD": "TXJCD-25217717",
  "ZSCHM": "5217717",
  "IMPRF": "217717",
  "EVGEW": 334715.8,
  "AENNR": "NNR-25217717",
  "SUBPR": "BPR-25217717",
  "POSTU": "POSTU-25217717",
  "PLINT": "7",
  "LOEVM": "7",
  "KZBWS": "7",
  "FPLNR": "R-25217717",
  "TADAT": "2012-09-10",
  "IZWEK": "17",
  "ISIZE": "17",
  "IUMKZ": "17717",
  "ABUKR": "7717",
  "GRPKZ": "7",
  "PGPRF": "217717",
  "LOGSYSTEM": "M-25217717",
  "PSPNR_LOGS": "25217717",
  "STORT": "T-25217717",
  "FUNC_AREA": "NC_AREA-25217717",
  "KLVAR": "7717",
  "KALNR": "LNR-25217717",
  "POSID_EDIT": "POSID_EDIT-25217717",
  "PSPKZ": "7",
  "MATNR": "MATNR-25217717",
  "VLPSP": "25217717",
  "VLPKZ": "7",
  "SORT1": "1-25217717",
  "SORT2": "2-25217717",
  "SORT3": "3-25217717",
  "VNAME": "217717",
  "RECID": "17",
  "ETYPE": "717",
  "OTYPE": "7717",
  "JIBCL": "717",
  "JIBSA": "17717",
  "CGPL_GUID16": "CGPL_GUID16-25217717",
  "CGPL_LOGSYS": "S-25217717",
  "CGPL_OBJTYPE": "717",
  "ADPSP": "ADPSP-25217717",
  "RFIPPNT": "RFIPPNT-25217717",
  "EEW_PRPS_PS_DUMMY": "7",
  "RFUND": "D-25217717",
  "RGRANT_NBR": "RGRANT_NBR-25217717",
  "FUND_FIX_ASSIGN": "7",
  "GRANT_FIX_ASSIGNED": "7",
  "FUNC_AREA_FIX_ASSIGNED": "7",
  "SPONSOREDPROG": "ONSOREDPROG-25217717",
  "SETTLEMENTELEMENT": "7",
  "SETTLMTRULEINHERITED": "7",
  "SETTLEMENTOBJECT": "TLEMENTOBJECT-25217717",
  "CPD_UPDAT": 69024752725143,
  "FERC_IND": "7717",
  "PRPS_STATUS": 5,
  "POSNR_PRPS": "217717",
  "VBELN_PRPS": "S-25217717",
  "ZZADMIN": "25217717",
  "ZZADMINNAME": "ZZADMINNAME-25217717",
  "ZZCNTRCD": "17",
  "ZZPJSGST": "217717",
  "ZZLDPCID": "217717",
  "ZZOFFERING": "217717",
  "ZZSOLSEID": "217717",
  "ZZOPPORID": "ZZOPPORID-25217717",
  "ZZ_PLAN_WAERS": "17717",
  "ZZRAREFID": "ZZRAREFID-25217717",
  "ZZ_LINEITEM_ID": "217717",
  "ZZ_COUNTRY_KEY": "717",
  "ZCPM_AMR_FSST": "2016-12-01",
  "ZCPM_AMR_FSFT": "2000-02-18"
}


### WBSElements
# @name WBSElements_PATCH
PATCH {{server}}/odata/v4/projectsys/WBSElements/25217717
Content-Type: application/json

{
  "PSPNR": "25217717",
  "POSID": "POSID-25217717",
  "POST1": "POST1-25217717",
  "OBJNR": "OBJNR-25217717",
  "POSKI": "POSKI-25217717",
  "ERNAM": "NAM-25217717",
  "ERDAT": "2001-02-23",
  "AENAM": "NAM-25217717",
  "AEDAT": "2016-07-10",
  "VERNR": "25217717",
  "VERNA": "VERNA-25217717",
  "ASTNR": "25217717",
  "ASTNA": "ASTNA-25217717",
  "PBUKR": "7717",
  "PGSBR": "7717",
  "PKOKR": "7717",
  "PRCTR": "R-25217717",
  "PRART": "17",
  "STUFE": 28,
  "PLAKZ": "7",
  "BELKZ": "7",
  "FAKKZ": "7",
  "NPFAZ": "7",
  "ZUORD": "7",
  "TRMEQ": "7",
  "KVEWE": "7",
  "KAPPL": "17",
  "KALSM": "217717",
  "ZSCHL": "217717",
  "ABGSL": "217717",
  "AKOKR": "7717",
  "AKSTL": "L-25217717",
  "FKOKR": "7717",
  "FKSTL": "L-25217717",
  "FABKL": "17",
  "PSPRI": "7",
  "EQUNR": "EQUNR-25217717",
  "TPLNR": "TPLNR-25217717",
  "PWPOS": "17717",
  "WERKS": "7717",
  "TXTSP": "7",
  "SLWID": "5217717",
  "USR00": "USR00-25217717",
  "USR01": "USR01-25217717",
  "USR02": "2-25217717",
  "USR03": "3-25217717",
  "USR04": 288287178.517,
  "USE04": "717",
  "USR05": 4130478910.419,
  "USE05": "717",
  "USR06": 454017633.623,
  "USE06": "17717",
  "USR07": 8684295596.206,
  "USE07": "17717",
  "USR08": "2012-04-03",
  "USR09": "2007-03-03",
  "USR10": "7",
  "USR11": "7",
  "KOSTL": "L-25217717",
  "KTRG": "TRG-25217717",
  "BERST": "BERST-25217717",
  "BERTR": "BERTR-25217717",
  "BERKO": "BERKO-25217717",
  "BERBU": "BERBU-25217717",
  "CLASF": "7",
  "SPSNR": "25217717",
  "SCOPE": "SCOPE-25217717",
  "XSTAT": "7",
  "TXJCD": "TXJCD-25217717",
  "ZSCHM": "5217717",
  "IMPRF": "217717",
  "EVGEW": 334715.8,
  "AENNR": "NNR-25217717",
  "SUBPR": "BPR-25217717",
  "POSTU": "POSTU-25217717",
  "PLINT": "7",
  "LOEVM": "7",
  "KZBWS": "7",
  "FPLNR": "R-25217717",
  "TADAT": "2012-09-10",
  "IZWEK": "17",
  "ISIZE": "17",
  "IUMKZ": "17717",
  "ABUKR": "7717",
  "GRPKZ": "7",
  "PGPRF": "217717",
  "LOGSYSTEM": "M-25217717",
  "PSPNR_LOGS": "25217717",
  "STORT": "T-25217717",
  "FUNC_AREA": "NC_AREA-25217717",
  "KLVAR": "7717",
  "KALNR": "LNR-25217717",
  "POSID_EDIT": "POSID_EDIT-25217717",
  "PSPKZ": "7",
  "MATNR": "MATNR-25217717",
  "VLPSP": "25217717",
  "VLPKZ": "7",
  "SORT1": "1-25217717",
  "SORT2": "2-25217717",
  "SORT3": "3-25217717",
  "VNAME": "217717",
  "RECID": "17",
  "ETYPE": "717",
  "OTYPE": "7717",
  "JIBCL": "717",
  "JIBSA": "17717",
  "CGPL_GUID16": "CGPL_GUID16-25217717",
  "CGPL_LOGSYS": "S-25217717",
  "CGPL_OBJTYPE": "717",
  "ADPSP": "ADPSP-25217717",
  "RFIPPNT": "RFIPPNT-25217717",
  "EEW_PRPS_PS_DUMMY": "7",
  "RFUND": "D-25217717",
  "RGRANT_NBR": "RGRANT_NBR-25217717",
  "FUND_FIX_ASSIGN": "7",
  "GRANT_FIX_ASSIGNED": "7",
  "FUNC_AREA_FIX_ASSIGNED": "7",
  "SPONSOREDPROG": "ONSOREDPROG-25217717",
  "SETTLEMENTELEMENT": "7",
  "SETTLMTRULEINHERITED": "7",
  "SETTLEMENTOBJECT": "TLEMENTOBJECT-25217717",
  "CPD_UPDAT": 69024752725143,
  "FERC_IND": "7717",
  "PRPS_STATUS": 5,
  "POSNR_PRPS": "217717",
  "VBELN_PRPS": "S-25217717",
  "ZZADMIN": "25217717",
  "ZZADMINNAME": "ZZADMINNAME-25217717",
  "ZZCNTRCD": "17",
  "ZZPJSGST": "217717",
  "ZZLDPCID": "217717",
  "ZZOFFERING": "217717",
  "ZZSOLSEID": "217717",
  "ZZOPPORID": "ZZOPPORID-25217717",
  "ZZ_PLAN_WAERS": "17717",
  "ZZRAREFID": "ZZRAREFID-25217717",
  "ZZ_LINEITEM_ID": "217717",
  "ZZ_COUNTRY_KEY": "717",
  "ZCPM_AMR_FSST": "2016-12-01",
  "ZCPM_AMR_FSFT": "2000-02-18"
}


### WBSElements
# @name WBSElements_DELETE
DELETE {{server}}/odata/v4/projectsys/WBSElements/25217717
Content-Type: application/json


### SalesOrderHeader
# @name SalesOrderHeader_GET
GET {{server}}/odata/v4/projectsys/SalesOrderHeader



### SalesOrderHeader
# @name SalesOrderHeader_POST
POST {{server}}/odata/v4/projectsys/SalesOrderHeader
Content-Type: application/json

{
  "salesOrder": "er-6301391",
  "wbsElement": "-6301391",
  "createdOn": "2009-08-16",
  "createdTime": "22:59:53",
  "createdBy": "edBy-6301391",
  "quotationValidFrom": "2011-02-04",
  "quotationValidTo": "2008-08-19",
  "documentDate": "2015-04-06",
  "salesDocumentCategory": "1",
  "transactionGroup": "1",
  "salesDocumentType": "1391",
  "orderReason": "391",
  "warrantyDate": "2013-03-09",
  "collectiveNumber": "er-6301391",
  "deliveryBlock": "91",
  "billingBlock": "91",
  "netValue": 4172350068159.89,
  "currency": {
    "code": "801"
  },
  "salesOrganization": "1391",
  "distributionChannel": "91",
  "division": "91",
  "salesGroup": "1391",
  "salesOffice": "1391",
  "businessArea": "1391",
  "costCenter": "er-6301391",
  "validityStartDate": "2011-05-22",
  "validityEndDate": "2013-05-31",
  "pricingDocument": "nt-6301391",
  "requestedDeliveryDate": "2010-12-01",
  "deliveryDateTypeRule": "91",
  "pricingGroup": "91",
  "completeDeliveryIndicator": "1",
  "salesDocumentIndicator": "91",
  "salesDocumentIndicator2": "91",
  "pricingProcedure": "301391",
  "shippingCondition": "91",
  "billingType": "1391",
  "probability": 790.21,
  "description": "description-6301391",
  "customerPurchaseOrder": "customerPurchaseOrder-6301391",
  "purchaseOrderType": "1391",
  "purchaseOrderDate": "2006-01-09",
  "purchaseOrderTime": "22:59:53",
  "yourReference": "ourReference-6301391",
  "contactPerson": "rson-6301391",
  "telephoneNumber": "neNumber-6301391",
  "numberOfReminders": 92,
  "lastReminderDate": "2016-09-02",
  "soldToParty": "ty-6301391",
  "costCenterAccount": "nt-6301391",
  "statisticsGroup": "91",
  "documentCurrency": "01391",
  "lastChangedOn": "2004-05-31",
  "customerGroup1": "391",
  "customerGroup2": "391",
  "customerGroup3": "391",
  "customerGroup4": "391",
  "customerGroup5": "391",
  "agreementNumber": "er-6301391",
  "controllingArea": "1391",
  "exchangeRateType": "1391",
  "creditControlArea": "1391",
  "creditAccount": "nt-6301391",
  "creditGroup": "1391",
  "creditRepresentativeGroup": "391",
  "creditRiskCategory": "91",
  "creditCurrency": "01391",
  "creditReleaseDate": "2017-09-19",
  "nextCreditCheckDate": "2015-02-07",
  "creditNextReviewDate": "2010-09-25",
  "releasedCreditValue": 3196400681630.88,
  "lastCreditCheckDate": "2014-10-03",
  "hierarchyTypePricing": "91",
  "universalSalesRelevance": "1",
  "branchUuid": "branchUuid-6301391",
  "usageIndicator": "391",
  "usageIndicatorDescription": "geIndicatorDescription-6301391",
  "precedingDocument": "nt-6301391",
  "objectNumber": "objectNumber-6301391",
  "companyCode": "1391",
  "taxClassification1": "1",
  "taxClassification2": "1",
  "taxClassification3": "1",
  "taxClassification4": "1",
  "taxClassification5": "1",
  "taxClassification6": "1",
  "taxClassification7": "1",
  "taxClassification8": "1",
  "taxClassification9": "1",
  "referenceDocumentNumber": "ntNumber-6301391",
  "assignmentNumber": "mentNumber-6301391",
  "precedingDocumentCategory": "1",
  "pricingProcedureCustomer": "301391",
  "settlementGroup": "301391",
  "orderNumber": "mber-6301391",
  "qualityNotificationNumber": "mber-6301391",
  "documentGroupNumber": "er-6301391",
  "schemeGroup": "1391",
  "callOffPartner": "er-6301391",
  "releaseOrderDate": "2004-04-17",
  "releaseOrderTime": "22:59:53",
  "releaseOrderStatus": "91",
  "routeSchedule": "le-6301391",
  "deliveryTime": "22:59:53",
  "vatRegistrationNumber": "rationNumber-6301391",
  "taxDepartureCountry": "391",
  "externalGoodsReceiptIndicator": "1",
  "enqueueGroup": "91",
  "paymentAuthorizationDate": "2021-05-08",
  "fundsManagementPostingDate": "2008-10-22",
  "versionNumber": "er-6301391",
  "technicalHandle": "echnicalHandle-6301391",
  "productLine": "ne-6301391",
  "dangerousGoodsIndicator": "1",
  "crmGuid": "crmGuid-6301391",
  "updateTimestamp": "ateTimestamp-6301391",
  "measurementServiceId": "Id-6301391",
  "transportationManagementControlKey": "1391",
  "oilIndustryBusinessLocation": "on-6301391",
  "lastChangedByUser": "User-6301391",
  "handoverLocation": "on-6301391",
  "externalBusinessSystemId": "Id-6301391",
  "externalReferenceDocumentId": "externalReferenceDocumentId-6301391",
  "externalRevisionTimestamp": "ionTimestamp-6301391",
  "approvalStatus": "91",
  "approvalReason": "approvalReason-6301391",
  "rejectionReason": "rejectionReason-6301391",
  "solutionOrderId": "utionOrderId-6301391",
  "externalCommunicationSystemType": "pe-6301391",
  "retroPurchaseDocumentCreation": "1",
  "crossItemPricingDate": "2019-06-18",
  "dataAging": "-6301391",
  "overallRejectionStatus": "1",
  "confirmationStatus": "1",
  "creditStatusStaticCheck": "1",
  "creditStatusDynamicCheck": "1",
  "creditStatusPartialRelease": "1",
  "creditStatusManualRelease": "1",
  "creditStatusNextCheck": "1",
  "creditStatusCentralManagement": "1",
  "creditStatusTechnicalError": "1",
  "overallCreditStatus": "1",
  "overallProcessingStatus": "1",
  "deliveryBlockStatus": "1",
  "billingBlockStatus": "1",
  "billingStatus": "1",
  "billingStatusHeader": "1",
  "overallProcessingStatusDocument": "1",
  "deliveryBlockStatusHeader": "1",
  "deliveryStatus": "1",
  "deliveryStatusHeader": "1",
  "manualCompletionIndicator": "1",
  "billingBlockStatusHeader2": "1",
  "billingStatusItem": "1",
  "overallBlockStatus": "1",
  "transportationStatus": "1",
  "incompletionStatusHeader": "1",
  "incompletionStatusItem": "1",
  "billingIncompletionStatusHeader": "1",
  "billingIncompletionStatusItem": "1",
  "pricingIncompletionStatus": "1",
  "deliveryIncompletionStatusHeader": "1",
  "deliveryIncompletionStatusItem": "1",
  "incompletionProcedure1": "1",
  "incompletionProcedure2": "1",
  "incompletionProcedure3": "1",
  "incompletionProcedure4": "1",
  "incompletionProcedure5": "1",
  "incompletionStatusSales1": "1",
  "incompletionStatusSales2": "1",
  "incompletionStatusSales3": "1",
  "incompletionStatusSales4": "1",
  "incompletionStatusSales5": "1",
  "goodsMovementStatus": "1",
  "totalEmcStatus": "1",
  "totalSlcStatus": "1",
  "totalLcStatus": "1",
  "totalPcStatus": "1",
  "totalDangerousGoodsStatus": "1",
  "totalSafetyDataSheetStatus": "1",
  "bobProcessingStatus": "1",
  "downPaymentClearingStatusHeader": "1",
  "b2bMessageProcessingStatus": "1",
  "deliveryRelatedBillingStatusTotal": "1",
  "sdmVersion": "on-6301391",
  "dummySalesDocIncludeEew": "1",
  "cgtoShipmentId": "toShipmentId-6301391",
  "cgtoCoiId": "cgtoCoiId-6301391",
  "cgtoTreatmentOrderId": "tmentOrderId-6301391",
  "cgtoTherapyId": "gtoTherapyId-6301391",
  "cgtoTherapyIdName": "cgtoTherapyIdName-6301391",
  "cgtoTherapyType": "oTherapyType-6301391",
  "cgtoTherapyTypeName": "cgtoTherapyTypeName-6301391",
  "cgtoClinicalTrialSubjectId": "ClinicalTrialSubjectId-6301391",
  "cgtoPatientId": "gtoPatientId-6301391",
  "cgtoCityPharmacyRefNumber": "oCityPharmacyRefNumber-6301391",
  "ctcoStudyId": "ctcoStudyId-6301391",
  "ctcoProtocolId": "coProtocolId-6301391",
  "ctcoSiteId": "ctcoSiteId-6301391",
  "ctcoNoRegularCheck": "1",
  "ctcoPushEpoch": "ch-6301391",
  "globalLogReferenceHeader": "globalLogReferenceHeader-6301391",
  "dmbeDealNumber": "beDealNumber-6301391",
  "dmbeEvgIdRenewal": "EvgIdRenewal-6301391",
  "dmbeEvgIdCancel": "eEvgIdCancel-6301391",
  "zapcgkhIndicator": "or-6301391",
  "apcgkExtendHeader": "er-6301391",
  "zabdathDate": "2010-10-07",
  "ad01FareReference": "areReference-6301391",
  "ad01BaseDocument": "BaseDocument-6301391",
  "lastVoucherNumber": "oucherNumber-6301391",
  "publicSectorBudgetDate": "2023-07-12",
  "fashionCustomerGroup6": "391",
  "fashionCustomerGroup7": "391",
  "fashionCustomerGroup8": "391",
  "fashionCustomerGroup9": "391",
  "fashionCustomerGroup10": "391",
  "fashionReregistration": "1",
  "fashionCqCheck": "1",
  "fashionVersionStatus": "91",
  "fashionTransaction": "on-6301391",
  "fashionValueAddedService": "ce-6301391",
  "fashionCandidateDate": "2015-06-14",
  "fashionSeasonSegment": "1391",
  "fashionOsStgChange": "1",
  "constructionIndicator": "or-6301391",
  "millApplicationId": "Id-6301391",
  "tasIndicator": "1",
  "betcIndicator": "1",
  "modificationAllowed": "1",
  "cancellationAllowed": "1",
  "paymentMethod": "1391",
  "businessPartnerNumber": "er-6301391",
  "reportingFrequency": "1391",
  "logicalSystem": "em-6301391",
  "pricingCalculationIndicator": "1",
  "multipleIndicator": "1",
  "specialPaymentIndicator": "1391",
  "warrantyClaimHeader": "yClaimHeader-6301391",
  "vbakStatus": "91",
  "technicalFields": "technicalFields-6301391",
  "extensionIndicator": "or-6301391",
  "cgtoHeaderIndicator": "or-6301391",
  "studyDataIndicator": "or-6301391",
  "to_item": [
    {
      "itemNumber": "878473",
      "wbsElement": "17878473",
      "material": "material-17878473",
      "enteredMaterial": "enteredMaterial-17878473",
      "pricingReferenceMaterial": "pricingReferenceMaterial-17878473",
      "batch": "batch-17878473",
      "materialGroup": "-17878473",
      "shortText": "shortText-17878473",
      "itemCategory": "17878473",
      "itemType": "17878473",
      "processCode": "e-17878473",
      "deliveryRelevant": false,
      "billingRelevant": false,
      "higherLevelItem": "878473",
      "alternativeItem": "878473",
      "rejectionReason": "73",
      "productHierarchy": "Hierarchy-17878473",
      "universalSalesParentNode": "universalSalesParentNode-17878473",
      "universalSalesOrigin": "n-17878473",
      "universalBatchParentNode": "universalBatchParentNode-17878473",
      "universalBatchOrigin": "n-17878473",
      "targetValue": 929563533899.146,
      "targetQuantity": 541248982079.16,
      "targetUnit": "473",
      "numeratorTargetQty": 89,
      "denominatorTargetQty": 0,
      "baseUnit": "78473",
      "substitutionNumerator": 9,
      "substitutionDenominator": 99,
      "scaleQuantity": 617602698072.317,
      "roundingQuantity": 921264296988.802,
      "roundingDate": "2010-10-28",
      "roundingFactor": 449.37,
      "externalItemNumber": "r-17878473",
      "customerMaterial": "customerMaterial-17878473",
      "usageIndicator": "8473",
      "usageIndicator2": "8473",
      "salesGroup": "78473",
      "usageIndicatorSales": "473",
      "deliveryGroup": "78473",
      "fixedQuantity": 333310978634.46,
      "unlimitedOverdelivery": "y-17878473",
      "overdeliveryTolerance": 477.21,
      "underdeliveryTolerance": 731.8,
      "billingBlockItem": "73",
      "replacementPart": false,
      "billingIndex": false,
      "division": "73",
      "businessArea": "8473",
      "netValueItem": 8239936640637.3,
      "currency": {
        "code": "801"
      },
      "partialDeliveryItem": 6,
      "partialDeliveryIndicator": "3",
      "resourceId": "resourceId-17878473",
      "batchSplitAllowed": false,
      "orderQuantity": 247803186674.037,
      "requiredQuantity": 942508918486.509,
      "confirmedQuantity": 843706542875.672,
      "cumulativeQuantity": 174885191681.445,
      "salesUnit": "473",
      "numeratorConversion": 21,
      "denominatorConversion": 89,
      "grossWeight": 987186351830.243,
      "netWeight": 289037188693.527,
      "weightUnit": "473",
      "volume": 62338547359.871,
      "volumeUnit": "473",
      "originatingDocument": "t-17878473",
      "precedingItem": "878473",
      "referenceDocument": "t-17878473",
      "referenceItem": "878473",
      "originReference": "e-17878473",
      "updateIndicator": "3",
      "completionIndicator": "3",
      "deliveryPriority": "73",
      "plant": "8473",
      "storageLocation": "8473",
      "shippingPoint": "8473",
      "route": "878473",
      "billOfMaterialKey": "17878473",
      "billOfMaterialDate": "2004-08-10",
      "billOfMaterialNumber": "17878473",
      "billOfMaterialItem": "17878473",
      "probability": 5.48,
      "createdOn": "2012-07-18",
      "createdBy": "dBy-17878473",
      "createdTime": "22:59:53",
      "taxClassification1": "3",
      "taxClassification2": "3",
      "taxClassification3": "3",
      "taxClassification4": "3",
      "taxClassification5": "3",
      "taxClassification6": "3",
      "taxClassification7": "3",
      "taxClassification8": "3",
      "taxClassification9": "3",
      "confirmedQuantityDelivery": 337386625172.821,
      "confirmedQuantitySchedule": 549567164361.221,
      "referenceIndicator": "3",
      "netPrice": 3976869401438.32,
      "pricingUnit": 73,
      "pricingUnitOfMeasure": "473",
      "debitCreditIndicator": "3",
      "cashDiscountIndicator": false,
      "checkingGroup": "8473",
      "collectiveBillingIndicator": false,
      "priceGroup": "8473",
      "accountAssignmentGroup": "78473",
      "bonusIndicator": false,
      "commissionGroup": "78473",
      "europeanArticleNumber": "cleNumber-17878473",
      "pricingSource": "78473",
      "valuationType": "e-17878473",
      "valuationDescription": "valuationDescription-17878473",
      "batchManagementRequired": false,
      "batchCharacteristic": "17878473",
      "batchBillingVariant": "t-17878473",
      "deliveryQuantity": 376544598473.855,
      "statisticsGroup": "78473",
      "costValue": 5749536153117.24,
      "subtotal1": 6811207363946.31,
      "subtotal2": 3673408302453.84,
      "subtotal3": 6882717957052,
      "subtotal4": 9279863474998.17,
      "subtotal5": 8772209671001.15,
      "subtotal6": 7737757482383.94,
      "exchangeRate": 85226.59817,
      "lastChangedOn": "2007-09-14",
      "eanUpc": "eanUpc-17878473",
      "fixedQuantityIndicator": false,
      "profitCenter": "r-17878473",
      "materialGroup1": "78473",
      "materialGroup2": "78473",
      "materialGroup3": "78473",
      "materialGroup4": "78473",
      "materialGroup5": "78473",
      "componentQuantity": 510176528057.472,
      "reasonForSubstitution": "8473",
      "specialStockIndicator": "3",
      "assignmentIndicator": "3",
      "promotionGroupId": "tionGroupId-17878473",
      "promotionId": "promotionId-17878473",
      "profitabilitySegment": "t-17878473",
      "frozenProfitabilitySegment": "t-17878473",
      "orderNumber": "ber-17878473",
      "planningMaterial": "planningMaterial-17878473",
      "planningPlant": "8473",
      "baseUnitPlanning": "473",
      "referenceUnit": "473",
      "accountAssignmentCategory": "73",
      "consumptionPosting": "3",
      "serialNumberProfile": "8473",
      "objectNumber": "objectNumber-17878473"
    },
    {
      "itemNumber": "878474",
      "wbsElement": "17878474",
      "material": "material-17878474",
      "enteredMaterial": "enteredMaterial-17878474",
      "pricingReferenceMaterial": "pricingReferenceMaterial-17878474",
      "batch": "batch-17878474",
      "materialGroup": "-17878474",
      "shortText": "shortText-17878474",
      "itemCategory": "17878474",
      "itemType": "17878474",
      "processCode": "e-17878474",
      "deliveryRelevant": true,
      "billingRelevant": true,
      "higherLevelItem": "878474",
      "alternativeItem": "878474",
      "rejectionReason": "74",
      "productHierarchy": "Hierarchy-17878474",
      "universalSalesParentNode": "universalSalesParentNode-17878474",
      "universalSalesOrigin": "n-17878474",
      "universalBatchParentNode": "universalBatchParentNode-17878474",
      "universalBatchOrigin": "n-17878474",
      "targetValue": 367260170800.066,
      "targetQuantity": 998678355813.506,
      "targetUnit": "474",
      "numeratorTargetQty": 68,
      "denominatorTargetQty": 25,
      "baseUnit": "78474",
      "substitutionNumerator": 61,
      "substitutionDenominator": 36,
      "scaleQuantity": 588605674824.576,
      "roundingQuantity": 912165168891.357,
      "roundingDate": "2013-07-09",
      "roundingFactor": 354.8,
      "externalItemNumber": "r-17878474",
      "customerMaterial": "customerMaterial-17878474",
      "usageIndicator": "8474",
      "usageIndicator2": "8474",
      "salesGroup": "78474",
      "usageIndicatorSales": "474",
      "deliveryGroup": "78474",
      "fixedQuantity": 759851152325.339,
      "unlimitedOverdelivery": "y-17878474",
      "overdeliveryTolerance": 98.81,
      "underdeliveryTolerance": 970.64,
      "billingBlockItem": "74",
      "replacementPart": true,
      "billingIndex": true,
      "division": "74",
      "businessArea": "8474",
      "netValueItem": 4258332469986.93,
      "currency": {
        "code": "801"
      },
      "partialDeliveryItem": 12,
      "partialDeliveryIndicator": "4",
      "resourceId": "resourceId-17878474",
      "batchSplitAllowed": true,
      "orderQuantity": 393822115932.479,
      "requiredQuantity": 380125053295.915,
      "confirmedQuantity": 327713628569.288,
      "cumulativeQuantity": 730976613103.453,
      "salesUnit": "474",
      "numeratorConversion": 5,
      "denominatorConversion": 9,
      "grossWeight": 283677190767.535,
      "netWeight": 757707839216.987,
      "weightUnit": "474",
      "volume": 312281805658.337,
      "volumeUnit": "474",
      "originatingDocument": "t-17878474",
      "precedingItem": "878474",
      "referenceDocument": "t-17878474",
      "referenceItem": "878474",
      "originReference": "e-17878474",
      "updateIndicator": "4",
      "completionIndicator": "4",
      "deliveryPriority": "74",
      "plant": "8474",
      "storageLocation": "8474",
      "shippingPoint": "8474",
      "route": "878474",
      "billOfMaterialKey": "17878474",
      "billOfMaterialDate": "2004-03-10",
      "billOfMaterialNumber": "17878474",
      "billOfMaterialItem": "17878474",
      "probability": 949.96,
      "createdOn": "2012-08-20",
      "createdBy": "dBy-17878474",
      "createdTime": "22:59:53",
      "taxClassification1": "4",
      "taxClassification2": "4",
      "taxClassification3": "4",
      "taxClassification4": "4",
      "taxClassification5": "4",
      "taxClassification6": "4",
      "taxClassification7": "4",
      "taxClassification8": "4",
      "taxClassification9": "4",
      "confirmedQuantityDelivery": 888912463951.77,
      "confirmedQuantitySchedule": 615930249815.678,
      "referenceIndicator": "4",
      "netPrice": 828965093059.36,
      "pricingUnit": 13,
      "pricingUnitOfMeasure": "474",
      "debitCreditIndicator": "4",
      "cashDiscountIndicator": true,
      "checkingGroup": "8474",
      "collectiveBillingIndicator": true,
      "priceGroup": "8474",
      "accountAssignmentGroup": "78474",
      "bonusIndicator": true,
      "commissionGroup": "78474",
      "europeanArticleNumber": "cleNumber-17878474",
      "pricingSource": "78474",
      "valuationType": "e-17878474",
      "valuationDescription": "valuationDescription-17878474",
      "batchManagementRequired": true,
      "batchCharacteristic": "17878474",
      "batchBillingVariant": "t-17878474",
      "deliveryQuantity": 764824123386.994,
      "statisticsGroup": "78474",
      "costValue": 5525428464356.12,
      "subtotal1": 5189513189565,
      "subtotal2": 8010556977542.49,
      "subtotal3": 2247544434447.98,
      "subtotal4": 4068563738207.27,
      "subtotal5": 9391256906405.26,
      "subtotal6": 7933306125850.09,
      "exchangeRate": 88685.30178,
      "lastChangedOn": "2006-06-04",
      "eanUpc": "eanUpc-17878474",
      "fixedQuantityIndicator": true,
      "profitCenter": "r-17878474",
      "materialGroup1": "78474",
      "materialGroup2": "78474",
      "materialGroup3": "78474",
      "materialGroup4": "78474",
      "materialGroup5": "78474",
      "componentQuantity": 51296983733.619,
      "reasonForSubstitution": "8474",
      "specialStockIndicator": "4",
      "assignmentIndicator": "4",
      "promotionGroupId": "tionGroupId-17878474",
      "promotionId": "promotionId-17878474",
      "profitabilitySegment": "t-17878474",
      "frozenProfitabilitySegment": "t-17878474",
      "orderNumber": "ber-17878474",
      "planningMaterial": "planningMaterial-17878474",
      "planningPlant": "8474",
      "baseUnitPlanning": "474",
      "referenceUnit": "474",
      "accountAssignmentCategory": "74",
      "consumptionPosting": "4",
      "serialNumberProfile": "8474",
      "objectNumber": "objectNumber-17878474"
    }
  ]
}


### SalesOrderHeader
# @name SalesOrderHeader_PATCH
PATCH {{server}}/odata/v4/projectsys/SalesOrderHeader(salesOrder='er-6301391',wbsElement='-6301391')
Content-Type: application/json

{
  "salesOrder": "er-6301391",
  "wbsElement": "-6301391",
  "createdOn": "2009-08-16",
  "createdTime": "22:59:53",
  "createdBy": "edBy-6301391",
  "quotationValidFrom": "2011-02-04",
  "quotationValidTo": "2008-08-19",
  "documentDate": "2015-04-06",
  "salesDocumentCategory": "1",
  "transactionGroup": "1",
  "salesDocumentType": "1391",
  "orderReason": "391",
  "warrantyDate": "2013-03-09",
  "collectiveNumber": "er-6301391",
  "deliveryBlock": "91",
  "billingBlock": "91",
  "netValue": 4172350068159.89,
  "currency": {
    "code": "801"
  },
  "salesOrganization": "1391",
  "distributionChannel": "91",
  "division": "91",
  "salesGroup": "1391",
  "salesOffice": "1391",
  "businessArea": "1391",
  "costCenter": "er-6301391",
  "validityStartDate": "2011-05-22",
  "validityEndDate": "2013-05-31",
  "pricingDocument": "nt-6301391",
  "requestedDeliveryDate": "2010-12-01",
  "deliveryDateTypeRule": "91",
  "pricingGroup": "91",
  "completeDeliveryIndicator": "1",
  "salesDocumentIndicator": "91",
  "salesDocumentIndicator2": "91",
  "pricingProcedure": "301391",
  "shippingCondition": "91",
  "billingType": "1391",
  "probability": 790.21,
  "description": "description-6301391",
  "customerPurchaseOrder": "customerPurchaseOrder-6301391",
  "purchaseOrderType": "1391",
  "purchaseOrderDate": "2006-01-09",
  "purchaseOrderTime": "22:59:53",
  "yourReference": "ourReference-6301391",
  "contactPerson": "rson-6301391",
  "telephoneNumber": "neNumber-6301391",
  "numberOfReminders": 92,
  "lastReminderDate": "2016-09-02",
  "soldToParty": "ty-6301391",
  "costCenterAccount": "nt-6301391",
  "statisticsGroup": "91",
  "documentCurrency": "01391",
  "lastChangedOn": "2004-05-31",
  "customerGroup1": "391",
  "customerGroup2": "391",
  "customerGroup3": "391",
  "customerGroup4": "391",
  "customerGroup5": "391",
  "agreementNumber": "er-6301391",
  "controllingArea": "1391",
  "exchangeRateType": "1391",
  "creditControlArea": "1391",
  "creditAccount": "nt-6301391",
  "creditGroup": "1391",
  "creditRepresentativeGroup": "391",
  "creditRiskCategory": "91",
  "creditCurrency": "01391",
  "creditReleaseDate": "2017-09-19",
  "nextCreditCheckDate": "2015-02-07",
  "creditNextReviewDate": "2010-09-25",
  "releasedCreditValue": 3196400681630.88,
  "lastCreditCheckDate": "2014-10-03",
  "hierarchyTypePricing": "91",
  "universalSalesRelevance": "1",
  "branchUuid": "branchUuid-6301391",
  "usageIndicator": "391",
  "usageIndicatorDescription": "geIndicatorDescription-6301391",
  "precedingDocument": "nt-6301391",
  "objectNumber": "objectNumber-6301391",
  "companyCode": "1391",
  "taxClassification1": "1",
  "taxClassification2": "1",
  "taxClassification3": "1",
  "taxClassification4": "1",
  "taxClassification5": "1",
  "taxClassification6": "1",
  "taxClassification7": "1",
  "taxClassification8": "1",
  "taxClassification9": "1",
  "referenceDocumentNumber": "ntNumber-6301391",
  "assignmentNumber": "mentNumber-6301391",
  "precedingDocumentCategory": "1",
  "pricingProcedureCustomer": "301391",
  "settlementGroup": "301391",
  "orderNumber": "mber-6301391",
  "qualityNotificationNumber": "mber-6301391",
  "documentGroupNumber": "er-6301391",
  "schemeGroup": "1391",
  "callOffPartner": "er-6301391",
  "releaseOrderDate": "2004-04-17",
  "releaseOrderTime": "22:59:53",
  "releaseOrderStatus": "91",
  "routeSchedule": "le-6301391",
  "deliveryTime": "22:59:53",
  "vatRegistrationNumber": "rationNumber-6301391",
  "taxDepartureCountry": "391",
  "externalGoodsReceiptIndicator": "1",
  "enqueueGroup": "91",
  "paymentAuthorizationDate": "2021-05-08",
  "fundsManagementPostingDate": "2008-10-22",
  "versionNumber": "er-6301391",
  "technicalHandle": "echnicalHandle-6301391",
  "productLine": "ne-6301391",
  "dangerousGoodsIndicator": "1",
  "crmGuid": "crmGuid-6301391",
  "updateTimestamp": "ateTimestamp-6301391",
  "measurementServiceId": "Id-6301391",
  "transportationManagementControlKey": "1391",
  "oilIndustryBusinessLocation": "on-6301391",
  "lastChangedByUser": "User-6301391",
  "handoverLocation": "on-6301391",
  "externalBusinessSystemId": "Id-6301391",
  "externalReferenceDocumentId": "externalReferenceDocumentId-6301391",
  "externalRevisionTimestamp": "ionTimestamp-6301391",
  "approvalStatus": "91",
  "approvalReason": "approvalReason-6301391",
  "rejectionReason": "rejectionReason-6301391",
  "solutionOrderId": "utionOrderId-6301391",
  "externalCommunicationSystemType": "pe-6301391",
  "retroPurchaseDocumentCreation": "1",
  "crossItemPricingDate": "2019-06-18",
  "dataAging": "-6301391",
  "overallRejectionStatus": "1",
  "confirmationStatus": "1",
  "creditStatusStaticCheck": "1",
  "creditStatusDynamicCheck": "1",
  "creditStatusPartialRelease": "1",
  "creditStatusManualRelease": "1",
  "creditStatusNextCheck": "1",
  "creditStatusCentralManagement": "1",
  "creditStatusTechnicalError": "1",
  "overallCreditStatus": "1",
  "overallProcessingStatus": "1",
  "deliveryBlockStatus": "1",
  "billingBlockStatus": "1",
  "billingStatus": "1",
  "billingStatusHeader": "1",
  "overallProcessingStatusDocument": "1",
  "deliveryBlockStatusHeader": "1",
  "deliveryStatus": "1",
  "deliveryStatusHeader": "1",
  "manualCompletionIndicator": "1",
  "billingBlockStatusHeader2": "1",
  "billingStatusItem": "1",
  "overallBlockStatus": "1",
  "transportationStatus": "1",
  "incompletionStatusHeader": "1",
  "incompletionStatusItem": "1",
  "billingIncompletionStatusHeader": "1",
  "billingIncompletionStatusItem": "1",
  "pricingIncompletionStatus": "1",
  "deliveryIncompletionStatusHeader": "1",
  "deliveryIncompletionStatusItem": "1",
  "incompletionProcedure1": "1",
  "incompletionProcedure2": "1",
  "incompletionProcedure3": "1",
  "incompletionProcedure4": "1",
  "incompletionProcedure5": "1",
  "incompletionStatusSales1": "1",
  "incompletionStatusSales2": "1",
  "incompletionStatusSales3": "1",
  "incompletionStatusSales4": "1",
  "incompletionStatusSales5": "1",
  "goodsMovementStatus": "1",
  "totalEmcStatus": "1",
  "totalSlcStatus": "1",
  "totalLcStatus": "1",
  "totalPcStatus": "1",
  "totalDangerousGoodsStatus": "1",
  "totalSafetyDataSheetStatus": "1",
  "bobProcessingStatus": "1",
  "downPaymentClearingStatusHeader": "1",
  "b2bMessageProcessingStatus": "1",
  "deliveryRelatedBillingStatusTotal": "1",
  "sdmVersion": "on-6301391",
  "dummySalesDocIncludeEew": "1",
  "cgtoShipmentId": "toShipmentId-6301391",
  "cgtoCoiId": "cgtoCoiId-6301391",
  "cgtoTreatmentOrderId": "tmentOrderId-6301391",
  "cgtoTherapyId": "gtoTherapyId-6301391",
  "cgtoTherapyIdName": "cgtoTherapyIdName-6301391",
  "cgtoTherapyType": "oTherapyType-6301391",
  "cgtoTherapyTypeName": "cgtoTherapyTypeName-6301391",
  "cgtoClinicalTrialSubjectId": "ClinicalTrialSubjectId-6301391",
  "cgtoPatientId": "gtoPatientId-6301391",
  "cgtoCityPharmacyRefNumber": "oCityPharmacyRefNumber-6301391",
  "ctcoStudyId": "ctcoStudyId-6301391",
  "ctcoProtocolId": "coProtocolId-6301391",
  "ctcoSiteId": "ctcoSiteId-6301391",
  "ctcoNoRegularCheck": "1",
  "ctcoPushEpoch": "ch-6301391",
  "globalLogReferenceHeader": "globalLogReferenceHeader-6301391",
  "dmbeDealNumber": "beDealNumber-6301391",
  "dmbeEvgIdRenewal": "EvgIdRenewal-6301391",
  "dmbeEvgIdCancel": "eEvgIdCancel-6301391",
  "zapcgkhIndicator": "or-6301391",
  "apcgkExtendHeader": "er-6301391",
  "zabdathDate": "2010-10-07",
  "ad01FareReference": "areReference-6301391",
  "ad01BaseDocument": "BaseDocument-6301391",
  "lastVoucherNumber": "oucherNumber-6301391",
  "publicSectorBudgetDate": "2023-07-12",
  "fashionCustomerGroup6": "391",
  "fashionCustomerGroup7": "391",
  "fashionCustomerGroup8": "391",
  "fashionCustomerGroup9": "391",
  "fashionCustomerGroup10": "391",
  "fashionReregistration": "1",
  "fashionCqCheck": "1",
  "fashionVersionStatus": "91",
  "fashionTransaction": "on-6301391",
  "fashionValueAddedService": "ce-6301391",
  "fashionCandidateDate": "2015-06-14",
  "fashionSeasonSegment": "1391",
  "fashionOsStgChange": "1",
  "constructionIndicator": "or-6301391",
  "millApplicationId": "Id-6301391",
  "tasIndicator": "1",
  "betcIndicator": "1",
  "modificationAllowed": "1",
  "cancellationAllowed": "1",
  "paymentMethod": "1391",
  "businessPartnerNumber": "er-6301391",
  "reportingFrequency": "1391",
  "logicalSystem": "em-6301391",
  "pricingCalculationIndicator": "1",
  "multipleIndicator": "1",
  "specialPaymentIndicator": "1391",
  "warrantyClaimHeader": "yClaimHeader-6301391",
  "vbakStatus": "91",
  "technicalFields": "technicalFields-6301391",
  "extensionIndicator": "or-6301391",
  "cgtoHeaderIndicator": "or-6301391",
  "studyDataIndicator": "or-6301391",
  "to_item": [
    {
      "itemNumber": "878473",
      "wbsElement": "17878473",
      "material": "material-17878473",
      "enteredMaterial": "enteredMaterial-17878473",
      "pricingReferenceMaterial": "pricingReferenceMaterial-17878473",
      "batch": "batch-17878473",
      "materialGroup": "-17878473",
      "shortText": "shortText-17878473",
      "itemCategory": "17878473",
      "itemType": "17878473",
      "processCode": "e-17878473",
      "deliveryRelevant": false,
      "billingRelevant": false,
      "higherLevelItem": "878473",
      "alternativeItem": "878473",
      "rejectionReason": "73",
      "productHierarchy": "Hierarchy-17878473",
      "universalSalesParentNode": "universalSalesParentNode-17878473",
      "universalSalesOrigin": "n-17878473",
      "universalBatchParentNode": "universalBatchParentNode-17878473",
      "universalBatchOrigin": "n-17878473",
      "targetValue": 929563533899.146,
      "targetQuantity": 541248982079.16,
      "targetUnit": "473",
      "numeratorTargetQty": 89,
      "denominatorTargetQty": 0,
      "baseUnit": "78473",
      "substitutionNumerator": 9,
      "substitutionDenominator": 99,
      "scaleQuantity": 617602698072.317,
      "roundingQuantity": 921264296988.802,
      "roundingDate": "2010-10-28",
      "roundingFactor": 449.37,
      "externalItemNumber": "r-17878473",
      "customerMaterial": "customerMaterial-17878473",
      "usageIndicator": "8473",
      "usageIndicator2": "8473",
      "salesGroup": "78473",
      "usageIndicatorSales": "473",
      "deliveryGroup": "78473",
      "fixedQuantity": 333310978634.46,
      "unlimitedOverdelivery": "y-17878473",
      "overdeliveryTolerance": 477.21,
      "underdeliveryTolerance": 731.8,
      "billingBlockItem": "73",
      "replacementPart": false,
      "billingIndex": false,
      "division": "73",
      "businessArea": "8473",
      "netValueItem": 8239936640637.3,
      "currency": {
        "code": "801"
      },
      "partialDeliveryItem": 6,
      "partialDeliveryIndicator": "3",
      "resourceId": "resourceId-17878473",
      "batchSplitAllowed": false,
      "orderQuantity": 247803186674.037,
      "requiredQuantity": 942508918486.509,
      "confirmedQuantity": 843706542875.672,
      "cumulativeQuantity": 174885191681.445,
      "salesUnit": "473",
      "numeratorConversion": 21,
      "denominatorConversion": 89,
      "grossWeight": 987186351830.243,
      "netWeight": 289037188693.527,
      "weightUnit": "473",
      "volume": 62338547359.871,
      "volumeUnit": "473",
      "originatingDocument": "t-17878473",
      "precedingItem": "878473",
      "referenceDocument": "t-17878473",
      "referenceItem": "878473",
      "originReference": "e-17878473",
      "updateIndicator": "3",
      "completionIndicator": "3",
      "deliveryPriority": "73",
      "plant": "8473",
      "storageLocation": "8473",
      "shippingPoint": "8473",
      "route": "878473",
      "billOfMaterialKey": "17878473",
      "billOfMaterialDate": "2004-08-10",
      "billOfMaterialNumber": "17878473",
      "billOfMaterialItem": "17878473",
      "probability": 5.48,
      "createdOn": "2012-07-18",
      "createdBy": "dBy-17878473",
      "createdTime": "22:59:53",
      "taxClassification1": "3",
      "taxClassification2": "3",
      "taxClassification3": "3",
      "taxClassification4": "3",
      "taxClassification5": "3",
      "taxClassification6": "3",
      "taxClassification7": "3",
      "taxClassification8": "3",
      "taxClassification9": "3",
      "confirmedQuantityDelivery": 337386625172.821,
      "confirmedQuantitySchedule": 549567164361.221,
      "referenceIndicator": "3",
      "netPrice": 3976869401438.32,
      "pricingUnit": 73,
      "pricingUnitOfMeasure": "473",
      "debitCreditIndicator": "3",
      "cashDiscountIndicator": false,
      "checkingGroup": "8473",
      "collectiveBillingIndicator": false,
      "priceGroup": "8473",
      "accountAssignmentGroup": "78473",
      "bonusIndicator": false,
      "commissionGroup": "78473",
      "europeanArticleNumber": "cleNumber-17878473",
      "pricingSource": "78473",
      "valuationType": "e-17878473",
      "valuationDescription": "valuationDescription-17878473",
      "batchManagementRequired": false,
      "batchCharacteristic": "17878473",
      "batchBillingVariant": "t-17878473",
      "deliveryQuantity": 376544598473.855,
      "statisticsGroup": "78473",
      "costValue": 5749536153117.24,
      "subtotal1": 6811207363946.31,
      "subtotal2": 3673408302453.84,
      "subtotal3": 6882717957052,
      "subtotal4": 9279863474998.17,
      "subtotal5": 8772209671001.15,
      "subtotal6": 7737757482383.94,
      "exchangeRate": 85226.59817,
      "lastChangedOn": "2007-09-14",
      "eanUpc": "eanUpc-17878473",
      "fixedQuantityIndicator": false,
      "profitCenter": "r-17878473",
      "materialGroup1": "78473",
      "materialGroup2": "78473",
      "materialGroup3": "78473",
      "materialGroup4": "78473",
      "materialGroup5": "78473",
      "componentQuantity": 510176528057.472,
      "reasonForSubstitution": "8473",
      "specialStockIndicator": "3",
      "assignmentIndicator": "3",
      "promotionGroupId": "tionGroupId-17878473",
      "promotionId": "promotionId-17878473",
      "profitabilitySegment": "t-17878473",
      "frozenProfitabilitySegment": "t-17878473",
      "orderNumber": "ber-17878473",
      "planningMaterial": "planningMaterial-17878473",
      "planningPlant": "8473",
      "baseUnitPlanning": "473",
      "referenceUnit": "473",
      "accountAssignmentCategory": "73",
      "consumptionPosting": "3",
      "serialNumberProfile": "8473",
      "objectNumber": "objectNumber-17878473"
    },
    {
      "itemNumber": "878474",
      "wbsElement": "17878474",
      "material": "material-17878474",
      "enteredMaterial": "enteredMaterial-17878474",
      "pricingReferenceMaterial": "pricingReferenceMaterial-17878474",
      "batch": "batch-17878474",
      "materialGroup": "-17878474",
      "shortText": "shortText-17878474",
      "itemCategory": "17878474",
      "itemType": "17878474",
      "processCode": "e-17878474",
      "deliveryRelevant": true,
      "billingRelevant": true,
      "higherLevelItem": "878474",
      "alternativeItem": "878474",
      "rejectionReason": "74",
      "productHierarchy": "Hierarchy-17878474",
      "universalSalesParentNode": "universalSalesParentNode-17878474",
      "universalSalesOrigin": "n-17878474",
      "universalBatchParentNode": "universalBatchParentNode-17878474",
      "universalBatchOrigin": "n-17878474",
      "targetValue": 367260170800.066,
      "targetQuantity": 998678355813.506,
      "targetUnit": "474",
      "numeratorTargetQty": 68,
      "denominatorTargetQty": 25,
      "baseUnit": "78474",
      "substitutionNumerator": 61,
      "substitutionDenominator": 36,
      "scaleQuantity": 588605674824.576,
      "roundingQuantity": 912165168891.357,
      "roundingDate": "2013-07-09",
      "roundingFactor": 354.8,
      "externalItemNumber": "r-17878474",
      "customerMaterial": "customerMaterial-17878474",
      "usageIndicator": "8474",
      "usageIndicator2": "8474",
      "salesGroup": "78474",
      "usageIndicatorSales": "474",
      "deliveryGroup": "78474",
      "fixedQuantity": 759851152325.339,
      "unlimitedOverdelivery": "y-17878474",
      "overdeliveryTolerance": 98.81,
      "underdeliveryTolerance": 970.64,
      "billingBlockItem": "74",
      "replacementPart": true,
      "billingIndex": true,
      "division": "74",
      "businessArea": "8474",
      "netValueItem": 4258332469986.93,
      "currency": {
        "code": "801"
      },
      "partialDeliveryItem": 12,
      "partialDeliveryIndicator": "4",
      "resourceId": "resourceId-17878474",
      "batchSplitAllowed": true,
      "orderQuantity": 393822115932.479,
      "requiredQuantity": 380125053295.915,
      "confirmedQuantity": 327713628569.288,
      "cumulativeQuantity": 730976613103.453,
      "salesUnit": "474",
      "numeratorConversion": 5,
      "denominatorConversion": 9,
      "grossWeight": 283677190767.535,
      "netWeight": 757707839216.987,
      "weightUnit": "474",
      "volume": 312281805658.337,
      "volumeUnit": "474",
      "originatingDocument": "t-17878474",
      "precedingItem": "878474",
      "referenceDocument": "t-17878474",
      "referenceItem": "878474",
      "originReference": "e-17878474",
      "updateIndicator": "4",
      "completionIndicator": "4",
      "deliveryPriority": "74",
      "plant": "8474",
      "storageLocation": "8474",
      "shippingPoint": "8474",
      "route": "878474",
      "billOfMaterialKey": "17878474",
      "billOfMaterialDate": "2004-03-10",
      "billOfMaterialNumber": "17878474",
      "billOfMaterialItem": "17878474",
      "probability": 949.96,
      "createdOn": "2012-08-20",
      "createdBy": "dBy-17878474",
      "createdTime": "22:59:53",
      "taxClassification1": "4",
      "taxClassification2": "4",
      "taxClassification3": "4",
      "taxClassification4": "4",
      "taxClassification5": "4",
      "taxClassification6": "4",
      "taxClassification7": "4",
      "taxClassification8": "4",
      "taxClassification9": "4",
      "confirmedQuantityDelivery": 888912463951.77,
      "confirmedQuantitySchedule": 615930249815.678,
      "referenceIndicator": "4",
      "netPrice": 828965093059.36,
      "pricingUnit": 13,
      "pricingUnitOfMeasure": "474",
      "debitCreditIndicator": "4",
      "cashDiscountIndicator": true,
      "checkingGroup": "8474",
      "collectiveBillingIndicator": true,
      "priceGroup": "8474",
      "accountAssignmentGroup": "78474",
      "bonusIndicator": true,
      "commissionGroup": "78474",
      "europeanArticleNumber": "cleNumber-17878474",
      "pricingSource": "78474",
      "valuationType": "e-17878474",
      "valuationDescription": "valuationDescription-17878474",
      "batchManagementRequired": true,
      "batchCharacteristic": "17878474",
      "batchBillingVariant": "t-17878474",
      "deliveryQuantity": 764824123386.994,
      "statisticsGroup": "78474",
      "costValue": 5525428464356.12,
      "subtotal1": 5189513189565,
      "subtotal2": 8010556977542.49,
      "subtotal3": 2247544434447.98,
      "subtotal4": 4068563738207.27,
      "subtotal5": 9391256906405.26,
      "subtotal6": 7933306125850.09,
      "exchangeRate": 88685.30178,
      "lastChangedOn": "2006-06-04",
      "eanUpc": "eanUpc-17878474",
      "fixedQuantityIndicator": true,
      "profitCenter": "r-17878474",
      "materialGroup1": "78474",
      "materialGroup2": "78474",
      "materialGroup3": "78474",
      "materialGroup4": "78474",
      "materialGroup5": "78474",
      "componentQuantity": 51296983733.619,
      "reasonForSubstitution": "8474",
      "specialStockIndicator": "4",
      "assignmentIndicator": "4",
      "promotionGroupId": "tionGroupId-17878474",
      "promotionId": "promotionId-17878474",
      "profitabilitySegment": "t-17878474",
      "frozenProfitabilitySegment": "t-17878474",
      "orderNumber": "ber-17878474",
      "planningMaterial": "planningMaterial-17878474",
      "planningPlant": "8474",
      "baseUnitPlanning": "474",
      "referenceUnit": "474",
      "accountAssignmentCategory": "74",
      "consumptionPosting": "4",
      "serialNumberProfile": "8474",
      "objectNumber": "objectNumber-17878474"
    }
  ]
}


### SalesOrderHeader
# @name SalesOrderHeader_DELETE
DELETE {{server}}/odata/v4/projectsys/SalesOrderHeader(salesOrder='er-6301391',wbsElement='-6301391')
Content-Type: application/json


### SalesOrderItem
# @name SalesOrderItem_GET
GET {{server}}/odata/v4/projectsys/SalesOrderItem



### SalesOrderItem
# @name SalesOrderItem_POST
POST {{server}}/odata/v4/projectsys/SalesOrderItem
Content-Type: application/json

{
  "itemNumber": "878473",
  "wbsElement": "17878473",
  "material": "material-17878473",
  "enteredMaterial": "enteredMaterial-17878473",
  "pricingReferenceMaterial": "pricingReferenceMaterial-17878473",
  "batch": "batch-17878473",
  "materialGroup": "-17878473",
  "shortText": "shortText-17878473",
  "itemCategory": "17878473",
  "itemType": "17878473",
  "processCode": "e-17878473",
  "deliveryRelevant": false,
  "billingRelevant": false,
  "higherLevelItem": "878473",
  "alternativeItem": "878473",
  "rejectionReason": "73",
  "productHierarchy": "Hierarchy-17878473",
  "universalSalesParentNode": "universalSalesParentNode-17878473",
  "universalSalesOrigin": "n-17878473",
  "universalBatchParentNode": "universalBatchParentNode-17878473",
  "universalBatchOrigin": "n-17878473",
  "targetValue": 929563533899.146,
  "targetQuantity": 541248982079.16,
  "targetUnit": "473",
  "numeratorTargetQty": 89,
  "denominatorTargetQty": 0,
  "baseUnit": "78473",
  "substitutionNumerator": 9,
  "substitutionDenominator": 99,
  "scaleQuantity": 617602698072.317,
  "roundingQuantity": 921264296988.802,
  "roundingDate": "2010-10-28",
  "roundingFactor": 449.37,
  "externalItemNumber": "r-17878473",
  "customerMaterial": "customerMaterial-17878473",
  "usageIndicator": "8473",
  "usageIndicator2": "8473",
  "salesGroup": "78473",
  "usageIndicatorSales": "473",
  "deliveryGroup": "78473",
  "fixedQuantity": 333310978634.46,
  "unlimitedOverdelivery": "y-17878473",
  "overdeliveryTolerance": 477.21,
  "underdeliveryTolerance": 731.8,
  "billingBlockItem": "73",
  "replacementPart": false,
  "billingIndex": false,
  "division": "73",
  "businessArea": "8473",
  "netValueItem": 8239936640637.3,
  "currency": {
    "code": "801"
  },
  "partialDeliveryItem": 6,
  "partialDeliveryIndicator": "3",
  "resourceId": "resourceId-17878473",
  "batchSplitAllowed": false,
  "orderQuantity": 247803186674.037,
  "requiredQuantity": 942508918486.509,
  "confirmedQuantity": 843706542875.672,
  "cumulativeQuantity": 174885191681.445,
  "salesUnit": "473",
  "numeratorConversion": 21,
  "denominatorConversion": 89,
  "grossWeight": 987186351830.243,
  "netWeight": 289037188693.527,
  "weightUnit": "473",
  "volume": 62338547359.871,
  "volumeUnit": "473",
  "originatingDocument": "t-17878473",
  "precedingItem": "878473",
  "referenceDocument": "t-17878473",
  "referenceItem": "878473",
  "originReference": "e-17878473",
  "updateIndicator": "3",
  "completionIndicator": "3",
  "deliveryPriority": "73",
  "plant": "8473",
  "storageLocation": "8473",
  "shippingPoint": "8473",
  "route": "878473",
  "billOfMaterialKey": "17878473",
  "billOfMaterialDate": "2004-08-10",
  "billOfMaterialNumber": "17878473",
  "billOfMaterialItem": "17878473",
  "probability": 5.48,
  "createdOn": "2012-07-18",
  "createdBy": "dBy-17878473",
  "createdTime": "22:59:53",
  "taxClassification1": "3",
  "taxClassification2": "3",
  "taxClassification3": "3",
  "taxClassification4": "3",
  "taxClassification5": "3",
  "taxClassification6": "3",
  "taxClassification7": "3",
  "taxClassification8": "3",
  "taxClassification9": "3",
  "confirmedQuantityDelivery": 337386625172.821,
  "confirmedQuantitySchedule": 549567164361.221,
  "referenceIndicator": "3",
  "netPrice": 3976869401438.32,
  "pricingUnit": 73,
  "pricingUnitOfMeasure": "473",
  "debitCreditIndicator": "3",
  "cashDiscountIndicator": false,
  "checkingGroup": "8473",
  "collectiveBillingIndicator": false,
  "priceGroup": "8473",
  "accountAssignmentGroup": "78473",
  "bonusIndicator": false,
  "commissionGroup": "78473",
  "europeanArticleNumber": "cleNumber-17878473",
  "pricingSource": "78473",
  "valuationType": "e-17878473",
  "valuationDescription": "valuationDescription-17878473",
  "batchManagementRequired": false,
  "batchCharacteristic": "17878473",
  "batchBillingVariant": "t-17878473",
  "deliveryQuantity": 376544598473.855,
  "statisticsGroup": "78473",
  "costValue": 5749536153117.24,
  "subtotal1": 6811207363946.31,
  "subtotal2": 3673408302453.84,
  "subtotal3": 6882717957052,
  "subtotal4": 9279863474998.17,
  "subtotal5": 8772209671001.15,
  "subtotal6": 7737757482383.94,
  "exchangeRate": 85226.59817,
  "lastChangedOn": "2007-09-14",
  "eanUpc": "eanUpc-17878473",
  "fixedQuantityIndicator": false,
  "profitCenter": "r-17878473",
  "materialGroup1": "78473",
  "materialGroup2": "78473",
  "materialGroup3": "78473",
  "materialGroup4": "78473",
  "materialGroup5": "78473",
  "componentQuantity": 510176528057.472,
  "reasonForSubstitution": "8473",
  "specialStockIndicator": "3",
  "assignmentIndicator": "3",
  "promotionGroupId": "tionGroupId-17878473",
  "promotionId": "promotionId-17878473",
  "profitabilitySegment": "t-17878473",
  "frozenProfitabilitySegment": "t-17878473",
  "orderNumber": "ber-17878473",
  "planningMaterial": "planningMaterial-17878473",
  "planningPlant": "8473",
  "baseUnitPlanning": "473",
  "referenceUnit": "473",
  "accountAssignmentCategory": "73",
  "consumptionPosting": "3",
  "serialNumberProfile": "8473",
  "objectNumber": "objectNumber-17878473"
}


### SalesOrderItem
# @name SalesOrderItem_PATCH
PATCH {{server}}/odata/v4/projectsys/SalesOrderItem(salesOrder='er-6301391',itemNumber='878473',wbsElement='17878473')
Content-Type: application/json

{
  "itemNumber": "878473",
  "wbsElement": "17878473",
  "material": "material-17878473",
  "enteredMaterial": "enteredMaterial-17878473",
  "pricingReferenceMaterial": "pricingReferenceMaterial-17878473",
  "batch": "batch-17878473",
  "materialGroup": "-17878473",
  "shortText": "shortText-17878473",
  "itemCategory": "17878473",
  "itemType": "17878473",
  "processCode": "e-17878473",
  "deliveryRelevant": false,
  "billingRelevant": false,
  "higherLevelItem": "878473",
  "alternativeItem": "878473",
  "rejectionReason": "73",
  "productHierarchy": "Hierarchy-17878473",
  "universalSalesParentNode": "universalSalesParentNode-17878473",
  "universalSalesOrigin": "n-17878473",
  "universalBatchParentNode": "universalBatchParentNode-17878473",
  "universalBatchOrigin": "n-17878473",
  "targetValue": 929563533899.146,
  "targetQuantity": 541248982079.16,
  "targetUnit": "473",
  "numeratorTargetQty": 89,
  "denominatorTargetQty": 0,
  "baseUnit": "78473",
  "substitutionNumerator": 9,
  "substitutionDenominator": 99,
  "scaleQuantity": 617602698072.317,
  "roundingQuantity": 921264296988.802,
  "roundingDate": "2010-10-28",
  "roundingFactor": 449.37,
  "externalItemNumber": "r-17878473",
  "customerMaterial": "customerMaterial-17878473",
  "usageIndicator": "8473",
  "usageIndicator2": "8473",
  "salesGroup": "78473",
  "usageIndicatorSales": "473",
  "deliveryGroup": "78473",
  "fixedQuantity": 333310978634.46,
  "unlimitedOverdelivery": "y-17878473",
  "overdeliveryTolerance": 477.21,
  "underdeliveryTolerance": 731.8,
  "billingBlockItem": "73",
  "replacementPart": false,
  "billingIndex": false,
  "division": "73",
  "businessArea": "8473",
  "netValueItem": 8239936640637.3,
  "currency": {
    "code": "801"
  },
  "partialDeliveryItem": 6,
  "partialDeliveryIndicator": "3",
  "resourceId": "resourceId-17878473",
  "batchSplitAllowed": false,
  "orderQuantity": 247803186674.037,
  "requiredQuantity": 942508918486.509,
  "confirmedQuantity": 843706542875.672,
  "cumulativeQuantity": 174885191681.445,
  "salesUnit": "473",
  "numeratorConversion": 21,
  "denominatorConversion": 89,
  "grossWeight": 987186351830.243,
  "netWeight": 289037188693.527,
  "weightUnit": "473",
  "volume": 62338547359.871,
  "volumeUnit": "473",
  "originatingDocument": "t-17878473",
  "precedingItem": "878473",
  "referenceDocument": "t-17878473",
  "referenceItem": "878473",
  "originReference": "e-17878473",
  "updateIndicator": "3",
  "completionIndicator": "3",
  "deliveryPriority": "73",
  "plant": "8473",
  "storageLocation": "8473",
  "shippingPoint": "8473",
  "route": "878473",
  "billOfMaterialKey": "17878473",
  "billOfMaterialDate": "2004-08-10",
  "billOfMaterialNumber": "17878473",
  "billOfMaterialItem": "17878473",
  "probability": 5.48,
  "createdOn": "2012-07-18",
  "createdBy": "dBy-17878473",
  "createdTime": "22:59:53",
  "taxClassification1": "3",
  "taxClassification2": "3",
  "taxClassification3": "3",
  "taxClassification4": "3",
  "taxClassification5": "3",
  "taxClassification6": "3",
  "taxClassification7": "3",
  "taxClassification8": "3",
  "taxClassification9": "3",
  "confirmedQuantityDelivery": 337386625172.821,
  "confirmedQuantitySchedule": 549567164361.221,
  "referenceIndicator": "3",
  "netPrice": 3976869401438.32,
  "pricingUnit": 73,
  "pricingUnitOfMeasure": "473",
  "debitCreditIndicator": "3",
  "cashDiscountIndicator": false,
  "checkingGroup": "8473",
  "collectiveBillingIndicator": false,
  "priceGroup": "8473",
  "accountAssignmentGroup": "78473",
  "bonusIndicator": false,
  "commissionGroup": "78473",
  "europeanArticleNumber": "cleNumber-17878473",
  "pricingSource": "78473",
  "valuationType": "e-17878473",
  "valuationDescription": "valuationDescription-17878473",
  "batchManagementRequired": false,
  "batchCharacteristic": "17878473",
  "batchBillingVariant": "t-17878473",
  "deliveryQuantity": 376544598473.855,
  "statisticsGroup": "78473",
  "costValue": 5749536153117.24,
  "subtotal1": 6811207363946.31,
  "subtotal2": 3673408302453.84,
  "subtotal3": 6882717957052,
  "subtotal4": 9279863474998.17,
  "subtotal5": 8772209671001.15,
  "subtotal6": 7737757482383.94,
  "exchangeRate": 85226.59817,
  "lastChangedOn": "2007-09-14",
  "eanUpc": "eanUpc-17878473",
  "fixedQuantityIndicator": false,
  "profitCenter": "r-17878473",
  "materialGroup1": "78473",
  "materialGroup2": "78473",
  "materialGroup3": "78473",
  "materialGroup4": "78473",
  "materialGroup5": "78473",
  "componentQuantity": 510176528057.472,
  "reasonForSubstitution": "8473",
  "specialStockIndicator": "3",
  "assignmentIndicator": "3",
  "promotionGroupId": "tionGroupId-17878473",
  "promotionId": "promotionId-17878473",
  "profitabilitySegment": "t-17878473",
  "frozenProfitabilitySegment": "t-17878473",
  "orderNumber": "ber-17878473",
  "planningMaterial": "planningMaterial-17878473",
  "planningPlant": "8473",
  "baseUnitPlanning": "473",
  "referenceUnit": "473",
  "accountAssignmentCategory": "73",
  "consumptionPosting": "3",
  "serialNumberProfile": "8473",
  "objectNumber": "objectNumber-17878473"
}


### SalesOrderItem
# @name SalesOrderItem_DELETE
DELETE {{server}}/odata/v4/projectsys/SalesOrderItem(salesOrder='er-6301391',itemNumber='878473',wbsElement='17878473')
Content-Type: application/json


### PurchaseDocumentHeader
# @name PurchaseDocumentHeader_GET
GET {{server}}/odata/v4/projectsys/PurchaseDocumentHeader



### PurchaseDocumentHeader
# @name PurchaseDocumentHeader_POST
POST {{server}}/odata/v4/projectsys/PurchaseDocumentHeader
Content-Type: application/json

{
  "EBELN": "r-23230638",
  "PSPNR": "23230638",
  "BUKRS": "0638",
  "BSTYP": "8",
  "BSART": "0638",
  "BSAKZ": "8",
  "LOEKZ": "8",
  "STATU": "8",
  "AEDAT": "2013-10-21",
  "ERNAM": "NAM-23230638",
  "PINCR": "30638",
  "LPONR": "30638",
  "LIFNR": "R-23230638",
  "SPRAS": "8",
  "ZTERM": "0638",
  "ZBD1T": 251,
  "ZBD2T": 711,
  "ZBD3T": 9,
  "ZBD1P": 58.482,
  "ZBD2P": 27.185,
  "EKORG": "0638",
  "EKGRP": "638",
  "WAERS": "30638",
  "WKURS": 3733.64889,
  "KUFIX": "8",
  "BEDAT": "2010-01-16",
  "KDATB": "2008-07-21",
  "KDATE": "2007-06-05",
  "BWBDT": "2018-08-25",
  "ANGDT": "2015-07-29",
  "BNDDT": "2000-12-29",
  "GWLDT": "2021-01-21",
  "AUSNR": "R-23230638",
  "ANGNR": "R-23230638",
  "IHRAN": "2013-04-08",
  "IHREZ": "REZ-23230638",
  "VERKF": "VERKF-23230638",
  "TELF1": "TELF1-23230638",
  "LLIEF": "F-23230638",
  "KUNNR": "R-23230638",
  "KONNR": "R-23230638",
  "ABGRU": "38",
  "AUTLF": "8",
  "WEAKT": "8",
  "RESWK": "0638",
  "LBLIF": "F-23230638",
  "INCO1": "638",
  "INCO2": "INCO2-23230638",
  "KTWRT": 512736639327.61,
  "SUBMI": "I-23230638",
  "KNUMV": "V-23230638",
  "KALSM": "230638",
  "STAFO": "230638",
  "LIFRE": "E-23230638",
  "EXNUM": "M-23230638",
  "UNSEZ": "SEZ-23230638",
  "LOGSY": "Y-23230638",
  "UPINC": "30638",
  "STAKO": "8",
  "FRGGR": "38",
  "FRGSX": "38",
  "FRGKE": "8",
  "FRGZU": "23230638",
  "FRGRL": "8",
  "to_PurchaseOrderItems": [
    {
      "EBELN": "m-25021961",
      "PSPNR": "25021961",
      "EBELP": "21961",
      "UNIQUEID": "IQUEID-25021961",
      "LOEKZ": "1",
      "STATU": "1",
      "AEDAT": "2006-10-11",
      "TXZ01": "TXZ01-25021961",
      "MATNR": "MATNR-25021961",
      "EMATN": "EMATN-25021961",
      "BUKRS": "1961",
      "WERKS": "1961",
      "LGORT": "1961",
      "BEDNR": "R-25021961",
      "MATKL": "-25021961",
      "INFNR": "R-25021961",
      "IDNLF": "IDNLF-25021961",
      "KTMNG": 3136542750.034,
      "MENGE": 7668204997.399,
      "MEINS": "961",
      "BPRME": "961",
      "BPUMZ": 31,
      "BPUMN": 8,
      "UMREZ": 94,
      "UMREN": 15,
      "NETPR": 645186277.61,
      "PEINH": 6,
      "NETWR": 22826421503.88,
      "BRTWR": 84577678098.95,
      "AGDAT": "2012-11-27",
      "WEBAZ": 26,
      "MWSKZ": "61",
      "TXDAT_FROM": "2020-02-24",
      "TXDAT": "2015-12-23",
      "TAX_COUNTRY": "961",
      "BONUS": "61",
      "INSMK": "1",
      "SPINF": "1",
      "PRSDR": "1",
      "SCHPR": "1",
      "MAHNZ": 32,
      "MAHN1": 15,
      "MAHN2": 21,
      "MAHN3": 59,
      "UEBTO": 97.2,
      "UEBTK": "1",
      "UNTTO": 42.5,
      "BWTAR": "R-25021961",
      "BWTTY": "1",
      "ABSKZ": "1",
      "AGMEM": "961",
      "ELIKZ": "1",
      "EREKZ": "1",
      "PSTYP": "1",
      "KNTTP": "1",
      "KZVBR": "1",
      "VRTKZ": "1",
      "TWRKZ": "1",
      "WEPOS": "1",
      "WEUNB": "1",
      "REPOS": "1",
      "WEBRE": "1",
      "KZABS": "1",
      "LABNR": "LABNR-25021961",
      "KONNR": "R-25021961",
      "KTPNR": 62960,
      "ABDAT": "2009-04-28",
      "ABFTZ": 3617560684.046,
      "ETFZ1": 672,
      "ETFZ2": 94,
      "KZSTU": "1",
      "NOTKZ": "1",
      "LMEIN": "961",
      "EVERS": "61",
      "ZWERT": 8658714310.04,
      "NAVNW": 23927062587.17,
      "ABMNG": 1370880436.49,
      "PRDAT": "2023-10-23",
      "BSTYP": "1",
      "EFFWR": 95487772808.76,
      "XOBLR": "1",
      "KUNNR": "R-25021961",
      "ADRNR": "R-25021961",
      "EKKOL": "1961",
      "SKTOF": "1",
      "STAFO": "021961",
      "PLIFZ": 163,
      "NTGEW": 6321754648.076,
      "GEWEI": "961"
    },
    {
      "EBELN": "m-25021962",
      "PSPNR": "25021962",
      "EBELP": "21962",
      "UNIQUEID": "IQUEID-25021962",
      "LOEKZ": "2",
      "STATU": "2",
      "AEDAT": "2005-08-08",
      "TXZ01": "TXZ01-25021962",
      "MATNR": "MATNR-25021962",
      "EMATN": "EMATN-25021962",
      "BUKRS": "1962",
      "WERKS": "1962",
      "LGORT": "1962",
      "BEDNR": "R-25021962",
      "MATKL": "-25021962",
      "INFNR": "R-25021962",
      "IDNLF": "IDNLF-25021962",
      "KTMNG": 640182968.167,
      "MENGE": 8498218379.016,
      "MEINS": "962",
      "BPRME": "962",
      "BPUMZ": 62,
      "BPUMN": 27,
      "UMREZ": 95,
      "UMREN": 12,
      "NETPR": 327789976.54,
      "PEINH": 63,
      "NETWR": 174077118.28,
      "BRTWR": 23776648300.19,
      "AGDAT": "2013-12-27",
      "WEBAZ": 91,
      "MWSKZ": "62",
      "TXDAT_FROM": "2007-07-16",
      "TXDAT": "2019-01-13",
      "TAX_COUNTRY": "962",
      "BONUS": "62",
      "INSMK": "2",
      "SPINF": "2",
      "PRSDR": "2",
      "SCHPR": "2",
      "MAHNZ": 91,
      "MAHN1": 54,
      "MAHN2": 71,
      "MAHN3": 81,
      "UEBTO": 18,
      "UEBTK": "2",
      "UNTTO": 33.1,
      "BWTAR": "R-25021962",
      "BWTTY": "2",
      "ABSKZ": "2",
      "AGMEM": "962",
      "ELIKZ": "2",
      "EREKZ": "2",
      "PSTYP": "2",
      "KNTTP": "2",
      "KZVBR": "2",
      "VRTKZ": "2",
      "TWRKZ": "2",
      "WEPOS": "2",
      "WEUNB": "2",
      "REPOS": "2",
      "WEBRE": "2",
      "KZABS": "2",
      "LABNR": "LABNR-25021962",
      "KONNR": "R-25021962",
      "KTPNR": 53578,
      "ABDAT": "2017-07-27",
      "ABFTZ": 9568347030.692,
      "ETFZ1": 372,
      "ETFZ2": 34,
      "KZSTU": "2",
      "NOTKZ": "2",
      "LMEIN": "962",
      "EVERS": "62",
      "ZWERT": 71262972071.52,
      "NAVNW": 5523582706.15,
      "ABMNG": 147537863.722,
      "PRDAT": "2020-08-14",
      "BSTYP": "2",
      "EFFWR": 3255173502.88,
      "XOBLR": "2",
      "KUNNR": "R-25021962",
      "ADRNR": "R-25021962",
      "EKKOL": "1962",
      "SKTOF": "2",
      "STAFO": "021962",
      "PLIFZ": 259,
      "NTGEW": 9417312456.052,
      "GEWEI": "962"
    }
  ]
}


### PurchaseDocumentHeader
# @name PurchaseDocumentHeader_PATCH
PATCH {{server}}/odata/v4/projectsys/PurchaseDocumentHeader(EBELN='r-23230638',PSPNR='23230638')
Content-Type: application/json

{
  "EBELN": "r-23230638",
  "PSPNR": "23230638",
  "BUKRS": "0638",
  "BSTYP": "8",
  "BSART": "0638",
  "BSAKZ": "8",
  "LOEKZ": "8",
  "STATU": "8",
  "AEDAT": "2013-10-21",
  "ERNAM": "NAM-23230638",
  "PINCR": "30638",
  "LPONR": "30638",
  "LIFNR": "R-23230638",
  "SPRAS": "8",
  "ZTERM": "0638",
  "ZBD1T": 251,
  "ZBD2T": 711,
  "ZBD3T": 9,
  "ZBD1P": 58.482,
  "ZBD2P": 27.185,
  "EKORG": "0638",
  "EKGRP": "638",
  "WAERS": "30638",
  "WKURS": 3733.64889,
  "KUFIX": "8",
  "BEDAT": "2010-01-16",
  "KDATB": "2008-07-21",
  "KDATE": "2007-06-05",
  "BWBDT": "2018-08-25",
  "ANGDT": "2015-07-29",
  "BNDDT": "2000-12-29",
  "GWLDT": "2021-01-21",
  "AUSNR": "R-23230638",
  "ANGNR": "R-23230638",
  "IHRAN": "2013-04-08",
  "IHREZ": "REZ-23230638",
  "VERKF": "VERKF-23230638",
  "TELF1": "TELF1-23230638",
  "LLIEF": "F-23230638",
  "KUNNR": "R-23230638",
  "KONNR": "R-23230638",
  "ABGRU": "38",
  "AUTLF": "8",
  "WEAKT": "8",
  "RESWK": "0638",
  "LBLIF": "F-23230638",
  "INCO1": "638",
  "INCO2": "INCO2-23230638",
  "KTWRT": 512736639327.61,
  "SUBMI": "I-23230638",
  "KNUMV": "V-23230638",
  "KALSM": "230638",
  "STAFO": "230638",
  "LIFRE": "E-23230638",
  "EXNUM": "M-23230638",
  "UNSEZ": "SEZ-23230638",
  "LOGSY": "Y-23230638",
  "UPINC": "30638",
  "STAKO": "8",
  "FRGGR": "38",
  "FRGSX": "38",
  "FRGKE": "8",
  "FRGZU": "23230638",
  "FRGRL": "8",
  "to_PurchaseOrderItems": [
    {
      "EBELN": "m-25021961",
      "PSPNR": "25021961",
      "EBELP": "21961",
      "UNIQUEID": "IQUEID-25021961",
      "LOEKZ": "1",
      "STATU": "1",
      "AEDAT": "2006-10-11",
      "TXZ01": "TXZ01-25021961",
      "MATNR": "MATNR-25021961",
      "EMATN": "EMATN-25021961",
      "BUKRS": "1961",
      "WERKS": "1961",
      "LGORT": "1961",
      "BEDNR": "R-25021961",
      "MATKL": "-25021961",
      "INFNR": "R-25021961",
      "IDNLF": "IDNLF-25021961",
      "KTMNG": 3136542750.034,
      "MENGE": 7668204997.399,
      "MEINS": "961",
      "BPRME": "961",
      "BPUMZ": 31,
      "BPUMN": 8,
      "UMREZ": 94,
      "UMREN": 15,
      "NETPR": 645186277.61,
      "PEINH": 6,
      "NETWR": 22826421503.88,
      "BRTWR": 84577678098.95,
      "AGDAT": "2012-11-27",
      "WEBAZ": 26,
      "MWSKZ": "61",
      "TXDAT_FROM": "2020-02-24",
      "TXDAT": "2015-12-23",
      "TAX_COUNTRY": "961",
      "BONUS": "61",
      "INSMK": "1",
      "SPINF": "1",
      "PRSDR": "1",
      "SCHPR": "1",
      "MAHNZ": 32,
      "MAHN1": 15,
      "MAHN2": 21,
      "MAHN3": 59,
      "UEBTO": 97.2,
      "UEBTK": "1",
      "UNTTO": 42.5,
      "BWTAR": "R-25021961",
      "BWTTY": "1",
      "ABSKZ": "1",
      "AGMEM": "961",
      "ELIKZ": "1",
      "EREKZ": "1",
      "PSTYP": "1",
      "KNTTP": "1",
      "KZVBR": "1",
      "VRTKZ": "1",
      "TWRKZ": "1",
      "WEPOS": "1",
      "WEUNB": "1",
      "REPOS": "1",
      "WEBRE": "1",
      "KZABS": "1",
      "LABNR": "LABNR-25021961",
      "KONNR": "R-25021961",
      "KTPNR": 62960,
      "ABDAT": "2009-04-28",
      "ABFTZ": 3617560684.046,
      "ETFZ1": 672,
      "ETFZ2": 94,
      "KZSTU": "1",
      "NOTKZ": "1",
      "LMEIN": "961",
      "EVERS": "61",
      "ZWERT": 8658714310.04,
      "NAVNW": 23927062587.17,
      "ABMNG": 1370880436.49,
      "PRDAT": "2023-10-23",
      "BSTYP": "1",
      "EFFWR": 95487772808.76,
      "XOBLR": "1",
      "KUNNR": "R-25021961",
      "ADRNR": "R-25021961",
      "EKKOL": "1961",
      "SKTOF": "1",
      "STAFO": "021961",
      "PLIFZ": 163,
      "NTGEW": 6321754648.076,
      "GEWEI": "961"
    },
    {
      "EBELN": "m-25021962",
      "PSPNR": "25021962",
      "EBELP": "21962",
      "UNIQUEID": "IQUEID-25021962",
      "LOEKZ": "2",
      "STATU": "2",
      "AEDAT": "2005-08-08",
      "TXZ01": "TXZ01-25021962",
      "MATNR": "MATNR-25021962",
      "EMATN": "EMATN-25021962",
      "BUKRS": "1962",
      "WERKS": "1962",
      "LGORT": "1962",
      "BEDNR": "R-25021962",
      "MATKL": "-25021962",
      "INFNR": "R-25021962",
      "IDNLF": "IDNLF-25021962",
      "KTMNG": 640182968.167,
      "MENGE": 8498218379.016,
      "MEINS": "962",
      "BPRME": "962",
      "BPUMZ": 62,
      "BPUMN": 27,
      "UMREZ": 95,
      "UMREN": 12,
      "NETPR": 327789976.54,
      "PEINH": 63,
      "NETWR": 174077118.28,
      "BRTWR": 23776648300.19,
      "AGDAT": "2013-12-27",
      "WEBAZ": 91,
      "MWSKZ": "62",
      "TXDAT_FROM": "2007-07-16",
      "TXDAT": "2019-01-13",
      "TAX_COUNTRY": "962",
      "BONUS": "62",
      "INSMK": "2",
      "SPINF": "2",
      "PRSDR": "2",
      "SCHPR": "2",
      "MAHNZ": 91,
      "MAHN1": 54,
      "MAHN2": 71,
      "MAHN3": 81,
      "UEBTO": 18,
      "UEBTK": "2",
      "UNTTO": 33.1,
      "BWTAR": "R-25021962",
      "BWTTY": "2",
      "ABSKZ": "2",
      "AGMEM": "962",
      "ELIKZ": "2",
      "EREKZ": "2",
      "PSTYP": "2",
      "KNTTP": "2",
      "KZVBR": "2",
      "VRTKZ": "2",
      "TWRKZ": "2",
      "WEPOS": "2",
      "WEUNB": "2",
      "REPOS": "2",
      "WEBRE": "2",
      "KZABS": "2",
      "LABNR": "LABNR-25021962",
      "KONNR": "R-25021962",
      "KTPNR": 53578,
      "ABDAT": "2017-07-27",
      "ABFTZ": 9568347030.692,
      "ETFZ1": 372,
      "ETFZ2": 34,
      "KZSTU": "2",
      "NOTKZ": "2",
      "LMEIN": "962",
      "EVERS": "62",
      "ZWERT": 71262972071.52,
      "NAVNW": 5523582706.15,
      "ABMNG": 147537863.722,
      "PRDAT": "2020-08-14",
      "BSTYP": "2",
      "EFFWR": 3255173502.88,
      "XOBLR": "2",
      "KUNNR": "R-25021962",
      "ADRNR": "R-25021962",
      "EKKOL": "1962",
      "SKTOF": "2",
      "STAFO": "021962",
      "PLIFZ": 259,
      "NTGEW": 9417312456.052,
      "GEWEI": "962"
    }
  ]
}


### PurchaseDocumentHeader
# @name PurchaseDocumentHeader_DELETE
DELETE {{server}}/odata/v4/projectsys/PurchaseDocumentHeader(EBELN='r-23230638',PSPNR='23230638')
Content-Type: application/json


### PurchaseOrderItem
# @name PurchaseOrderItem_GET
GET {{server}}/odata/v4/projectsys/PurchaseOrderItem



### PurchaseOrderItem
# @name PurchaseOrderItem_POST
POST {{server}}/odata/v4/projectsys/PurchaseOrderItem
Content-Type: application/json

{
  "EBELN": "m-25021961",
  "PSPNR": "25021961",
  "EBELP": "21961",
  "UNIQUEID": "IQUEID-25021961",
  "LOEKZ": "1",
  "STATU": "1",
  "AEDAT": "2006-10-11",
  "TXZ01": "TXZ01-25021961",
  "MATNR": "MATNR-25021961",
  "EMATN": "EMATN-25021961",
  "BUKRS": "1961",
  "WERKS": "1961",
  "LGORT": "1961",
  "BEDNR": "R-25021961",
  "MATKL": "-25021961",
  "INFNR": "R-25021961",
  "IDNLF": "IDNLF-25021961",
  "KTMNG": 3136542750.034,
  "MENGE": 7668204997.399,
  "MEINS": "961",
  "BPRME": "961",
  "BPUMZ": 31,
  "BPUMN": 8,
  "UMREZ": 94,
  "UMREN": 15,
  "NETPR": 645186277.61,
  "PEINH": 6,
  "NETWR": 22826421503.88,
  "BRTWR": 84577678098.95,
  "AGDAT": "2012-11-27",
  "WEBAZ": 26,
  "MWSKZ": "61",
  "TXDAT_FROM": "2020-02-24",
  "TXDAT": "2015-12-23",
  "TAX_COUNTRY": "961",
  "BONUS": "61",
  "INSMK": "1",
  "SPINF": "1",
  "PRSDR": "1",
  "SCHPR": "1",
  "MAHNZ": 32,
  "MAHN1": 15,
  "MAHN2": 21,
  "MAHN3": 59,
  "UEBTO": 97.2,
  "UEBTK": "1",
  "UNTTO": 42.5,
  "BWTAR": "R-25021961",
  "BWTTY": "1",
  "ABSKZ": "1",
  "AGMEM": "961",
  "ELIKZ": "1",
  "EREKZ": "1",
  "PSTYP": "1",
  "KNTTP": "1",
  "KZVBR": "1",
  "VRTKZ": "1",
  "TWRKZ": "1",
  "WEPOS": "1",
  "WEUNB": "1",
  "REPOS": "1",
  "WEBRE": "1",
  "KZABS": "1",
  "LABNR": "LABNR-25021961",
  "KONNR": "R-25021961",
  "KTPNR": 62960,
  "ABDAT": "2009-04-28",
  "ABFTZ": 3617560684.046,
  "ETFZ1": 672,
  "ETFZ2": 94,
  "KZSTU": "1",
  "NOTKZ": "1",
  "LMEIN": "961",
  "EVERS": "61",
  "ZWERT": 8658714310.04,
  "NAVNW": 23927062587.17,
  "ABMNG": 1370880436.49,
  "PRDAT": "2023-10-23",
  "BSTYP": "1",
  "EFFWR": 95487772808.76,
  "XOBLR": "1",
  "KUNNR": "R-25021961",
  "ADRNR": "R-25021961",
  "EKKOL": "1961",
  "SKTOF": "1",
  "STAFO": "021961",
  "PLIFZ": 163,
  "NTGEW": 6321754648.076,
  "GEWEI": "961"
}


### PurchaseOrderItem
# @name PurchaseOrderItem_PATCH
PATCH {{server}}/odata/v4/projectsys/PurchaseOrderItem(EBELN='m-25021961',PSPNR='25021961',EBELP='21961')
Content-Type: application/json

{
  "EBELN": "m-25021961",
  "PSPNR": "25021961",
  "EBELP": "21961",
  "UNIQUEID": "IQUEID-25021961",
  "LOEKZ": "1",
  "STATU": "1",
  "AEDAT": "2006-10-11",
  "TXZ01": "TXZ01-25021961",
  "MATNR": "MATNR-25021961",
  "EMATN": "EMATN-25021961",
  "BUKRS": "1961",
  "WERKS": "1961",
  "LGORT": "1961",
  "BEDNR": "R-25021961",
  "MATKL": "-25021961",
  "INFNR": "R-25021961",
  "IDNLF": "IDNLF-25021961",
  "KTMNG": 3136542750.034,
  "MENGE": 7668204997.399,
  "MEINS": "961",
  "BPRME": "961",
  "BPUMZ": 31,
  "BPUMN": 8,
  "UMREZ": 94,
  "UMREN": 15,
  "NETPR": 645186277.61,
  "PEINH": 6,
  "NETWR": 22826421503.88,
  "BRTWR": 84577678098.95,
  "AGDAT": "2012-11-27",
  "WEBAZ": 26,
  "MWSKZ": "61",
  "TXDAT_FROM": "2020-02-24",
  "TXDAT": "2015-12-23",
  "TAX_COUNTRY": "961",
  "BONUS": "61",
  "INSMK": "1",
  "SPINF": "1",
  "PRSDR": "1",
  "SCHPR": "1",
  "MAHNZ": 32,
  "MAHN1": 15,
  "MAHN2": 21,
  "MAHN3": 59,
  "UEBTO": 97.2,
  "UEBTK": "1",
  "UNTTO": 42.5,
  "BWTAR": "R-25021961",
  "BWTTY": "1",
  "ABSKZ": "1",
  "AGMEM": "961",
  "ELIKZ": "1",
  "EREKZ": "1",
  "PSTYP": "1",
  "KNTTP": "1",
  "KZVBR": "1",
  "VRTKZ": "1",
  "TWRKZ": "1",
  "WEPOS": "1",
  "WEUNB": "1",
  "REPOS": "1",
  "WEBRE": "1",
  "KZABS": "1",
  "LABNR": "LABNR-25021961",
  "KONNR": "R-25021961",
  "KTPNR": 62960,
  "ABDAT": "2009-04-28",
  "ABFTZ": 3617560684.046,
  "ETFZ1": 672,
  "ETFZ2": 94,
  "KZSTU": "1",
  "NOTKZ": "1",
  "LMEIN": "961",
  "EVERS": "61",
  "ZWERT": 8658714310.04,
  "NAVNW": 23927062587.17,
  "ABMNG": 1370880436.49,
  "PRDAT": "2023-10-23",
  "BSTYP": "1",
  "EFFWR": 95487772808.76,
  "XOBLR": "1",
  "KUNNR": "R-25021961",
  "ADRNR": "R-25021961",
  "EKKOL": "1961",
  "SKTOF": "1",
  "STAFO": "021961",
  "PLIFZ": 163,
  "NTGEW": 6321754648.076,
  "GEWEI": "961"
}


### PurchaseOrderItem
# @name PurchaseOrderItem_DELETE
DELETE {{server}}/odata/v4/projectsys/PurchaseOrderItem(EBELN='m-25021961',PSPNR='25021961',EBELP='21961')
Content-Type: application/json


### UpsertPROJ
# @name UpsertPROJ_POST
POST {{server}}/odata/v4/projectsys/UpsertPROJ
Content-Type: application/json

{}


### UpsertWBS
# @name UpsertWBS_POST
POST {{server}}/odata/v4/projectsys/UpsertWBS
Content-Type: application/json

{}
