@server=http://localhost:4004


### projects
# @name projects_GET
GET {{server}}/odata/v4/projectsys/projects



### projects
# @name projects_POST
POST {{server}}/odata/v4/projectsys/projects
Content-Type: application/json

{
  "PSPNR": "26717855",
  "PSPID": "PSPID-26717855",
  "POST1": "POST1-26717855",
  "OBJNR": "OBJNR-26717855",
  "ERNAM": "NAM-26717855",
  "ERDAT": "2003-05-19",
  "AENAM": "NAM-26717855",
  "AEDAT": "2007-02-09",
  "KIMSK": "KIMSK-26717855",
  "AUTOD": "5",
  "STSPD": "26717855",
  "STSPR": "26717855",
  "VERNR": "26717855",
  "VERNA": "VERNA-26717855",
  "ASTNR": "26717855",
  "ASTNA": "ASTNA-26717855",
  "VBUKR": "7855",
  "VGSBR": "7855",
  "VKOKR": "7855",
  "PRCTR": "R-26717855",
  "PWHIE": {
    "code": "441"
  },
  "ZUORD": "ZUORD-26717855",
  "TRMEQ": "5",
  "PLFAZ": "2011-10-25",
  "PLSEZ": "2022-01-19",
  "WERKS": "7855",
  "KALID": "55",
  "VGPLF": "5",
  "EWPLF": "5",
  "ZTEHT": "855",
  "NZANZ": "5",
  "PLNAW": "5",
  "VPROF": "6717855",
  "PROFL": "6717855",
  "BPROF": "717855",
  "TXTSP": "5",
  "KOSTL": "L-26717855",
  "KTRG": "TRG-26717855",
  "AEDTE": "2009-01-11",
  "AEDTP": "2010-04-02",
  "BERST": "BERST-26717855",
  "BERTR": "BERTR-26717855",
  "BERKO": "BERKO-26717855",
  "BERBU": "BERBU-26717855",
  "SPSNR": "26717855",
  "BESTA": "5",
  "SCOPE": "SCOPE-26717855",
  "XSTAT": "5",
  "TXJCD": "TXJCD-26717855",
  "ZSCHM": "6717855",
  "SCPRF": "PRF-26717855",
  "IMPRF": "717855",
  "FMPRF": "717855",
  "ABGSL": "ABGSL-26717855",
  "POSTU": "POSTU-26717855",
  "PPROF": "717855",
  "PLINT": "5",
  "LOEVM": "5",
  "INACT": "5",
  "KZBWS": "5",
  "SMPRF": "6717855",
  "FLGVRG": "5",
  "GRTOP": "5",
  "PGPRF": "717855",
  "STORT": "T-26717855",
  "LOGSYSTEM": "M-26717855",
  "KZERB": "5",
  "PARGR": "7855",
  "FUNC_AREA": "NC_AREA-26717855",
  "VKORG": "7855",
  "VTWEG": "55",
  "SPART": "55",
  "DPPPROF": "26717855",
  "VPKSTU": "55",
  "PSPID_EDIT": "PSPID_EDIT-26717855",
  "VNAME": "717855",
  "RECID": "55",
  "ETYPE": "855",
  "OTYPE": "7855",
  "JIBCL": "JIBCL-26717855",
  "JIBSA": "17855",
  "EEW_PROJ_PS_DUMMY": "5",
  "ZZADMIN": "26717855",
  "ZZADMINNAME": "ZZADMINNAME-26717855",
  "ZZCNTRCD": "55",
  "ZZPGID": "ZZPGID-26717855",
  "ZZPJSGST": "717855",
  "ZZLDPCID": "717855",
  "ZZOPPORID": "ZZOPPORID-26717855",
  "ZZCUNO": "O-26717855",
  "ZZ_PLAN_WAERS": {
    "code": "441"
  },
  "ZZMASTAGID": "855",
  "ZZ_COUNTRY_KEY": "5",
  "SCHTYP": "5",
  "SPROG": "2014-06-24",
  "EPROG": "2007-01-25",
  "ORDER_PROC_MODE": "5",
  "SETTLEMENTTYPE": "55",
  "SLWID": "6717855",
  "USR00": "USR00-26717855",
  "USR01": "USR01-26717855",
  "USR02": "2-26717855",
  "USR03": "3-26717855",
  "USR04": 9552196888.887,
  "USE04": "855",
  "USR05": 663045499.731,
  "USE05": "855",
  "USR06": 1358254070.93,
  "USE06": "17855",
  "USR07": 8455301135.487,
  "USE07": "17855",
  "USR08": "2013-04-02",
  "USR09": "2007-04-14",
  "USR10": "17855",
  "USR11": "5",
  "CPD_UPDAT": "CPD_UPDAT-26717855",
  "FERC_IND": "7855",
  "AVC_PROFILE": "717855",
  "AVC_ACTIVE": "5",
  "CPCURR": {
    "code": "441"
  },
  "PROJ_STATUS": "855",
  "to_WBSElement": [
    {
      "PSPNR": "-6585110",
      "POSID": "POSID-6585110",
      "POST1": "POST1-6585110",
      "OBJNR": "OBJNR-6585110",
      "POSKI": "POSKI-6585110",
      "ERNAM": "RNAM-6585110",
      "ERDAT": "2011-04-22",
      "AENAM": "ENAM-6585110",
      "AEDAT": "2022-10-05",
      "VERNR": "-6585110",
      "VERNA": "VERNA-6585110",
      "ASTNR": "-6585110",
      "ASTNA": "ASTNA-6585110",
      "PBUKR": "5110",
      "PGSBR": "5110",
      "PKOKR": "5110",
      "PRCTR": "TR-6585110",
      "PRART": "10",
      "STUFE": 94,
      "PLAKZ": "0",
      "BELKZ": "0",
      "FAKKZ": "0",
      "NPFAZ": "0",
      "ZUORD": "0",
      "TRMEQ": "0",
      "KVEWE": "0",
      "KAPPL": "10",
      "KALSM": "585110",
      "ZSCHL": "585110",
      "ABGSL": "585110",
      "AKOKR": "5110",
      "AKSTL": "TL-6585110",
      "FKOKR": "5110",
      "FKSTL": "TL-6585110",
      "FABKL": "10",
      "PSPRI": "0",
      "EQUNR": "EQUNR-6585110",
      "TPLNR": "TPLNR-6585110",
      "PWPOS": "85110",
      "WERKS": "5110",
      "TXTSP": "0",
      "SLWID": "6585110",
      "USR00": "USR00-6585110",
      "USR01": "USR01-6585110",
      "USR02": "02-6585110",
      "USR03": "03-6585110",
      "USR04": 6650162269.668,
      "USE04": "110",
      "USR05": 1685193267.925,
      "USE05": "110",
      "USR06": 4143615416.143,
      "USE06": "85110",
      "USR07": 1619264320.854,
      "USE07": "85110",
      "USR08": "2002-06-04",
      "USR09": "2008-09-09",
      "USR10": "0",
      "USR11": "0",
      "KOSTL": "TL-6585110",
      "KTRG": "KTRG-6585110",
      "BERST": "BERST-6585110",
      "BERTR": "BERTR-6585110",
      "BERKO": "BERKO-6585110",
      "BERBU": "BERBU-6585110",
      "CLASF": "0",
      "SPSNR": "-6585110",
      "SCOPE": "SCOPE-6585110",
      "XSTAT": "0",
      "TXJCD": "TXJCD-6585110",
      "ZSCHM": "6585110",
      "IMPRF": "585110",
      "EVGEW": 747056.41,
      "AENNR": "ENNR-6585110",
      "SUBPR": "UBPR-6585110",
      "POSTU": "POSTU-6585110",
      "PLINT": "0",
      "LOEVM": "0",
      "KZBWS": "0",
      "FPLNR": "NR-6585110",
      "TADAT": "2019-05-08",
      "IZWEK": "10",
      "ISIZE": "10",
      "IUMKZ": "85110",
      "ABUKR": "5110",
      "GRPKZ": "0",
      "PGPRF": "585110",
      "LOGSYSTEM": "EM-6585110",
      "PSPNR_LOGS": "-6585110",
      "STORT": "RT-6585110",
      "FUNC_AREA": "UNC_AREA-6585110",
      "KLVAR": "5110",
      "KALNR": "ALNR-6585110",
      "POSID_EDIT": "POSID_EDIT-6585110",
      "PSPKZ": "0",
      "MATNR": "MATNR-6585110",
      "VLPSP": "-6585110",
      "VLPKZ": "0",
      "SORT1": "T1-6585110",
      "SORT2": "T2-6585110",
      "SORT3": "T3-6585110",
      "VNAME": "585110",
      "RECID": "10",
      "ETYPE": "110",
      "OTYPE": "5110",
      "JIBCL": "110",
      "JIBSA": "85110",
      "CGPL_GUID16": "CGPL_GUID16-6585110",
      "CGPL_LOGSYS": "YS-6585110",
      "CGPL_OBJTYPE": "110",
      "ADPSP": "ADPSP-6585110",
      "RFIPPNT": "RFIPPNT-6585110",
      "EEW_PRPS_PS_DUMMY": "0",
      "RFUND": "ND-6585110",
      "RGRANT_NBR": "RGRANT_NBR-6585110",
      "FUND_FIX_ASSIGN": "0",
      "GRANT_FIX_ASSIGNED": "0",
      "FUNC_AREA_FIX_ASSIGNED": "0",
      "SPONSOREDPROG": "PONSOREDPROG-6585110",
      "SETTLEMENTELEMENT": "0",
      "SETTLMTRULEINHERITED": "0",
      "SETTLEMENTOBJECT": "TTLEMENTOBJECT-6585110",
      "CPD_UPDAT": 95819109094243,
      "FERC_IND": "5110",
      "PRPS_STATUS": 10,
      "POSNR_PRPS": "585110",
      "VBELN_PRPS": "PS-6585110",
      "ZZADMIN": "-6585110",
      "ZZADMINNAME": "ZZADMINNAME-6585110",
      "ZZCNTRCD": "10",
      "ZZPJSGST": "585110",
      "ZZLDPCID": "585110",
      "ZZOFFERING": "585110",
      "ZZSOLSEID": "585110",
      "ZZOPPORID": "ZZOPPORID-6585110",
      "ZZ_PLAN_WAERS": "85110",
      "ZZRAREFID": "ZZRAREFID-6585110",
      "ZZ_LINEITEM_ID": "585110",
      "ZZ_COUNTRY_KEY": "110",
      "ZCPM_AMR_FSST": "2002-05-19",
      "ZCPM_AMR_FSFT": "2010-09-22"
    },
    {
      "PSPNR": "-6585111",
      "POSID": "POSID-6585111",
      "POST1": "POST1-6585111",
      "OBJNR": "OBJNR-6585111",
      "POSKI": "POSKI-6585111",
      "ERNAM": "RNAM-6585111",
      "ERDAT": "2000-04-21",
      "AENAM": "ENAM-6585111",
      "AEDAT": "2015-01-28",
      "VERNR": "-6585111",
      "VERNA": "VERNA-6585111",
      "ASTNR": "-6585111",
      "ASTNA": "ASTNA-6585111",
      "PBUKR": "5111",
      "PGSBR": "5111",
      "PKOKR": "5111",
      "PRCTR": "TR-6585111",
      "PRART": "11",
      "STUFE": 51,
      "PLAKZ": "1",
      "BELKZ": "1",
      "FAKKZ": "1",
      "NPFAZ": "1",
      "ZUORD": "1",
      "TRMEQ": "1",
      "KVEWE": "1",
      "KAPPL": "11",
      "KALSM": "585111",
      "ZSCHL": "585111",
      "ABGSL": "585111",
      "AKOKR": "5111",
      "AKSTL": "TL-6585111",
      "FKOKR": "5111",
      "FKSTL": "TL-6585111",
      "FABKL": "11",
      "PSPRI": "1",
      "EQUNR": "EQUNR-6585111",
      "TPLNR": "TPLNR-6585111",
      "PWPOS": "85111",
      "WERKS": "5111",
      "TXTSP": "1",
      "SLWID": "6585111",
      "USR00": "USR00-6585111",
      "USR01": "USR01-6585111",
      "USR02": "02-6585111",
      "USR03": "03-6585111",
      "USR04": 1032890611.815,
      "USE04": "111",
      "USR05": 5018784870.875,
      "USE05": "111",
      "USR06": 4244785270.568,
      "USE06": "85111",
      "USR07": 6595585753.913,
      "USE07": "85111",
      "USR08": "2015-12-15",
      "USR09": "2012-01-13",
      "USR10": "1",
      "USR11": "1",
      "KOSTL": "TL-6585111",
      "KTRG": "KTRG-6585111",
      "BERST": "BERST-6585111",
      "BERTR": "BERTR-6585111",
      "BERKO": "BERKO-6585111",
      "BERBU": "BERBU-6585111",
      "CLASF": "1",
      "SPSNR": "-6585111",
      "SCOPE": "SCOPE-6585111",
      "XSTAT": "1",
      "TXJCD": "TXJCD-6585111",
      "ZSCHM": "6585111",
      "IMPRF": "585111",
      "EVGEW": 302.9,
      "AENNR": "ENNR-6585111",
      "SUBPR": "UBPR-6585111",
      "POSTU": "POSTU-6585111",
      "PLINT": "1",
      "LOEVM": "1",
      "KZBWS": "1",
      "FPLNR": "NR-6585111",
      "TADAT": "2003-02-13",
      "IZWEK": "11",
      "ISIZE": "11",
      "IUMKZ": "85111",
      "ABUKR": "5111",
      "GRPKZ": "1",
      "PGPRF": "585111",
      "LOGSYSTEM": "EM-6585111",
      "PSPNR_LOGS": "-6585111",
      "STORT": "RT-6585111",
      "FUNC_AREA": "UNC_AREA-6585111",
      "KLVAR": "5111",
      "KALNR": "ALNR-6585111",
      "POSID_EDIT": "POSID_EDIT-6585111",
      "PSPKZ": "1",
      "MATNR": "MATNR-6585111",
      "VLPSP": "-6585111",
      "VLPKZ": "1",
      "SORT1": "T1-6585111",
      "SORT2": "T2-6585111",
      "SORT3": "T3-6585111",
      "VNAME": "585111",
      "RECID": "11",
      "ETYPE": "111",
      "OTYPE": "5111",
      "JIBCL": "111",
      "JIBSA": "85111",
      "CGPL_GUID16": "CGPL_GUID16-6585111",
      "CGPL_LOGSYS": "YS-6585111",
      "CGPL_OBJTYPE": "111",
      "ADPSP": "ADPSP-6585111",
      "RFIPPNT": "RFIPPNT-6585111",
      "EEW_PRPS_PS_DUMMY": "1",
      "RFUND": "ND-6585111",
      "RGRANT_NBR": "RGRANT_NBR-6585111",
      "FUND_FIX_ASSIGN": "1",
      "GRANT_FIX_ASSIGNED": "1",
      "FUNC_AREA_FIX_ASSIGNED": "1",
      "SPONSOREDPROG": "PONSOREDPROG-6585111",
      "SETTLEMENTELEMENT": "1",
      "SETTLMTRULEINHERITED": "1",
      "SETTLEMENTOBJECT": "TTLEMENTOBJECT-6585111",
      "CPD_UPDAT": 341988650904537,
      "FERC_IND": "5111",
      "PRPS_STATUS": 22,
      "POSNR_PRPS": "585111",
      "VBELN_PRPS": "PS-6585111",
      "ZZADMIN": "-6585111",
      "ZZADMINNAME": "ZZADMINNAME-6585111",
      "ZZCNTRCD": "11",
      "ZZPJSGST": "585111",
      "ZZLDPCID": "585111",
      "ZZOFFERING": "585111",
      "ZZSOLSEID": "585111",
      "ZZOPPORID": "ZZOPPORID-6585111",
      "ZZ_PLAN_WAERS": "85111",
      "ZZRAREFID": "ZZRAREFID-6585111",
      "ZZ_LINEITEM_ID": "585111",
      "ZZ_COUNTRY_KEY": "111",
      "ZCPM_AMR_FSST": "2007-03-15",
      "ZCPM_AMR_FSFT": "2000-03-28"
    }
  ]
}


### projects
# @name projects_PATCH
PATCH {{server}}/odata/v4/projectsys/projects/26717855
Content-Type: application/json

{
  "PSPNR": "26717855",
  "PSPID": "PSPID-26717855",
  "POST1": "POST1-26717855",
  "OBJNR": "OBJNR-26717855",
  "ERNAM": "NAM-26717855",
  "ERDAT": "2003-05-19",
  "AENAM": "NAM-26717855",
  "AEDAT": "2007-02-09",
  "KIMSK": "KIMSK-26717855",
  "AUTOD": "5",
  "STSPD": "26717855",
  "STSPR": "26717855",
  "VERNR": "26717855",
  "VERNA": "VERNA-26717855",
  "ASTNR": "26717855",
  "ASTNA": "ASTNA-26717855",
  "VBUKR": "7855",
  "VGSBR": "7855",
  "VKOKR": "7855",
  "PRCTR": "R-26717855",
  "PWHIE": {
    "code": "441"
  },
  "ZUORD": "ZUORD-26717855",
  "TRMEQ": "5",
  "PLFAZ": "2011-10-25",
  "PLSEZ": "2022-01-19",
  "WERKS": "7855",
  "KALID": "55",
  "VGPLF": "5",
  "EWPLF": "5",
  "ZTEHT": "855",
  "NZANZ": "5",
  "PLNAW": "5",
  "VPROF": "6717855",
  "PROFL": "6717855",
  "BPROF": "717855",
  "TXTSP": "5",
  "KOSTL": "L-26717855",
  "KTRG": "TRG-26717855",
  "AEDTE": "2009-01-11",
  "AEDTP": "2010-04-02",
  "BERST": "BERST-26717855",
  "BERTR": "BERTR-26717855",
  "BERKO": "BERKO-26717855",
  "BERBU": "BERBU-26717855",
  "SPSNR": "26717855",
  "BESTA": "5",
  "SCOPE": "SCOPE-26717855",
  "XSTAT": "5",
  "TXJCD": "TXJCD-26717855",
  "ZSCHM": "6717855",
  "SCPRF": "PRF-26717855",
  "IMPRF": "717855",
  "FMPRF": "717855",
  "ABGSL": "ABGSL-26717855",
  "POSTU": "POSTU-26717855",
  "PPROF": "717855",
  "PLINT": "5",
  "LOEVM": "5",
  "INACT": "5",
  "KZBWS": "5",
  "SMPRF": "6717855",
  "FLGVRG": "5",
  "GRTOP": "5",
  "PGPRF": "717855",
  "STORT": "T-26717855",
  "LOGSYSTEM": "M-26717855",
  "KZERB": "5",
  "PARGR": "7855",
  "FUNC_AREA": "NC_AREA-26717855",
  "VKORG": "7855",
  "VTWEG": "55",
  "SPART": "55",
  "DPPPROF": "26717855",
  "VPKSTU": "55",
  "PSPID_EDIT": "PSPID_EDIT-26717855",
  "VNAME": "717855",
  "RECID": "55",
  "ETYPE": "855",
  "OTYPE": "7855",
  "JIBCL": "JIBCL-26717855",
  "JIBSA": "17855",
  "EEW_PROJ_PS_DUMMY": "5",
  "ZZADMIN": "26717855",
  "ZZADMINNAME": "ZZADMINNAME-26717855",
  "ZZCNTRCD": "55",
  "ZZPGID": "ZZPGID-26717855",
  "ZZPJSGST": "717855",
  "ZZLDPCID": "717855",
  "ZZOPPORID": "ZZOPPORID-26717855",
  "ZZCUNO": "O-26717855",
  "ZZ_PLAN_WAERS": {
    "code": "441"
  },
  "ZZMASTAGID": "855",
  "ZZ_COUNTRY_KEY": "5",
  "SCHTYP": "5",
  "SPROG": "2014-06-24",
  "EPROG": "2007-01-25",
  "ORDER_PROC_MODE": "5",
  "SETTLEMENTTYPE": "55",
  "SLWID": "6717855",
  "USR00": "USR00-26717855",
  "USR01": "USR01-26717855",
  "USR02": "2-26717855",
  "USR03": "3-26717855",
  "USR04": 9552196888.887,
  "USE04": "855",
  "USR05": 663045499.731,
  "USE05": "855",
  "USR06": 1358254070.93,
  "USE06": "17855",
  "USR07": 8455301135.487,
  "USE07": "17855",
  "USR08": "2013-04-02",
  "USR09": "2007-04-14",
  "USR10": "17855",
  "USR11": "5",
  "CPD_UPDAT": "CPD_UPDAT-26717855",
  "FERC_IND": "7855",
  "AVC_PROFILE": "717855",
  "AVC_ACTIVE": "5",
  "CPCURR": {
    "code": "441"
  },
  "PROJ_STATUS": "855",
  "to_WBSElement": [
    {
      "PSPNR": "-6585110",
      "POSID": "POSID-6585110",
      "POST1": "POST1-6585110",
      "OBJNR": "OBJNR-6585110",
      "POSKI": "POSKI-6585110",
      "ERNAM": "RNAM-6585110",
      "ERDAT": "2011-04-22",
      "AENAM": "ENAM-6585110",
      "AEDAT": "2022-10-05",
      "VERNR": "-6585110",
      "VERNA": "VERNA-6585110",
      "ASTNR": "-6585110",
      "ASTNA": "ASTNA-6585110",
      "PBUKR": "5110",
      "PGSBR": "5110",
      "PKOKR": "5110",
      "PRCTR": "TR-6585110",
      "PRART": "10",
      "STUFE": 94,
      "PLAKZ": "0",
      "BELKZ": "0",
      "FAKKZ": "0",
      "NPFAZ": "0",
      "ZUORD": "0",
      "TRMEQ": "0",
      "KVEWE": "0",
      "KAPPL": "10",
      "KALSM": "585110",
      "ZSCHL": "585110",
      "ABGSL": "585110",
      "AKOKR": "5110",
      "AKSTL": "TL-6585110",
      "FKOKR": "5110",
      "FKSTL": "TL-6585110",
      "FABKL": "10",
      "PSPRI": "0",
      "EQUNR": "EQUNR-6585110",
      "TPLNR": "TPLNR-6585110",
      "PWPOS": "85110",
      "WERKS": "5110",
      "TXTSP": "0",
      "SLWID": "6585110",
      "USR00": "USR00-6585110",
      "USR01": "USR01-6585110",
      "USR02": "02-6585110",
      "USR03": "03-6585110",
      "USR04": 6650162269.668,
      "USE04": "110",
      "USR05": 1685193267.925,
      "USE05": "110",
      "USR06": 4143615416.143,
      "USE06": "85110",
      "USR07": 1619264320.854,
      "USE07": "85110",
      "USR08": "2002-06-04",
      "USR09": "2008-09-09",
      "USR10": "0",
      "USR11": "0",
      "KOSTL": "TL-6585110",
      "KTRG": "KTRG-6585110",
      "BERST": "BERST-6585110",
      "BERTR": "BERTR-6585110",
      "BERKO": "BERKO-6585110",
      "BERBU": "BERBU-6585110",
      "CLASF": "0",
      "SPSNR": "-6585110",
      "SCOPE": "SCOPE-6585110",
      "XSTAT": "0",
      "TXJCD": "TXJCD-6585110",
      "ZSCHM": "6585110",
      "IMPRF": "585110",
      "EVGEW": 747056.41,
      "AENNR": "ENNR-6585110",
      "SUBPR": "UBPR-6585110",
      "POSTU": "POSTU-6585110",
      "PLINT": "0",
      "LOEVM": "0",
      "KZBWS": "0",
      "FPLNR": "NR-6585110",
      "TADAT": "2019-05-08",
      "IZWEK": "10",
      "ISIZE": "10",
      "IUMKZ": "85110",
      "ABUKR": "5110",
      "GRPKZ": "0",
      "PGPRF": "585110",
      "LOGSYSTEM": "EM-6585110",
      "PSPNR_LOGS": "-6585110",
      "STORT": "RT-6585110",
      "FUNC_AREA": "UNC_AREA-6585110",
      "KLVAR": "5110",
      "KALNR": "ALNR-6585110",
      "POSID_EDIT": "POSID_EDIT-6585110",
      "PSPKZ": "0",
      "MATNR": "MATNR-6585110",
      "VLPSP": "-6585110",
      "VLPKZ": "0",
      "SORT1": "T1-6585110",
      "SORT2": "T2-6585110",
      "SORT3": "T3-6585110",
      "VNAME": "585110",
      "RECID": "10",
      "ETYPE": "110",
      "OTYPE": "5110",
      "JIBCL": "110",
      "JIBSA": "85110",
      "CGPL_GUID16": "CGPL_GUID16-6585110",
      "CGPL_LOGSYS": "YS-6585110",
      "CGPL_OBJTYPE": "110",
      "ADPSP": "ADPSP-6585110",
      "RFIPPNT": "RFIPPNT-6585110",
      "EEW_PRPS_PS_DUMMY": "0",
      "RFUND": "ND-6585110",
      "RGRANT_NBR": "RGRANT_NBR-6585110",
      "FUND_FIX_ASSIGN": "0",
      "GRANT_FIX_ASSIGNED": "0",
      "FUNC_AREA_FIX_ASSIGNED": "0",
      "SPONSOREDPROG": "PONSOREDPROG-6585110",
      "SETTLEMENTELEMENT": "0",
      "SETTLMTRULEINHERITED": "0",
      "SETTLEMENTOBJECT": "TTLEMENTOBJECT-6585110",
      "CPD_UPDAT": 95819109094243,
      "FERC_IND": "5110",
      "PRPS_STATUS": 10,
      "POSNR_PRPS": "585110",
      "VBELN_PRPS": "PS-6585110",
      "ZZADMIN": "-6585110",
      "ZZADMINNAME": "ZZADMINNAME-6585110",
      "ZZCNTRCD": "10",
      "ZZPJSGST": "585110",
      "ZZLDPCID": "585110",
      "ZZOFFERING": "585110",
      "ZZSOLSEID": "585110",
      "ZZOPPORID": "ZZOPPORID-6585110",
      "ZZ_PLAN_WAERS": "85110",
      "ZZRAREFID": "ZZRAREFID-6585110",
      "ZZ_LINEITEM_ID": "585110",
      "ZZ_COUNTRY_KEY": "110",
      "ZCPM_AMR_FSST": "2002-05-19",
      "ZCPM_AMR_FSFT": "2010-09-22"
    },
    {
      "PSPNR": "-6585111",
      "POSID": "POSID-6585111",
      "POST1": "POST1-6585111",
      "OBJNR": "OBJNR-6585111",
      "POSKI": "POSKI-6585111",
      "ERNAM": "RNAM-6585111",
      "ERDAT": "2000-04-21",
      "AENAM": "ENAM-6585111",
      "AEDAT": "2015-01-28",
      "VERNR": "-6585111",
      "VERNA": "VERNA-6585111",
      "ASTNR": "-6585111",
      "ASTNA": "ASTNA-6585111",
      "PBUKR": "5111",
      "PGSBR": "5111",
      "PKOKR": "5111",
      "PRCTR": "TR-6585111",
      "PRART": "11",
      "STUFE": 51,
      "PLAKZ": "1",
      "BELKZ": "1",
      "FAKKZ": "1",
      "NPFAZ": "1",
      "ZUORD": "1",
      "TRMEQ": "1",
      "KVEWE": "1",
      "KAPPL": "11",
      "KALSM": "585111",
      "ZSCHL": "585111",
      "ABGSL": "585111",
      "AKOKR": "5111",
      "AKSTL": "TL-6585111",
      "FKOKR": "5111",
      "FKSTL": "TL-6585111",
      "FABKL": "11",
      "PSPRI": "1",
      "EQUNR": "EQUNR-6585111",
      "TPLNR": "TPLNR-6585111",
      "PWPOS": "85111",
      "WERKS": "5111",
      "TXTSP": "1",
      "SLWID": "6585111",
      "USR00": "USR00-6585111",
      "USR01": "USR01-6585111",
      "USR02": "02-6585111",
      "USR03": "03-6585111",
      "USR04": 1032890611.815,
      "USE04": "111",
      "USR05": 5018784870.875,
      "USE05": "111",
      "USR06": 4244785270.568,
      "USE06": "85111",
      "USR07": 6595585753.913,
      "USE07": "85111",
      "USR08": "2015-12-15",
      "USR09": "2012-01-13",
      "USR10": "1",
      "USR11": "1",
      "KOSTL": "TL-6585111",
      "KTRG": "KTRG-6585111",
      "BERST": "BERST-6585111",
      "BERTR": "BERTR-6585111",
      "BERKO": "BERKO-6585111",
      "BERBU": "BERBU-6585111",
      "CLASF": "1",
      "SPSNR": "-6585111",
      "SCOPE": "SCOPE-6585111",
      "XSTAT": "1",
      "TXJCD": "TXJCD-6585111",
      "ZSCHM": "6585111",
      "IMPRF": "585111",
      "EVGEW": 302.9,
      "AENNR": "ENNR-6585111",
      "SUBPR": "UBPR-6585111",
      "POSTU": "POSTU-6585111",
      "PLINT": "1",
      "LOEVM": "1",
      "KZBWS": "1",
      "FPLNR": "NR-6585111",
      "TADAT": "2003-02-13",
      "IZWEK": "11",
      "ISIZE": "11",
      "IUMKZ": "85111",
      "ABUKR": "5111",
      "GRPKZ": "1",
      "PGPRF": "585111",
      "LOGSYSTEM": "EM-6585111",
      "PSPNR_LOGS": "-6585111",
      "STORT": "RT-6585111",
      "FUNC_AREA": "UNC_AREA-6585111",
      "KLVAR": "5111",
      "KALNR": "ALNR-6585111",
      "POSID_EDIT": "POSID_EDIT-6585111",
      "PSPKZ": "1",
      "MATNR": "MATNR-6585111",
      "VLPSP": "-6585111",
      "VLPKZ": "1",
      "SORT1": "T1-6585111",
      "SORT2": "T2-6585111",
      "SORT3": "T3-6585111",
      "VNAME": "585111",
      "RECID": "11",
      "ETYPE": "111",
      "OTYPE": "5111",
      "JIBCL": "111",
      "JIBSA": "85111",
      "CGPL_GUID16": "CGPL_GUID16-6585111",
      "CGPL_LOGSYS": "YS-6585111",
      "CGPL_OBJTYPE": "111",
      "ADPSP": "ADPSP-6585111",
      "RFIPPNT": "RFIPPNT-6585111",
      "EEW_PRPS_PS_DUMMY": "1",
      "RFUND": "ND-6585111",
      "RGRANT_NBR": "RGRANT_NBR-6585111",
      "FUND_FIX_ASSIGN": "1",
      "GRANT_FIX_ASSIGNED": "1",
      "FUNC_AREA_FIX_ASSIGNED": "1",
      "SPONSOREDPROG": "PONSOREDPROG-6585111",
      "SETTLEMENTELEMENT": "1",
      "SETTLMTRULEINHERITED": "1",
      "SETTLEMENTOBJECT": "TTLEMENTOBJECT-6585111",
      "CPD_UPDAT": 341988650904537,
      "FERC_IND": "5111",
      "PRPS_STATUS": 22,
      "POSNR_PRPS": "585111",
      "VBELN_PRPS": "PS-6585111",
      "ZZADMIN": "-6585111",
      "ZZADMINNAME": "ZZADMINNAME-6585111",
      "ZZCNTRCD": "11",
      "ZZPJSGST": "585111",
      "ZZLDPCID": "585111",
      "ZZOFFERING": "585111",
      "ZZSOLSEID": "585111",
      "ZZOPPORID": "ZZOPPORID-6585111",
      "ZZ_PLAN_WAERS": "85111",
      "ZZRAREFID": "ZZRAREFID-6585111",
      "ZZ_LINEITEM_ID": "585111",
      "ZZ_COUNTRY_KEY": "111",
      "ZCPM_AMR_FSST": "2007-03-15",
      "ZCPM_AMR_FSFT": "2000-03-28"
    }
  ]
}


### projects
# @name projects_DELETE
DELETE {{server}}/odata/v4/projectsys/projects/26717855
Content-Type: application/json


### Currencies
# @name Currencies_GET
GET {{server}}/odata/v4/projectsys/Currencies



### WBSElements
# @name WBSElements_GET
GET {{server}}/odata/v4/projectsys/WBSElements



### WBSElements
# @name WBSElements_POST
POST {{server}}/odata/v4/projectsys/WBSElements
Content-Type: application/json

{
  "PSPNR": "-6585110",
  "POSID": "POSID-6585110",
  "POST1": "POST1-6585110",
  "OBJNR": "OBJNR-6585110",
  "POSKI": "POSKI-6585110",
  "ERNAM": "RNAM-6585110",
  "ERDAT": "2011-04-22",
  "AENAM": "ENAM-6585110",
  "AEDAT": "2022-10-05",
  "VERNR": "-6585110",
  "VERNA": "VERNA-6585110",
  "ASTNR": "-6585110",
  "ASTNA": "ASTNA-6585110",
  "PBUKR": "5110",
  "PGSBR": "5110",
  "PKOKR": "5110",
  "PRCTR": "TR-6585110",
  "PRART": "10",
  "STUFE": 94,
  "PLAKZ": "0",
  "BELKZ": "0",
  "FAKKZ": "0",
  "NPFAZ": "0",
  "ZUORD": "0",
  "TRMEQ": "0",
  "KVEWE": "0",
  "KAPPL": "10",
  "KALSM": "585110",
  "ZSCHL": "585110",
  "ABGSL": "585110",
  "AKOKR": "5110",
  "AKSTL": "TL-6585110",
  "FKOKR": "5110",
  "FKSTL": "TL-6585110",
  "FABKL": "10",
  "PSPRI": "0",
  "EQUNR": "EQUNR-6585110",
  "TPLNR": "TPLNR-6585110",
  "PWPOS": "85110",
  "WERKS": "5110",
  "TXTSP": "0",
  "SLWID": "6585110",
  "USR00": "USR00-6585110",
  "USR01": "USR01-6585110",
  "USR02": "02-6585110",
  "USR03": "03-6585110",
  "USR04": 6650162269.668,
  "USE04": "110",
  "USR05": 1685193267.925,
  "USE05": "110",
  "USR06": 4143615416.143,
  "USE06": "85110",
  "USR07": 1619264320.854,
  "USE07": "85110",
  "USR08": "2002-06-04",
  "USR09": "2008-09-09",
  "USR10": "0",
  "USR11": "0",
  "KOSTL": "TL-6585110",
  "KTRG": "KTRG-6585110",
  "BERST": "BERST-6585110",
  "BERTR": "BERTR-6585110",
  "BERKO": "BERKO-6585110",
  "BERBU": "BERBU-6585110",
  "CLASF": "0",
  "SPSNR": "-6585110",
  "SCOPE": "SCOPE-6585110",
  "XSTAT": "0",
  "TXJCD": "TXJCD-6585110",
  "ZSCHM": "6585110",
  "IMPRF": "585110",
  "EVGEW": 747056.41,
  "AENNR": "ENNR-6585110",
  "SUBPR": "UBPR-6585110",
  "POSTU": "POSTU-6585110",
  "PLINT": "0",
  "LOEVM": "0",
  "KZBWS": "0",
  "FPLNR": "NR-6585110",
  "TADAT": "2019-05-08",
  "IZWEK": "10",
  "ISIZE": "10",
  "IUMKZ": "85110",
  "ABUKR": "5110",
  "GRPKZ": "0",
  "PGPRF": "585110",
  "LOGSYSTEM": "EM-6585110",
  "PSPNR_LOGS": "-6585110",
  "STORT": "RT-6585110",
  "FUNC_AREA": "UNC_AREA-6585110",
  "KLVAR": "5110",
  "KALNR": "ALNR-6585110",
  "POSID_EDIT": "POSID_EDIT-6585110",
  "PSPKZ": "0",
  "MATNR": "MATNR-6585110",
  "VLPSP": "-6585110",
  "VLPKZ": "0",
  "SORT1": "T1-6585110",
  "SORT2": "T2-6585110",
  "SORT3": "T3-6585110",
  "VNAME": "585110",
  "RECID": "10",
  "ETYPE": "110",
  "OTYPE": "5110",
  "JIBCL": "110",
  "JIBSA": "85110",
  "CGPL_GUID16": "CGPL_GUID16-6585110",
  "CGPL_LOGSYS": "YS-6585110",
  "CGPL_OBJTYPE": "110",
  "ADPSP": "ADPSP-6585110",
  "RFIPPNT": "RFIPPNT-6585110",
  "EEW_PRPS_PS_DUMMY": "0",
  "RFUND": "ND-6585110",
  "RGRANT_NBR": "RGRANT_NBR-6585110",
  "FUND_FIX_ASSIGN": "0",
  "GRANT_FIX_ASSIGNED": "0",
  "FUNC_AREA_FIX_ASSIGNED": "0",
  "SPONSOREDPROG": "PONSOREDPROG-6585110",
  "SETTLEMENTELEMENT": "0",
  "SETTLMTRULEINHERITED": "0",
  "SETTLEMENTOBJECT": "TTLEMENTOBJECT-6585110",
  "CPD_UPDAT": 95819109094243,
  "FERC_IND": "5110",
  "PRPS_STATUS": 10,
  "POSNR_PRPS": "585110",
  "VBELN_PRPS": "PS-6585110",
  "ZZADMIN": "-6585110",
  "ZZADMINNAME": "ZZADMINNAME-6585110",
  "ZZCNTRCD": "10",
  "ZZPJSGST": "585110",
  "ZZLDPCID": "585110",
  "ZZOFFERING": "585110",
  "ZZSOLSEID": "585110",
  "ZZOPPORID": "ZZOPPORID-6585110",
  "ZZ_PLAN_WAERS": "85110",
  "ZZRAREFID": "ZZRAREFID-6585110",
  "ZZ_LINEITEM_ID": "585110",
  "ZZ_COUNTRY_KEY": "110",
  "ZCPM_AMR_FSST": "2002-05-19",
  "ZCPM_AMR_FSFT": "2010-09-22"
}


### WBSElements
# @name WBSElements_PATCH
PATCH {{server}}/odata/v4/projectsys/WBSElements/-6585110
Content-Type: application/json

{
  "PSPNR": "-6585110",
  "POSID": "POSID-6585110",
  "POST1": "POST1-6585110",
  "OBJNR": "OBJNR-6585110",
  "POSKI": "POSKI-6585110",
  "ERNAM": "RNAM-6585110",
  "ERDAT": "2011-04-22",
  "AENAM": "ENAM-6585110",
  "AEDAT": "2022-10-05",
  "VERNR": "-6585110",
  "VERNA": "VERNA-6585110",
  "ASTNR": "-6585110",
  "ASTNA": "ASTNA-6585110",
  "PBUKR": "5110",
  "PGSBR": "5110",
  "PKOKR": "5110",
  "PRCTR": "TR-6585110",
  "PRART": "10",
  "STUFE": 94,
  "PLAKZ": "0",
  "BELKZ": "0",
  "FAKKZ": "0",
  "NPFAZ": "0",
  "ZUORD": "0",
  "TRMEQ": "0",
  "KVEWE": "0",
  "KAPPL": "10",
  "KALSM": "585110",
  "ZSCHL": "585110",
  "ABGSL": "585110",
  "AKOKR": "5110",
  "AKSTL": "TL-6585110",
  "FKOKR": "5110",
  "FKSTL": "TL-6585110",
  "FABKL": "10",
  "PSPRI": "0",
  "EQUNR": "EQUNR-6585110",
  "TPLNR": "TPLNR-6585110",
  "PWPOS": "85110",
  "WERKS": "5110",
  "TXTSP": "0",
  "SLWID": "6585110",
  "USR00": "USR00-6585110",
  "USR01": "USR01-6585110",
  "USR02": "02-6585110",
  "USR03": "03-6585110",
  "USR04": 6650162269.668,
  "USE04": "110",
  "USR05": 1685193267.925,
  "USE05": "110",
  "USR06": 4143615416.143,
  "USE06": "85110",
  "USR07": 1619264320.854,
  "USE07": "85110",
  "USR08": "2002-06-04",
  "USR09": "2008-09-09",
  "USR10": "0",
  "USR11": "0",
  "KOSTL": "TL-6585110",
  "KTRG": "KTRG-6585110",
  "BERST": "BERST-6585110",
  "BERTR": "BERTR-6585110",
  "BERKO": "BERKO-6585110",
  "BERBU": "BERBU-6585110",
  "CLASF": "0",
  "SPSNR": "-6585110",
  "SCOPE": "SCOPE-6585110",
  "XSTAT": "0",
  "TXJCD": "TXJCD-6585110",
  "ZSCHM": "6585110",
  "IMPRF": "585110",
  "EVGEW": 747056.41,
  "AENNR": "ENNR-6585110",
  "SUBPR": "UBPR-6585110",
  "POSTU": "POSTU-6585110",
  "PLINT": "0",
  "LOEVM": "0",
  "KZBWS": "0",
  "FPLNR": "NR-6585110",
  "TADAT": "2019-05-08",
  "IZWEK": "10",
  "ISIZE": "10",
  "IUMKZ": "85110",
  "ABUKR": "5110",
  "GRPKZ": "0",
  "PGPRF": "585110",
  "LOGSYSTEM": "EM-6585110",
  "PSPNR_LOGS": "-6585110",
  "STORT": "RT-6585110",
  "FUNC_AREA": "UNC_AREA-6585110",
  "KLVAR": "5110",
  "KALNR": "ALNR-6585110",
  "POSID_EDIT": "POSID_EDIT-6585110",
  "PSPKZ": "0",
  "MATNR": "MATNR-6585110",
  "VLPSP": "-6585110",
  "VLPKZ": "0",
  "SORT1": "T1-6585110",
  "SORT2": "T2-6585110",
  "SORT3": "T3-6585110",
  "VNAME": "585110",
  "RECID": "10",
  "ETYPE": "110",
  "OTYPE": "5110",
  "JIBCL": "110",
  "JIBSA": "85110",
  "CGPL_GUID16": "CGPL_GUID16-6585110",
  "CGPL_LOGSYS": "YS-6585110",
  "CGPL_OBJTYPE": "110",
  "ADPSP": "ADPSP-6585110",
  "RFIPPNT": "RFIPPNT-6585110",
  "EEW_PRPS_PS_DUMMY": "0",
  "RFUND": "ND-6585110",
  "RGRANT_NBR": "RGRANT_NBR-6585110",
  "FUND_FIX_ASSIGN": "0",
  "GRANT_FIX_ASSIGNED": "0",
  "FUNC_AREA_FIX_ASSIGNED": "0",
  "SPONSOREDPROG": "PONSOREDPROG-6585110",
  "SETTLEMENTELEMENT": "0",
  "SETTLMTRULEINHERITED": "0",
  "SETTLEMENTOBJECT": "TTLEMENTOBJECT-6585110",
  "CPD_UPDAT": 95819109094243,
  "FERC_IND": "5110",
  "PRPS_STATUS": 10,
  "POSNR_PRPS": "585110",
  "VBELN_PRPS": "PS-6585110",
  "ZZADMIN": "-6585110",
  "ZZADMINNAME": "ZZADMINNAME-6585110",
  "ZZCNTRCD": "10",
  "ZZPJSGST": "585110",
  "ZZLDPCID": "585110",
  "ZZOFFERING": "585110",
  "ZZSOLSEID": "585110",
  "ZZOPPORID": "ZZOPPORID-6585110",
  "ZZ_PLAN_WAERS": "85110",
  "ZZRAREFID": "ZZRAREFID-6585110",
  "ZZ_LINEITEM_ID": "585110",
  "ZZ_COUNTRY_KEY": "110",
  "ZCPM_AMR_FSST": "2002-05-19",
  "ZCPM_AMR_FSFT": "2010-09-22"
}


### WBSElements
# @name WBSElements_DELETE
DELETE {{server}}/odata/v4/projectsys/WBSElements/-6585110
Content-Type: application/json


### SalesOrderHeader
# @name SalesOrderHeader_GET
GET {{server}}/odata/v4/projectsys/SalesOrderHeader



### SalesOrderHeader
# @name SalesOrderHeader_POST
POST {{server}}/odata/v4/projectsys/SalesOrderHeader
Content-Type: application/json

{
  "salesOrder": "er-8957289",
  "wbsElement": "-8957289",
  "createdOn": "2023-06-18",
  "createdTime": "22:59:53",
  "createdBy": "edBy-8957289",
  "quotationValidFrom": "2018-05-20",
  "quotationValidTo": "2013-11-20",
  "documentDate": "2009-06-29",
  "salesDocumentCategory": "9",
  "transactionGroup": "9",
  "salesDocumentType": "7289",
  "orderReason": "289",
  "warrantyDate": "2009-01-24",
  "collectiveNumber": "er-8957289",
  "deliveryBlock": "89",
  "billingBlock": "89",
  "netValue": 9278799764800.35,
  "currency": {
    "code": "441"
  },
  "salesOrganization": "7289",
  "distributionChannel": "89",
  "division": "89",
  "salesGroup": "7289",
  "salesOffice": "7289",
  "businessArea": "7289",
  "costCenter": "er-8957289",
  "validityStartDate": "2011-04-24",
  "validityEndDate": "2020-08-02",
  "pricingDocument": "nt-8957289",
  "requestedDeliveryDate": "2021-08-06",
  "deliveryDateTypeRule": "89",
  "pricingGroup": "89",
  "completeDeliveryIndicator": "9",
  "salesDocumentIndicator": "89",
  "salesDocumentIndicator2": "89",
  "pricingProcedure": "957289",
  "shippingCondition": "89",
  "billingType": "7289",
  "probability": 270.25,
  "description": "description-8957289",
  "customerPurchaseOrder": "customerPurchaseOrder-8957289",
  "purchaseOrderType": "7289",
  "purchaseOrderDate": "2018-06-17",
  "purchaseOrderTime": "22:59:53",
  "yourReference": "ourReference-8957289",
  "contactPerson": "rson-8957289",
  "telephoneNumber": "neNumber-8957289",
  "numberOfReminders": 64,
  "lastReminderDate": "2012-08-07",
  "soldToParty": "ty-8957289",
  "costCenterAccount": "nt-8957289",
  "statisticsGroup": "89",
  "documentCurrency": "57289",
  "lastChangedOn": "2016-05-01",
  "customerGroup1": "289",
  "customerGroup2": "289",
  "customerGroup3": "289",
  "customerGroup4": "289",
  "customerGroup5": "289",
  "agreementNumber": "er-8957289",
  "controllingArea": "7289",
  "exchangeRateType": "7289",
  "creditControlArea": "7289",
  "creditAccount": "nt-8957289",
  "creditGroup": "7289",
  "creditRepresentativeGroup": "289",
  "creditRiskCategory": "89",
  "creditCurrency": "57289",
  "creditReleaseDate": "2015-08-02",
  "nextCreditCheckDate": "2010-05-13",
  "creditNextReviewDate": "2011-07-27",
  "releasedCreditValue": 6771852918965.79,
  "lastCreditCheckDate": "2016-10-15",
  "hierarchyTypePricing": "89",
  "universalSalesRelevance": "9",
  "branchUuid": "branchUuid-8957289",
  "usageIndicator": "289",
  "usageIndicatorDescription": "geIndicatorDescription-8957289",
  "precedingDocument": "nt-8957289",
  "objectNumber": "objectNumber-8957289",
  "companyCode": "7289",
  "taxClassification1": "9",
  "taxClassification2": "9",
  "taxClassification3": "9",
  "taxClassification4": "9",
  "taxClassification5": "9",
  "taxClassification6": "9",
  "taxClassification7": "9",
  "taxClassification8": "9",
  "taxClassification9": "9",
  "referenceDocumentNumber": "ntNumber-8957289",
  "assignmentNumber": "mentNumber-8957289",
  "precedingDocumentCategory": "9",
  "pricingProcedureCustomer": "957289",
  "settlementGroup": "957289",
  "orderNumber": "mber-8957289",
  "qualityNotificationNumber": "mber-8957289",
  "documentGroupNumber": "er-8957289",
  "schemeGroup": "7289",
  "callOffPartner": "er-8957289",
  "releaseOrderDate": "2011-10-06",
  "releaseOrderTime": "22:59:53",
  "releaseOrderStatus": "89",
  "routeSchedule": "le-8957289",
  "deliveryTime": "22:59:53",
  "vatRegistrationNumber": "rationNumber-8957289",
  "taxDepartureCountry": "289",
  "externalGoodsReceiptIndicator": "9",
  "enqueueGroup": "89",
  "paymentAuthorizationDate": "2012-08-19",
  "fundsManagementPostingDate": "2016-06-24",
  "versionNumber": "er-8957289",
  "technicalHandle": "echnicalHandle-8957289",
  "productLine": "ne-8957289",
  "dangerousGoodsIndicator": "9",
  "crmGuid": "crmGuid-8957289",
  "updateTimestamp": "ateTimestamp-8957289",
  "measurementServiceId": "Id-8957289",
  "transportationManagementControlKey": "7289",
  "oilIndustryBusinessLocation": "on-8957289",
  "lastChangedByUser": "User-8957289",
  "handoverLocation": "on-8957289",
  "externalBusinessSystemId": "Id-8957289",
  "externalReferenceDocumentId": "externalReferenceDocumentId-8957289",
  "externalRevisionTimestamp": "ionTimestamp-8957289",
  "approvalStatus": "89",
  "approvalReason": "approvalReason-8957289",
  "rejectionReason": "rejectionReason-8957289",
  "solutionOrderId": "utionOrderId-8957289",
  "externalCommunicationSystemType": "pe-8957289",
  "retroPurchaseDocumentCreation": "9",
  "crossItemPricingDate": "2008-09-17",
  "dataAging": "-8957289",
  "overallRejectionStatus": "9",
  "confirmationStatus": "9",
  "creditStatusStaticCheck": "9",
  "creditStatusDynamicCheck": "9",
  "creditStatusPartialRelease": "9",
  "creditStatusManualRelease": "9",
  "creditStatusNextCheck": "9",
  "creditStatusCentralManagement": "9",
  "creditStatusTechnicalError": "9",
  "overallCreditStatus": "9",
  "overallProcessingStatus": "9",
  "deliveryBlockStatus": "9",
  "billingBlockStatus": "9",
  "billingStatus": "9",
  "billingStatusHeader": "9",
  "overallProcessingStatusDocument": "9",
  "deliveryBlockStatusHeader": "9",
  "deliveryStatus": "9",
  "deliveryStatusHeader": "9",
  "manualCompletionIndicator": "9",
  "billingBlockStatusHeader2": "9",
  "billingStatusItem": "9",
  "overallBlockStatus": "9",
  "transportationStatus": "9",
  "incompletionStatusHeader": "9",
  "incompletionStatusItem": "9",
  "billingIncompletionStatusHeader": "9",
  "billingIncompletionStatusItem": "9",
  "pricingIncompletionStatus": "9",
  "deliveryIncompletionStatusHeader": "9",
  "deliveryIncompletionStatusItem": "9",
  "incompletionProcedure1": "9",
  "incompletionProcedure2": "9",
  "incompletionProcedure3": "9",
  "incompletionProcedure4": "9",
  "incompletionProcedure5": "9",
  "incompletionStatusSales1": "9",
  "incompletionStatusSales2": "9",
  "incompletionStatusSales3": "9",
  "incompletionStatusSales4": "9",
  "incompletionStatusSales5": "9",
  "goodsMovementStatus": "9",
  "totalEmcStatus": "9",
  "totalSlcStatus": "9",
  "totalLcStatus": "9",
  "totalPcStatus": "9",
  "totalDangerousGoodsStatus": "9",
  "totalSafetyDataSheetStatus": "9",
  "bobProcessingStatus": "9",
  "downPaymentClearingStatusHeader": "9",
  "b2bMessageProcessingStatus": "9",
  "deliveryRelatedBillingStatusTotal": "9",
  "sdmVersion": "on-8957289",
  "dummySalesDocIncludeEew": "9",
  "cgtoShipmentId": "toShipmentId-8957289",
  "cgtoCoiId": "cgtoCoiId-8957289",
  "cgtoTreatmentOrderId": "tmentOrderId-8957289",
  "cgtoTherapyId": "gtoTherapyId-8957289",
  "cgtoTherapyIdName": "cgtoTherapyIdName-8957289",
  "cgtoTherapyType": "oTherapyType-8957289",
  "cgtoTherapyTypeName": "cgtoTherapyTypeName-8957289",
  "cgtoClinicalTrialSubjectId": "ClinicalTrialSubjectId-8957289",
  "cgtoPatientId": "gtoPatientId-8957289",
  "cgtoCityPharmacyRefNumber": "oCityPharmacyRefNumber-8957289",
  "ctcoStudyId": "ctcoStudyId-8957289",
  "ctcoProtocolId": "coProtocolId-8957289",
  "ctcoSiteId": "ctcoSiteId-8957289",
  "ctcoNoRegularCheck": "9",
  "ctcoPushEpoch": "ch-8957289",
  "globalLogReferenceHeader": "globalLogReferenceHeader-8957289",
  "dmbeDealNumber": "beDealNumber-8957289",
  "dmbeEvgIdRenewal": "EvgIdRenewal-8957289",
  "dmbeEvgIdCancel": "eEvgIdCancel-8957289",
  "zapcgkhIndicator": "or-8957289",
  "apcgkExtendHeader": "er-8957289",
  "zabdathDate": "2021-02-07",
  "ad01FareReference": "areReference-8957289",
  "ad01BaseDocument": "BaseDocument-8957289",
  "lastVoucherNumber": "oucherNumber-8957289",
  "publicSectorBudgetDate": "2014-08-09",
  "fashionCustomerGroup6": "289",
  "fashionCustomerGroup7": "289",
  "fashionCustomerGroup8": "289",
  "fashionCustomerGroup9": "289",
  "fashionCustomerGroup10": "289",
  "fashionReregistration": "9",
  "fashionCqCheck": "9",
  "fashionVersionStatus": "89",
  "fashionTransaction": "on-8957289",
  "fashionValueAddedService": "ce-8957289",
  "fashionCandidateDate": "2014-05-12",
  "fashionSeasonSegment": "7289",
  "fashionOsStgChange": "9",
  "constructionIndicator": "or-8957289",
  "millApplicationId": "Id-8957289",
  "tasIndicator": "9",
  "betcIndicator": "9",
  "modificationAllowed": "9",
  "cancellationAllowed": "9",
  "paymentMethod": "7289",
  "businessPartnerNumber": "er-8957289",
  "reportingFrequency": "7289",
  "logicalSystem": "em-8957289",
  "pricingCalculationIndicator": "9",
  "multipleIndicator": "9",
  "specialPaymentIndicator": "7289",
  "warrantyClaimHeader": "yClaimHeader-8957289",
  "vbakStatus": "89",
  "technicalFields": "technicalFields-8957289",
  "extensionIndicator": "or-8957289",
  "cgtoHeaderIndicator": "or-8957289",
  "studyDataIndicator": "or-8957289",
  "to_item": [
    {
      "itemNumber": "707946",
      "wbsElement": "29707946",
      "material": "material-29707946",
      "enteredMaterial": "enteredMaterial-29707946",
      "pricingReferenceMaterial": "pricingReferenceMaterial-29707946",
      "batch": "batch-29707946",
      "materialGroup": "-29707946",
      "shortText": "shortText-29707946",
      "itemCategory": "29707946",
      "itemType": "29707946",
      "processCode": "e-29707946",
      "deliveryRelevant": true,
      "billingRelevant": true,
      "higherLevelItem": "707946",
      "alternativeItem": "707946",
      "rejectionReason": "46",
      "productHierarchy": "Hierarchy-29707946",
      "universalSalesParentNode": "universalSalesParentNode-29707946",
      "universalSalesOrigin": "n-29707946",
      "universalBatchParentNode": "universalBatchParentNode-29707946",
      "universalBatchOrigin": "n-29707946",
      "targetValue": 868443280895.483,
      "targetQuantity": 92959585432.105,
      "targetUnit": "946",
      "numeratorTargetQty": 86,
      "denominatorTargetQty": 52,
      "baseUnit": "07946",
      "substitutionNumerator": 17,
      "substitutionDenominator": 19,
      "scaleQuantity": 779336434919.539,
      "roundingQuantity": 872301464785.819,
      "roundingDate": "2021-08-21",
      "roundingFactor": 287.31,
      "externalItemNumber": "r-29707946",
      "customerMaterial": "customerMaterial-29707946",
      "usageIndicator": "7946",
      "usageIndicator2": "7946",
      "salesGroup": "07946",
      "usageIndicatorSales": "946",
      "deliveryGroup": "07946",
      "fixedQuantity": 624259730084.71,
      "unlimitedOverdelivery": "y-29707946",
      "overdeliveryTolerance": 570.22,
      "underdeliveryTolerance": 328.57,
      "billingBlockItem": "46",
      "replacementPart": true,
      "billingIndex": true,
      "division": "46",
      "businessArea": "7946",
      "netValueItem": 2145691665283.97,
      "currency": {
        "code": "441"
      },
      "partialDeliveryItem": 23,
      "partialDeliveryIndicator": "6",
      "resourceId": "resourceId-29707946",
      "batchSplitAllowed": true,
      "orderQuantity": 884280289273.537,
      "requiredQuantity": 299636305524.633,
      "confirmedQuantity": 868369670890.077,
      "cumulativeQuantity": 184080777523.503,
      "salesUnit": "946",
      "numeratorConversion": 98,
      "denominatorConversion": 93,
      "grossWeight": 625648847485.673,
      "netWeight": 855816663190.378,
      "weightUnit": "946",
      "volume": 747811085824.938,
      "volumeUnit": "946",
      "originatingDocument": "t-29707946",
      "precedingItem": "707946",
      "referenceDocument": "t-29707946",
      "referenceItem": "707946",
      "originReference": "e-29707946",
      "updateIndicator": "6",
      "completionIndicator": "6",
      "deliveryPriority": "46",
      "plant": "7946",
      "storageLocation": "7946",
      "shippingPoint": "7946",
      "route": "707946",
      "billOfMaterialKey": "29707946",
      "billOfMaterialDate": "2013-04-20",
      "billOfMaterialNumber": "29707946",
      "billOfMaterialItem": "29707946",
      "probability": 877.59,
      "createdOn": "2023-11-09",
      "createdBy": "dBy-29707946",
      "createdTime": "22:59:53",
      "taxClassification1": "6",
      "taxClassification2": "6",
      "taxClassification3": "6",
      "taxClassification4": "6",
      "taxClassification5": "6",
      "taxClassification6": "6",
      "taxClassification7": "6",
      "taxClassification8": "6",
      "taxClassification9": "6",
      "confirmedQuantityDelivery": 369729174348.827,
      "confirmedQuantitySchedule": 923590266132.153,
      "referenceIndicator": "6",
      "netPrice": 8778053468242.23,
      "pricingUnit": 47,
      "pricingUnitOfMeasure": "946",
      "debitCreditIndicator": "6",
      "cashDiscountIndicator": true,
      "checkingGroup": "7946",
      "collectiveBillingIndicator": true,
      "priceGroup": "7946",
      "accountAssignmentGroup": "07946",
      "bonusIndicator": true,
      "commissionGroup": "07946",
      "europeanArticleNumber": "cleNumber-29707946",
      "pricingSource": "07946",
      "valuationType": "e-29707946",
      "valuationDescription": "valuationDescription-29707946",
      "batchManagementRequired": true,
      "batchCharacteristic": "29707946",
      "batchBillingVariant": "t-29707946",
      "deliveryQuantity": 415024377845.668,
      "statisticsGroup": "07946",
      "costValue": 7553631449970.15,
      "subtotal1": 3914433389271.62,
      "subtotal2": 7376985692027.65,
      "subtotal3": 7235212949117.27,
      "subtotal4": 8081820210821.09,
      "subtotal5": 9366694956742.08,
      "subtotal6": 7039710567602.5,
      "exchangeRate": 94065.71159,
      "lastChangedOn": "2008-07-30",
      "eanUpc": "eanUpc-29707946",
      "fixedQuantityIndicator": true,
      "profitCenter": "r-29707946",
      "materialGroup1": "07946",
      "materialGroup2": "07946",
      "materialGroup3": "07946",
      "materialGroup4": "07946",
      "materialGroup5": "07946",
      "componentQuantity": 669750492611.958,
      "reasonForSubstitution": "7946",
      "specialStockIndicator": "6",
      "assignmentIndicator": "6",
      "promotionGroupId": "tionGroupId-29707946",
      "promotionId": "promotionId-29707946",
      "profitabilitySegment": "t-29707946",
      "frozenProfitabilitySegment": "t-29707946",
      "orderNumber": "ber-29707946",
      "planningMaterial": "planningMaterial-29707946",
      "planningPlant": "7946",
      "baseUnitPlanning": "946",
      "referenceUnit": "946",
      "accountAssignmentCategory": "46",
      "consumptionPosting": "6",
      "serialNumberProfile": "7946",
      "objectNumber": "objectNumber-29707946"
    },
    {
      "itemNumber": "707947",
      "wbsElement": "29707947",
      "material": "material-29707947",
      "enteredMaterial": "enteredMaterial-29707947",
      "pricingReferenceMaterial": "pricingReferenceMaterial-29707947",
      "batch": "batch-29707947",
      "materialGroup": "-29707947",
      "shortText": "shortText-29707947",
      "itemCategory": "29707947",
      "itemType": "29707947",
      "processCode": "e-29707947",
      "deliveryRelevant": false,
      "billingRelevant": false,
      "higherLevelItem": "707947",
      "alternativeItem": "707947",
      "rejectionReason": "47",
      "productHierarchy": "Hierarchy-29707947",
      "universalSalesParentNode": "universalSalesParentNode-29707947",
      "universalSalesOrigin": "n-29707947",
      "universalBatchParentNode": "universalBatchParentNode-29707947",
      "universalBatchOrigin": "n-29707947",
      "targetValue": 581786631567.15,
      "targetQuantity": 113566452871.318,
      "targetUnit": "947",
      "numeratorTargetQty": 17,
      "denominatorTargetQty": 88,
      "baseUnit": "07947",
      "substitutionNumerator": 81,
      "substitutionDenominator": 63,
      "scaleQuantity": 909660005491.612,
      "roundingQuantity": 102738953054.445,
      "roundingDate": "2018-09-28",
      "roundingFactor": 451.24,
      "externalItemNumber": "r-29707947",
      "customerMaterial": "customerMaterial-29707947",
      "usageIndicator": "7947",
      "usageIndicator2": "7947",
      "salesGroup": "07947",
      "usageIndicatorSales": "947",
      "deliveryGroup": "07947",
      "fixedQuantity": 263847366775.132,
      "unlimitedOverdelivery": "y-29707947",
      "overdeliveryTolerance": 275.78,
      "underdeliveryTolerance": 339.38,
      "billingBlockItem": "47",
      "replacementPart": false,
      "billingIndex": false,
      "division": "47",
      "businessArea": "7947",
      "netValueItem": 9144476455057.1,
      "currency": {
        "code": "441"
      },
      "partialDeliveryItem": 50,
      "partialDeliveryIndicator": "7",
      "resourceId": "resourceId-29707947",
      "batchSplitAllowed": false,
      "orderQuantity": 623838305727.43,
      "requiredQuantity": 107717903551.613,
      "confirmedQuantity": 608670553593.549,
      "cumulativeQuantity": 783869760078.821,
      "salesUnit": "947",
      "numeratorConversion": 71,
      "denominatorConversion": 62,
      "grossWeight": 883874379979.879,
      "netWeight": 601189397943.07,
      "weightUnit": "947",
      "volume": 825266654523.885,
      "volumeUnit": "947",
      "originatingDocument": "t-29707947",
      "precedingItem": "707947",
      "referenceDocument": "t-29707947",
      "referenceItem": "707947",
      "originReference": "e-29707947",
      "updateIndicator": "7",
      "completionIndicator": "7",
      "deliveryPriority": "47",
      "plant": "7947",
      "storageLocation": "7947",
      "shippingPoint": "7947",
      "route": "707947",
      "billOfMaterialKey": "29707947",
      "billOfMaterialDate": "2017-01-09",
      "billOfMaterialNumber": "29707947",
      "billOfMaterialItem": "29707947",
      "probability": 711.76,
      "createdOn": "2017-02-19",
      "createdBy": "dBy-29707947",
      "createdTime": "22:59:53",
      "taxClassification1": "7",
      "taxClassification2": "7",
      "taxClassification3": "7",
      "taxClassification4": "7",
      "taxClassification5": "7",
      "taxClassification6": "7",
      "taxClassification7": "7",
      "taxClassification8": "7",
      "taxClassification9": "7",
      "confirmedQuantityDelivery": 806811408461.905,
      "confirmedQuantitySchedule": 94155409696.1,
      "referenceIndicator": "7",
      "netPrice": 1501555031015.47,
      "pricingUnit": 99,
      "pricingUnitOfMeasure": "947",
      "debitCreditIndicator": "7",
      "cashDiscountIndicator": false,
      "checkingGroup": "7947",
      "collectiveBillingIndicator": false,
      "priceGroup": "7947",
      "accountAssignmentGroup": "07947",
      "bonusIndicator": false,
      "commissionGroup": "07947",
      "europeanArticleNumber": "cleNumber-29707947",
      "pricingSource": "07947",
      "valuationType": "e-29707947",
      "valuationDescription": "valuationDescription-29707947",
      "batchManagementRequired": false,
      "batchCharacteristic": "29707947",
      "batchBillingVariant": "t-29707947",
      "deliveryQuantity": 482064335458.589,
      "statisticsGroup": "07947",
      "costValue": 5059334887818.44,
      "subtotal1": 7063131389106.25,
      "subtotal2": 7139983821534.58,
      "subtotal3": 9886943026548.53,
      "subtotal4": 2160192112355.76,
      "subtotal5": 9626130097673.55,
      "subtotal6": 5857919725253.2,
      "exchangeRate": 51095.82451,
      "lastChangedOn": "2008-05-01",
      "eanUpc": "eanUpc-29707947",
      "fixedQuantityIndicator": false,
      "profitCenter": "r-29707947",
      "materialGroup1": "07947",
      "materialGroup2": "07947",
      "materialGroup3": "07947",
      "materialGroup4": "07947",
      "materialGroup5": "07947",
      "componentQuantity": 432280243452.487,
      "reasonForSubstitution": "7947",
      "specialStockIndicator": "7",
      "assignmentIndicator": "7",
      "promotionGroupId": "tionGroupId-29707947",
      "promotionId": "promotionId-29707947",
      "profitabilitySegment": "t-29707947",
      "frozenProfitabilitySegment": "t-29707947",
      "orderNumber": "ber-29707947",
      "planningMaterial": "planningMaterial-29707947",
      "planningPlant": "7947",
      "baseUnitPlanning": "947",
      "referenceUnit": "947",
      "accountAssignmentCategory": "47",
      "consumptionPosting": "7",
      "serialNumberProfile": "7947",
      "objectNumber": "objectNumber-29707947"
    }
  ]
}


### SalesOrderHeader
# @name SalesOrderHeader_PATCH
PATCH {{server}}/odata/v4/projectsys/SalesOrderHeader(salesOrder='er-8957289',wbsElement='-8957289')
Content-Type: application/json

{
  "salesOrder": "er-8957289",
  "wbsElement": "-8957289",
  "createdOn": "2023-06-18",
  "createdTime": "22:59:53",
  "createdBy": "edBy-8957289",
  "quotationValidFrom": "2018-05-20",
  "quotationValidTo": "2013-11-20",
  "documentDate": "2009-06-29",
  "salesDocumentCategory": "9",
  "transactionGroup": "9",
  "salesDocumentType": "7289",
  "orderReason": "289",
  "warrantyDate": "2009-01-24",
  "collectiveNumber": "er-8957289",
  "deliveryBlock": "89",
  "billingBlock": "89",
  "netValue": 9278799764800.35,
  "currency": {
    "code": "441"
  },
  "salesOrganization": "7289",
  "distributionChannel": "89",
  "division": "89",
  "salesGroup": "7289",
  "salesOffice": "7289",
  "businessArea": "7289",
  "costCenter": "er-8957289",
  "validityStartDate": "2011-04-24",
  "validityEndDate": "2020-08-02",
  "pricingDocument": "nt-8957289",
  "requestedDeliveryDate": "2021-08-06",
  "deliveryDateTypeRule": "89",
  "pricingGroup": "89",
  "completeDeliveryIndicator": "9",
  "salesDocumentIndicator": "89",
  "salesDocumentIndicator2": "89",
  "pricingProcedure": "957289",
  "shippingCondition": "89",
  "billingType": "7289",
  "probability": 270.25,
  "description": "description-8957289",
  "customerPurchaseOrder": "customerPurchaseOrder-8957289",
  "purchaseOrderType": "7289",
  "purchaseOrderDate": "2018-06-17",
  "purchaseOrderTime": "22:59:53",
  "yourReference": "ourReference-8957289",
  "contactPerson": "rson-8957289",
  "telephoneNumber": "neNumber-8957289",
  "numberOfReminders": 64,
  "lastReminderDate": "2012-08-07",
  "soldToParty": "ty-8957289",
  "costCenterAccount": "nt-8957289",
  "statisticsGroup": "89",
  "documentCurrency": "57289",
  "lastChangedOn": "2016-05-01",
  "customerGroup1": "289",
  "customerGroup2": "289",
  "customerGroup3": "289",
  "customerGroup4": "289",
  "customerGroup5": "289",
  "agreementNumber": "er-8957289",
  "controllingArea": "7289",
  "exchangeRateType": "7289",
  "creditControlArea": "7289",
  "creditAccount": "nt-8957289",
  "creditGroup": "7289",
  "creditRepresentativeGroup": "289",
  "creditRiskCategory": "89",
  "creditCurrency": "57289",
  "creditReleaseDate": "2015-08-02",
  "nextCreditCheckDate": "2010-05-13",
  "creditNextReviewDate": "2011-07-27",
  "releasedCreditValue": 6771852918965.79,
  "lastCreditCheckDate": "2016-10-15",
  "hierarchyTypePricing": "89",
  "universalSalesRelevance": "9",
  "branchUuid": "branchUuid-8957289",
  "usageIndicator": "289",
  "usageIndicatorDescription": "geIndicatorDescription-8957289",
  "precedingDocument": "nt-8957289",
  "objectNumber": "objectNumber-8957289",
  "companyCode": "7289",
  "taxClassification1": "9",
  "taxClassification2": "9",
  "taxClassification3": "9",
  "taxClassification4": "9",
  "taxClassification5": "9",
  "taxClassification6": "9",
  "taxClassification7": "9",
  "taxClassification8": "9",
  "taxClassification9": "9",
  "referenceDocumentNumber": "ntNumber-8957289",
  "assignmentNumber": "mentNumber-8957289",
  "precedingDocumentCategory": "9",
  "pricingProcedureCustomer": "957289",
  "settlementGroup": "957289",
  "orderNumber": "mber-8957289",
  "qualityNotificationNumber": "mber-8957289",
  "documentGroupNumber": "er-8957289",
  "schemeGroup": "7289",
  "callOffPartner": "er-8957289",
  "releaseOrderDate": "2011-10-06",
  "releaseOrderTime": "22:59:53",
  "releaseOrderStatus": "89",
  "routeSchedule": "le-8957289",
  "deliveryTime": "22:59:53",
  "vatRegistrationNumber": "rationNumber-8957289",
  "taxDepartureCountry": "289",
  "externalGoodsReceiptIndicator": "9",
  "enqueueGroup": "89",
  "paymentAuthorizationDate": "2012-08-19",
  "fundsManagementPostingDate": "2016-06-24",
  "versionNumber": "er-8957289",
  "technicalHandle": "echnicalHandle-8957289",
  "productLine": "ne-8957289",
  "dangerousGoodsIndicator": "9",
  "crmGuid": "crmGuid-8957289",
  "updateTimestamp": "ateTimestamp-8957289",
  "measurementServiceId": "Id-8957289",
  "transportationManagementControlKey": "7289",
  "oilIndustryBusinessLocation": "on-8957289",
  "lastChangedByUser": "User-8957289",
  "handoverLocation": "on-8957289",
  "externalBusinessSystemId": "Id-8957289",
  "externalReferenceDocumentId": "externalReferenceDocumentId-8957289",
  "externalRevisionTimestamp": "ionTimestamp-8957289",
  "approvalStatus": "89",
  "approvalReason": "approvalReason-8957289",
  "rejectionReason": "rejectionReason-8957289",
  "solutionOrderId": "utionOrderId-8957289",
  "externalCommunicationSystemType": "pe-8957289",
  "retroPurchaseDocumentCreation": "9",
  "crossItemPricingDate": "2008-09-17",
  "dataAging": "-8957289",
  "overallRejectionStatus": "9",
  "confirmationStatus": "9",
  "creditStatusStaticCheck": "9",
  "creditStatusDynamicCheck": "9",
  "creditStatusPartialRelease": "9",
  "creditStatusManualRelease": "9",
  "creditStatusNextCheck": "9",
  "creditStatusCentralManagement": "9",
  "creditStatusTechnicalError": "9",
  "overallCreditStatus": "9",
  "overallProcessingStatus": "9",
  "deliveryBlockStatus": "9",
  "billingBlockStatus": "9",
  "billingStatus": "9",
  "billingStatusHeader": "9",
  "overallProcessingStatusDocument": "9",
  "deliveryBlockStatusHeader": "9",
  "deliveryStatus": "9",
  "deliveryStatusHeader": "9",
  "manualCompletionIndicator": "9",
  "billingBlockStatusHeader2": "9",
  "billingStatusItem": "9",
  "overallBlockStatus": "9",
  "transportationStatus": "9",
  "incompletionStatusHeader": "9",
  "incompletionStatusItem": "9",
  "billingIncompletionStatusHeader": "9",
  "billingIncompletionStatusItem": "9",
  "pricingIncompletionStatus": "9",
  "deliveryIncompletionStatusHeader": "9",
  "deliveryIncompletionStatusItem": "9",
  "incompletionProcedure1": "9",
  "incompletionProcedure2": "9",
  "incompletionProcedure3": "9",
  "incompletionProcedure4": "9",
  "incompletionProcedure5": "9",
  "incompletionStatusSales1": "9",
  "incompletionStatusSales2": "9",
  "incompletionStatusSales3": "9",
  "incompletionStatusSales4": "9",
  "incompletionStatusSales5": "9",
  "goodsMovementStatus": "9",
  "totalEmcStatus": "9",
  "totalSlcStatus": "9",
  "totalLcStatus": "9",
  "totalPcStatus": "9",
  "totalDangerousGoodsStatus": "9",
  "totalSafetyDataSheetStatus": "9",
  "bobProcessingStatus": "9",
  "downPaymentClearingStatusHeader": "9",
  "b2bMessageProcessingStatus": "9",
  "deliveryRelatedBillingStatusTotal": "9",
  "sdmVersion": "on-8957289",
  "dummySalesDocIncludeEew": "9",
  "cgtoShipmentId": "toShipmentId-8957289",
  "cgtoCoiId": "cgtoCoiId-8957289",
  "cgtoTreatmentOrderId": "tmentOrderId-8957289",
  "cgtoTherapyId": "gtoTherapyId-8957289",
  "cgtoTherapyIdName": "cgtoTherapyIdName-8957289",
  "cgtoTherapyType": "oTherapyType-8957289",
  "cgtoTherapyTypeName": "cgtoTherapyTypeName-8957289",
  "cgtoClinicalTrialSubjectId": "ClinicalTrialSubjectId-8957289",
  "cgtoPatientId": "gtoPatientId-8957289",
  "cgtoCityPharmacyRefNumber": "oCityPharmacyRefNumber-8957289",
  "ctcoStudyId": "ctcoStudyId-8957289",
  "ctcoProtocolId": "coProtocolId-8957289",
  "ctcoSiteId": "ctcoSiteId-8957289",
  "ctcoNoRegularCheck": "9",
  "ctcoPushEpoch": "ch-8957289",
  "globalLogReferenceHeader": "globalLogReferenceHeader-8957289",
  "dmbeDealNumber": "beDealNumber-8957289",
  "dmbeEvgIdRenewal": "EvgIdRenewal-8957289",
  "dmbeEvgIdCancel": "eEvgIdCancel-8957289",
  "zapcgkhIndicator": "or-8957289",
  "apcgkExtendHeader": "er-8957289",
  "zabdathDate": "2021-02-07",
  "ad01FareReference": "areReference-8957289",
  "ad01BaseDocument": "BaseDocument-8957289",
  "lastVoucherNumber": "oucherNumber-8957289",
  "publicSectorBudgetDate": "2014-08-09",
  "fashionCustomerGroup6": "289",
  "fashionCustomerGroup7": "289",
  "fashionCustomerGroup8": "289",
  "fashionCustomerGroup9": "289",
  "fashionCustomerGroup10": "289",
  "fashionReregistration": "9",
  "fashionCqCheck": "9",
  "fashionVersionStatus": "89",
  "fashionTransaction": "on-8957289",
  "fashionValueAddedService": "ce-8957289",
  "fashionCandidateDate": "2014-05-12",
  "fashionSeasonSegment": "7289",
  "fashionOsStgChange": "9",
  "constructionIndicator": "or-8957289",
  "millApplicationId": "Id-8957289",
  "tasIndicator": "9",
  "betcIndicator": "9",
  "modificationAllowed": "9",
  "cancellationAllowed": "9",
  "paymentMethod": "7289",
  "businessPartnerNumber": "er-8957289",
  "reportingFrequency": "7289",
  "logicalSystem": "em-8957289",
  "pricingCalculationIndicator": "9",
  "multipleIndicator": "9",
  "specialPaymentIndicator": "7289",
  "warrantyClaimHeader": "yClaimHeader-8957289",
  "vbakStatus": "89",
  "technicalFields": "technicalFields-8957289",
  "extensionIndicator": "or-8957289",
  "cgtoHeaderIndicator": "or-8957289",
  "studyDataIndicator": "or-8957289",
  "to_item": [
    {
      "itemNumber": "707946",
      "wbsElement": "29707946",
      "material": "material-29707946",
      "enteredMaterial": "enteredMaterial-29707946",
      "pricingReferenceMaterial": "pricingReferenceMaterial-29707946",
      "batch": "batch-29707946",
      "materialGroup": "-29707946",
      "shortText": "shortText-29707946",
      "itemCategory": "29707946",
      "itemType": "29707946",
      "processCode": "e-29707946",
      "deliveryRelevant": true,
      "billingRelevant": true,
      "higherLevelItem": "707946",
      "alternativeItem": "707946",
      "rejectionReason": "46",
      "productHierarchy": "Hierarchy-29707946",
      "universalSalesParentNode": "universalSalesParentNode-29707946",
      "universalSalesOrigin": "n-29707946",
      "universalBatchParentNode": "universalBatchParentNode-29707946",
      "universalBatchOrigin": "n-29707946",
      "targetValue": 868443280895.483,
      "targetQuantity": 92959585432.105,
      "targetUnit": "946",
      "numeratorTargetQty": 86,
      "denominatorTargetQty": 52,
      "baseUnit": "07946",
      "substitutionNumerator": 17,
      "substitutionDenominator": 19,
      "scaleQuantity": 779336434919.539,
      "roundingQuantity": 872301464785.819,
      "roundingDate": "2021-08-21",
      "roundingFactor": 287.31,
      "externalItemNumber": "r-29707946",
      "customerMaterial": "customerMaterial-29707946",
      "usageIndicator": "7946",
      "usageIndicator2": "7946",
      "salesGroup": "07946",
      "usageIndicatorSales": "946",
      "deliveryGroup": "07946",
      "fixedQuantity": 624259730084.71,
      "unlimitedOverdelivery": "y-29707946",
      "overdeliveryTolerance": 570.22,
      "underdeliveryTolerance": 328.57,
      "billingBlockItem": "46",
      "replacementPart": true,
      "billingIndex": true,
      "division": "46",
      "businessArea": "7946",
      "netValueItem": 2145691665283.97,
      "currency": {
        "code": "441"
      },
      "partialDeliveryItem": 23,
      "partialDeliveryIndicator": "6",
      "resourceId": "resourceId-29707946",
      "batchSplitAllowed": true,
      "orderQuantity": 884280289273.537,
      "requiredQuantity": 299636305524.633,
      "confirmedQuantity": 868369670890.077,
      "cumulativeQuantity": 184080777523.503,
      "salesUnit": "946",
      "numeratorConversion": 98,
      "denominatorConversion": 93,
      "grossWeight": 625648847485.673,
      "netWeight": 855816663190.378,
      "weightUnit": "946",
      "volume": 747811085824.938,
      "volumeUnit": "946",
      "originatingDocument": "t-29707946",
      "precedingItem": "707946",
      "referenceDocument": "t-29707946",
      "referenceItem": "707946",
      "originReference": "e-29707946",
      "updateIndicator": "6",
      "completionIndicator": "6",
      "deliveryPriority": "46",
      "plant": "7946",
      "storageLocation": "7946",
      "shippingPoint": "7946",
      "route": "707946",
      "billOfMaterialKey": "29707946",
      "billOfMaterialDate": "2013-04-20",
      "billOfMaterialNumber": "29707946",
      "billOfMaterialItem": "29707946",
      "probability": 877.59,
      "createdOn": "2023-11-09",
      "createdBy": "dBy-29707946",
      "createdTime": "22:59:53",
      "taxClassification1": "6",
      "taxClassification2": "6",
      "taxClassification3": "6",
      "taxClassification4": "6",
      "taxClassification5": "6",
      "taxClassification6": "6",
      "taxClassification7": "6",
      "taxClassification8": "6",
      "taxClassification9": "6",
      "confirmedQuantityDelivery": 369729174348.827,
      "confirmedQuantitySchedule": 923590266132.153,
      "referenceIndicator": "6",
      "netPrice": 8778053468242.23,
      "pricingUnit": 47,
      "pricingUnitOfMeasure": "946",
      "debitCreditIndicator": "6",
      "cashDiscountIndicator": true,
      "checkingGroup": "7946",
      "collectiveBillingIndicator": true,
      "priceGroup": "7946",
      "accountAssignmentGroup": "07946",
      "bonusIndicator": true,
      "commissionGroup": "07946",
      "europeanArticleNumber": "cleNumber-29707946",
      "pricingSource": "07946",
      "valuationType": "e-29707946",
      "valuationDescription": "valuationDescription-29707946",
      "batchManagementRequired": true,
      "batchCharacteristic": "29707946",
      "batchBillingVariant": "t-29707946",
      "deliveryQuantity": 415024377845.668,
      "statisticsGroup": "07946",
      "costValue": 7553631449970.15,
      "subtotal1": 3914433389271.62,
      "subtotal2": 7376985692027.65,
      "subtotal3": 7235212949117.27,
      "subtotal4": 8081820210821.09,
      "subtotal5": 9366694956742.08,
      "subtotal6": 7039710567602.5,
      "exchangeRate": 94065.71159,
      "lastChangedOn": "2008-07-30",
      "eanUpc": "eanUpc-29707946",
      "fixedQuantityIndicator": true,
      "profitCenter": "r-29707946",
      "materialGroup1": "07946",
      "materialGroup2": "07946",
      "materialGroup3": "07946",
      "materialGroup4": "07946",
      "materialGroup5": "07946",
      "componentQuantity": 669750492611.958,
      "reasonForSubstitution": "7946",
      "specialStockIndicator": "6",
      "assignmentIndicator": "6",
      "promotionGroupId": "tionGroupId-29707946",
      "promotionId": "promotionId-29707946",
      "profitabilitySegment": "t-29707946",
      "frozenProfitabilitySegment": "t-29707946",
      "orderNumber": "ber-29707946",
      "planningMaterial": "planningMaterial-29707946",
      "planningPlant": "7946",
      "baseUnitPlanning": "946",
      "referenceUnit": "946",
      "accountAssignmentCategory": "46",
      "consumptionPosting": "6",
      "serialNumberProfile": "7946",
      "objectNumber": "objectNumber-29707946"
    },
    {
      "itemNumber": "707947",
      "wbsElement": "29707947",
      "material": "material-29707947",
      "enteredMaterial": "enteredMaterial-29707947",
      "pricingReferenceMaterial": "pricingReferenceMaterial-29707947",
      "batch": "batch-29707947",
      "materialGroup": "-29707947",
      "shortText": "shortText-29707947",
      "itemCategory": "29707947",
      "itemType": "29707947",
      "processCode": "e-29707947",
      "deliveryRelevant": false,
      "billingRelevant": false,
      "higherLevelItem": "707947",
      "alternativeItem": "707947",
      "rejectionReason": "47",
      "productHierarchy": "Hierarchy-29707947",
      "universalSalesParentNode": "universalSalesParentNode-29707947",
      "universalSalesOrigin": "n-29707947",
      "universalBatchParentNode": "universalBatchParentNode-29707947",
      "universalBatchOrigin": "n-29707947",
      "targetValue": 581786631567.15,
      "targetQuantity": 113566452871.318,
      "targetUnit": "947",
      "numeratorTargetQty": 17,
      "denominatorTargetQty": 88,
      "baseUnit": "07947",
      "substitutionNumerator": 81,
      "substitutionDenominator": 63,
      "scaleQuantity": 909660005491.612,
      "roundingQuantity": 102738953054.445,
      "roundingDate": "2018-09-28",
      "roundingFactor": 451.24,
      "externalItemNumber": "r-29707947",
      "customerMaterial": "customerMaterial-29707947",
      "usageIndicator": "7947",
      "usageIndicator2": "7947",
      "salesGroup": "07947",
      "usageIndicatorSales": "947",
      "deliveryGroup": "07947",
      "fixedQuantity": 263847366775.132,
      "unlimitedOverdelivery": "y-29707947",
      "overdeliveryTolerance": 275.78,
      "underdeliveryTolerance": 339.38,
      "billingBlockItem": "47",
      "replacementPart": false,
      "billingIndex": false,
      "division": "47",
      "businessArea": "7947",
      "netValueItem": 9144476455057.1,
      "currency": {
        "code": "441"
      },
      "partialDeliveryItem": 50,
      "partialDeliveryIndicator": "7",
      "resourceId": "resourceId-29707947",
      "batchSplitAllowed": false,
      "orderQuantity": 623838305727.43,
      "requiredQuantity": 107717903551.613,
      "confirmedQuantity": 608670553593.549,
      "cumulativeQuantity": 783869760078.821,
      "salesUnit": "947",
      "numeratorConversion": 71,
      "denominatorConversion": 62,
      "grossWeight": 883874379979.879,
      "netWeight": 601189397943.07,
      "weightUnit": "947",
      "volume": 825266654523.885,
      "volumeUnit": "947",
      "originatingDocument": "t-29707947",
      "precedingItem": "707947",
      "referenceDocument": "t-29707947",
      "referenceItem": "707947",
      "originReference": "e-29707947",
      "updateIndicator": "7",
      "completionIndicator": "7",
      "deliveryPriority": "47",
      "plant": "7947",
      "storageLocation": "7947",
      "shippingPoint": "7947",
      "route": "707947",
      "billOfMaterialKey": "29707947",
      "billOfMaterialDate": "2017-01-09",
      "billOfMaterialNumber": "29707947",
      "billOfMaterialItem": "29707947",
      "probability": 711.76,
      "createdOn": "2017-02-19",
      "createdBy": "dBy-29707947",
      "createdTime": "22:59:53",
      "taxClassification1": "7",
      "taxClassification2": "7",
      "taxClassification3": "7",
      "taxClassification4": "7",
      "taxClassification5": "7",
      "taxClassification6": "7",
      "taxClassification7": "7",
      "taxClassification8": "7",
      "taxClassification9": "7",
      "confirmedQuantityDelivery": 806811408461.905,
      "confirmedQuantitySchedule": 94155409696.1,
      "referenceIndicator": "7",
      "netPrice": 1501555031015.47,
      "pricingUnit": 99,
      "pricingUnitOfMeasure": "947",
      "debitCreditIndicator": "7",
      "cashDiscountIndicator": false,
      "checkingGroup": "7947",
      "collectiveBillingIndicator": false,
      "priceGroup": "7947",
      "accountAssignmentGroup": "07947",
      "bonusIndicator": false,
      "commissionGroup": "07947",
      "europeanArticleNumber": "cleNumber-29707947",
      "pricingSource": "07947",
      "valuationType": "e-29707947",
      "valuationDescription": "valuationDescription-29707947",
      "batchManagementRequired": false,
      "batchCharacteristic": "29707947",
      "batchBillingVariant": "t-29707947",
      "deliveryQuantity": 482064335458.589,
      "statisticsGroup": "07947",
      "costValue": 5059334887818.44,
      "subtotal1": 7063131389106.25,
      "subtotal2": 7139983821534.58,
      "subtotal3": 9886943026548.53,
      "subtotal4": 2160192112355.76,
      "subtotal5": 9626130097673.55,
      "subtotal6": 5857919725253.2,
      "exchangeRate": 51095.82451,
      "lastChangedOn": "2008-05-01",
      "eanUpc": "eanUpc-29707947",
      "fixedQuantityIndicator": false,
      "profitCenter": "r-29707947",
      "materialGroup1": "07947",
      "materialGroup2": "07947",
      "materialGroup3": "07947",
      "materialGroup4": "07947",
      "materialGroup5": "07947",
      "componentQuantity": 432280243452.487,
      "reasonForSubstitution": "7947",
      "specialStockIndicator": "7",
      "assignmentIndicator": "7",
      "promotionGroupId": "tionGroupId-29707947",
      "promotionId": "promotionId-29707947",
      "profitabilitySegment": "t-29707947",
      "frozenProfitabilitySegment": "t-29707947",
      "orderNumber": "ber-29707947",
      "planningMaterial": "planningMaterial-29707947",
      "planningPlant": "7947",
      "baseUnitPlanning": "947",
      "referenceUnit": "947",
      "accountAssignmentCategory": "47",
      "consumptionPosting": "7",
      "serialNumberProfile": "7947",
      "objectNumber": "objectNumber-29707947"
    }
  ]
}


### SalesOrderHeader
# @name SalesOrderHeader_DELETE
DELETE {{server}}/odata/v4/projectsys/SalesOrderHeader(salesOrder='er-8957289',wbsElement='-8957289')
Content-Type: application/json


### SalesOrderItem
# @name SalesOrderItem_GET
GET {{server}}/odata/v4/projectsys/SalesOrderItem



### SalesOrderItem
# @name SalesOrderItem_POST
POST {{server}}/odata/v4/projectsys/SalesOrderItem
Content-Type: application/json

{
  "itemNumber": "707946",
  "wbsElement": "29707946",
  "material": "material-29707946",
  "enteredMaterial": "enteredMaterial-29707946",
  "pricingReferenceMaterial": "pricingReferenceMaterial-29707946",
  "batch": "batch-29707946",
  "materialGroup": "-29707946",
  "shortText": "shortText-29707946",
  "itemCategory": "29707946",
  "itemType": "29707946",
  "processCode": "e-29707946",
  "deliveryRelevant": true,
  "billingRelevant": true,
  "higherLevelItem": "707946",
  "alternativeItem": "707946",
  "rejectionReason": "46",
  "productHierarchy": "Hierarchy-29707946",
  "universalSalesParentNode": "universalSalesParentNode-29707946",
  "universalSalesOrigin": "n-29707946",
  "universalBatchParentNode": "universalBatchParentNode-29707946",
  "universalBatchOrigin": "n-29707946",
  "targetValue": 868443280895.483,
  "targetQuantity": 92959585432.105,
  "targetUnit": "946",
  "numeratorTargetQty": 86,
  "denominatorTargetQty": 52,
  "baseUnit": "07946",
  "substitutionNumerator": 17,
  "substitutionDenominator": 19,
  "scaleQuantity": 779336434919.539,
  "roundingQuantity": 872301464785.819,
  "roundingDate": "2021-08-21",
  "roundingFactor": 287.31,
  "externalItemNumber": "r-29707946",
  "customerMaterial": "customerMaterial-29707946",
  "usageIndicator": "7946",
  "usageIndicator2": "7946",
  "salesGroup": "07946",
  "usageIndicatorSales": "946",
  "deliveryGroup": "07946",
  "fixedQuantity": 624259730084.71,
  "unlimitedOverdelivery": "y-29707946",
  "overdeliveryTolerance": 570.22,
  "underdeliveryTolerance": 328.57,
  "billingBlockItem": "46",
  "replacementPart": true,
  "billingIndex": true,
  "division": "46",
  "businessArea": "7946",
  "netValueItem": 2145691665283.97,
  "currency": {
    "code": "441"
  },
  "partialDeliveryItem": 23,
  "partialDeliveryIndicator": "6",
  "resourceId": "resourceId-29707946",
  "batchSplitAllowed": true,
  "orderQuantity": 884280289273.537,
  "requiredQuantity": 299636305524.633,
  "confirmedQuantity": 868369670890.077,
  "cumulativeQuantity": 184080777523.503,
  "salesUnit": "946",
  "numeratorConversion": 98,
  "denominatorConversion": 93,
  "grossWeight": 625648847485.673,
  "netWeight": 855816663190.378,
  "weightUnit": "946",
  "volume": 747811085824.938,
  "volumeUnit": "946",
  "originatingDocument": "t-29707946",
  "precedingItem": "707946",
  "referenceDocument": "t-29707946",
  "referenceItem": "707946",
  "originReference": "e-29707946",
  "updateIndicator": "6",
  "completionIndicator": "6",
  "deliveryPriority": "46",
  "plant": "7946",
  "storageLocation": "7946",
  "shippingPoint": "7946",
  "route": "707946",
  "billOfMaterialKey": "29707946",
  "billOfMaterialDate": "2013-04-20",
  "billOfMaterialNumber": "29707946",
  "billOfMaterialItem": "29707946",
  "probability": 877.59,
  "createdOn": "2023-11-09",
  "createdBy": "dBy-29707946",
  "createdTime": "22:59:53",
  "taxClassification1": "6",
  "taxClassification2": "6",
  "taxClassification3": "6",
  "taxClassification4": "6",
  "taxClassification5": "6",
  "taxClassification6": "6",
  "taxClassification7": "6",
  "taxClassification8": "6",
  "taxClassification9": "6",
  "confirmedQuantityDelivery": 369729174348.827,
  "confirmedQuantitySchedule": 923590266132.153,
  "referenceIndicator": "6",
  "netPrice": 8778053468242.23,
  "pricingUnit": 47,
  "pricingUnitOfMeasure": "946",
  "debitCreditIndicator": "6",
  "cashDiscountIndicator": true,
  "checkingGroup": "7946",
  "collectiveBillingIndicator": true,
  "priceGroup": "7946",
  "accountAssignmentGroup": "07946",
  "bonusIndicator": true,
  "commissionGroup": "07946",
  "europeanArticleNumber": "cleNumber-29707946",
  "pricingSource": "07946",
  "valuationType": "e-29707946",
  "valuationDescription": "valuationDescription-29707946",
  "batchManagementRequired": true,
  "batchCharacteristic": "29707946",
  "batchBillingVariant": "t-29707946",
  "deliveryQuantity": 415024377845.668,
  "statisticsGroup": "07946",
  "costValue": 7553631449970.15,
  "subtotal1": 3914433389271.62,
  "subtotal2": 7376985692027.65,
  "subtotal3": 7235212949117.27,
  "subtotal4": 8081820210821.09,
  "subtotal5": 9366694956742.08,
  "subtotal6": 7039710567602.5,
  "exchangeRate": 94065.71159,
  "lastChangedOn": "2008-07-30",
  "eanUpc": "eanUpc-29707946",
  "fixedQuantityIndicator": true,
  "profitCenter": "r-29707946",
  "materialGroup1": "07946",
  "materialGroup2": "07946",
  "materialGroup3": "07946",
  "materialGroup4": "07946",
  "materialGroup5": "07946",
  "componentQuantity": 669750492611.958,
  "reasonForSubstitution": "7946",
  "specialStockIndicator": "6",
  "assignmentIndicator": "6",
  "promotionGroupId": "tionGroupId-29707946",
  "promotionId": "promotionId-29707946",
  "profitabilitySegment": "t-29707946",
  "frozenProfitabilitySegment": "t-29707946",
  "orderNumber": "ber-29707946",
  "planningMaterial": "planningMaterial-29707946",
  "planningPlant": "7946",
  "baseUnitPlanning": "946",
  "referenceUnit": "946",
  "accountAssignmentCategory": "46",
  "consumptionPosting": "6",
  "serialNumberProfile": "7946",
  "objectNumber": "objectNumber-29707946"
}


### SalesOrderItem
# @name SalesOrderItem_PATCH
PATCH {{server}}/odata/v4/projectsys/SalesOrderItem(salesOrder='er-8957289',itemNumber='707946',wbsElement='29707946')
Content-Type: application/json

{
  "itemNumber": "707946",
  "wbsElement": "29707946",
  "material": "material-29707946",
  "enteredMaterial": "enteredMaterial-29707946",
  "pricingReferenceMaterial": "pricingReferenceMaterial-29707946",
  "batch": "batch-29707946",
  "materialGroup": "-29707946",
  "shortText": "shortText-29707946",
  "itemCategory": "29707946",
  "itemType": "29707946",
  "processCode": "e-29707946",
  "deliveryRelevant": true,
  "billingRelevant": true,
  "higherLevelItem": "707946",
  "alternativeItem": "707946",
  "rejectionReason": "46",
  "productHierarchy": "Hierarchy-29707946",
  "universalSalesParentNode": "universalSalesParentNode-29707946",
  "universalSalesOrigin": "n-29707946",
  "universalBatchParentNode": "universalBatchParentNode-29707946",
  "universalBatchOrigin": "n-29707946",
  "targetValue": 868443280895.483,
  "targetQuantity": 92959585432.105,
  "targetUnit": "946",
  "numeratorTargetQty": 86,
  "denominatorTargetQty": 52,
  "baseUnit": "07946",
  "substitutionNumerator": 17,
  "substitutionDenominator": 19,
  "scaleQuantity": 779336434919.539,
  "roundingQuantity": 872301464785.819,
  "roundingDate": "2021-08-21",
  "roundingFactor": 287.31,
  "externalItemNumber": "r-29707946",
  "customerMaterial": "customerMaterial-29707946",
  "usageIndicator": "7946",
  "usageIndicator2": "7946",
  "salesGroup": "07946",
  "usageIndicatorSales": "946",
  "deliveryGroup": "07946",
  "fixedQuantity": 624259730084.71,
  "unlimitedOverdelivery": "y-29707946",
  "overdeliveryTolerance": 570.22,
  "underdeliveryTolerance": 328.57,
  "billingBlockItem": "46",
  "replacementPart": true,
  "billingIndex": true,
  "division": "46",
  "businessArea": "7946",
  "netValueItem": 2145691665283.97,
  "currency": {
    "code": "441"
  },
  "partialDeliveryItem": 23,
  "partialDeliveryIndicator": "6",
  "resourceId": "resourceId-29707946",
  "batchSplitAllowed": true,
  "orderQuantity": 884280289273.537,
  "requiredQuantity": 299636305524.633,
  "confirmedQuantity": 868369670890.077,
  "cumulativeQuantity": 184080777523.503,
  "salesUnit": "946",
  "numeratorConversion": 98,
  "denominatorConversion": 93,
  "grossWeight": 625648847485.673,
  "netWeight": 855816663190.378,
  "weightUnit": "946",
  "volume": 747811085824.938,
  "volumeUnit": "946",
  "originatingDocument": "t-29707946",
  "precedingItem": "707946",
  "referenceDocument": "t-29707946",
  "referenceItem": "707946",
  "originReference": "e-29707946",
  "updateIndicator": "6",
  "completionIndicator": "6",
  "deliveryPriority": "46",
  "plant": "7946",
  "storageLocation": "7946",
  "shippingPoint": "7946",
  "route": "707946",
  "billOfMaterialKey": "29707946",
  "billOfMaterialDate": "2013-04-20",
  "billOfMaterialNumber": "29707946",
  "billOfMaterialItem": "29707946",
  "probability": 877.59,
  "createdOn": "2023-11-09",
  "createdBy": "dBy-29707946",
  "createdTime": "22:59:53",
  "taxClassification1": "6",
  "taxClassification2": "6",
  "taxClassification3": "6",
  "taxClassification4": "6",
  "taxClassification5": "6",
  "taxClassification6": "6",
  "taxClassification7": "6",
  "taxClassification8": "6",
  "taxClassification9": "6",
  "confirmedQuantityDelivery": 369729174348.827,
  "confirmedQuantitySchedule": 923590266132.153,
  "referenceIndicator": "6",
  "netPrice": 8778053468242.23,
  "pricingUnit": 47,
  "pricingUnitOfMeasure": "946",
  "debitCreditIndicator": "6",
  "cashDiscountIndicator": true,
  "checkingGroup": "7946",
  "collectiveBillingIndicator": true,
  "priceGroup": "7946",
  "accountAssignmentGroup": "07946",
  "bonusIndicator": true,
  "commissionGroup": "07946",
  "europeanArticleNumber": "cleNumber-29707946",
  "pricingSource": "07946",
  "valuationType": "e-29707946",
  "valuationDescription": "valuationDescription-29707946",
  "batchManagementRequired": true,
  "batchCharacteristic": "29707946",
  "batchBillingVariant": "t-29707946",
  "deliveryQuantity": 415024377845.668,
  "statisticsGroup": "07946",
  "costValue": 7553631449970.15,
  "subtotal1": 3914433389271.62,
  "subtotal2": 7376985692027.65,
  "subtotal3": 7235212949117.27,
  "subtotal4": 8081820210821.09,
  "subtotal5": 9366694956742.08,
  "subtotal6": 7039710567602.5,
  "exchangeRate": 94065.71159,
  "lastChangedOn": "2008-07-30",
  "eanUpc": "eanUpc-29707946",
  "fixedQuantityIndicator": true,
  "profitCenter": "r-29707946",
  "materialGroup1": "07946",
  "materialGroup2": "07946",
  "materialGroup3": "07946",
  "materialGroup4": "07946",
  "materialGroup5": "07946",
  "componentQuantity": 669750492611.958,
  "reasonForSubstitution": "7946",
  "specialStockIndicator": "6",
  "assignmentIndicator": "6",
  "promotionGroupId": "tionGroupId-29707946",
  "promotionId": "promotionId-29707946",
  "profitabilitySegment": "t-29707946",
  "frozenProfitabilitySegment": "t-29707946",
  "orderNumber": "ber-29707946",
  "planningMaterial": "planningMaterial-29707946",
  "planningPlant": "7946",
  "baseUnitPlanning": "946",
  "referenceUnit": "946",
  "accountAssignmentCategory": "46",
  "consumptionPosting": "6",
  "serialNumberProfile": "7946",
  "objectNumber": "objectNumber-29707946"
}


### SalesOrderItem
# @name SalesOrderItem_DELETE
DELETE {{server}}/odata/v4/projectsys/SalesOrderItem(salesOrder='er-8957289',itemNumber='707946',wbsElement='29707946')
Content-Type: application/json


### PurchaseDocumentHeader
# @name PurchaseDocumentHeader_GET
GET {{server}}/odata/v4/projectsys/PurchaseDocumentHeader



### PurchaseDocumentHeader
# @name PurchaseDocumentHeader_POST
POST {{server}}/odata/v4/projectsys/PurchaseDocumentHeader
Content-Type: application/json

{
  "EBELN": "er-8905257",
  "PSPNR": "-8905257",
  "BUKRS": "5257",
  "BSTYP": "7",
  "BSART": "5257",
  "BSAKZ": "7",
  "LOEKZ": "7",
  "STATU": "7",
  "AEDAT": "2021-11-26",
  "ERNAM": "RNAM-8905257",
  "PINCR": "05257",
  "LPONR": "05257",
  "LIFNR": "NR-8905257",
  "SPRAS": "7",
  "ZTERM": "5257",
  "ZBD1T": 468,
  "ZBD2T": 953,
  "ZBD3T": 638,
  "ZBD1P": 9.673,
  "ZBD2P": 82.512,
  "EKORG": "5257",
  "EKGRP": "257",
  "WAERS": "05257",
  "WKURS": 2097.66035,
  "KUFIX": "7",
  "BEDAT": "2013-12-26",
  "KDATB": "2009-12-01",
  "KDATE": "2006-05-11",
  "BWBDT": "2004-06-09",
  "ANGDT": "2019-07-09",
  "BNDDT": "2004-10-25",
  "GWLDT": "2023-05-08",
  "AUSNR": "NR-8905257",
  "ANGNR": "NR-8905257",
  "IHRAN": "2006-06-13",
  "IHREZ": "HREZ-8905257",
  "VERKF": "VERKF-8905257",
  "TELF1": "TELF1-8905257",
  "LLIEF": "EF-8905257",
  "KUNNR": "NR-8905257",
  "KONNR": "NR-8905257",
  "ABGRU": "57",
  "AUTLF": "7",
  "WEAKT": "7",
  "RESWK": "5257",
  "LBLIF": "IF-8905257",
  "INCO1": "257",
  "INCO2": "INCO2-8905257",
  "KTWRT": 2299077102372.99,
  "SUBMI": "MI-8905257",
  "KNUMV": "MV-8905257",
  "KALSM": "905257",
  "STAFO": "905257",
  "LIFRE": "RE-8905257",
  "EXNUM": "UM-8905257",
  "UNSEZ": "NSEZ-8905257",
  "LOGSY": "SY-8905257",
  "UPINC": "05257",
  "STAKO": "7",
  "FRGGR": "57",
  "FRGSX": "57",
  "FRGKE": "7",
  "FRGZU": "-8905257",
  "FRGRL": "7",
  "to_PurchaseOrderItems": [
    {
      "EBELN": "m-17833220",
      "PSPNR": "17833220",
      "EBELP": "33220",
      "UNIQUEID": "IQUEID-17833220",
      "LOEKZ": "0",
      "STATU": "0",
      "AEDAT": "2018-07-19",
      "TXZ01": "TXZ01-17833220",
      "MATNR": "MATNR-17833220",
      "EMATN": "EMATN-17833220",
      "BUKRS": "3220",
      "WERKS": "3220",
      "LGORT": "3220",
      "BEDNR": "R-17833220",
      "MATKL": "-17833220",
      "INFNR": "R-17833220",
      "IDNLF": "IDNLF-17833220",
      "KTMNG": 805598086.73,
      "MENGE": 3928810156.909,
      "MEINS": "220",
      "BPRME": "220",
      "BPUMZ": 5,
      "BPUMN": 49,
      "UMREZ": 72,
      "UMREN": 38,
      "NETPR": 369034930.69,
      "PEINH": 59,
      "NETWR": 82481624563.9,
      "BRTWR": 79757906482.11,
      "AGDAT": "2007-07-27",
      "WEBAZ": 61,
      "MWSKZ": "20",
      "TXDAT_FROM": "2019-07-09",
      "TXDAT": "2014-03-04",
      "TAX_COUNTRY": "220",
      "BONUS": "20",
      "INSMK": "0",
      "SPINF": "0",
      "PRSDR": "0",
      "SCHPR": "0",
      "MAHNZ": 95,
      "MAHN1": 6,
      "MAHN2": 90,
      "MAHN3": 15,
      "UEBTO": 95.3,
      "UEBTK": "0",
      "UNTTO": 6.5,
      "BWTAR": "R-17833220",
      "BWTTY": "0",
      "ABSKZ": "0",
      "AGMEM": "220",
      "ELIKZ": "0",
      "EREKZ": "0",
      "PSTYP": "0",
      "KNTTP": "0",
      "KZVBR": "0",
      "VRTKZ": "0",
      "TWRKZ": "0",
      "WEPOS": "0",
      "WEUNB": "0",
      "REPOS": "0",
      "WEBRE": "0",
      "KZABS": "0",
      "LABNR": "LABNR-17833220",
      "KONNR": "R-17833220",
      "KTPNR": 88534,
      "ABDAT": "2014-07-08",
      "ABFTZ": 3958074775.05,
      "ETFZ1": 706,
      "ETFZ2": 79,
      "KZSTU": "0",
      "NOTKZ": "0",
      "LMEIN": "220",
      "EVERS": "20",
      "ZWERT": 30212173678.07,
      "NAVNW": 45327162009.07,
      "ABMNG": 6637765954.52,
      "PRDAT": "2009-05-14",
      "BSTYP": "0",
      "EFFWR": 58391030694.54,
      "XOBLR": "0",
      "KUNNR": "R-17833220",
      "ADRNR": "R-17833220",
      "EKKOL": "3220",
      "SKTOF": "0",
      "STAFO": "833220",
      "PLIFZ": 108,
      "NTGEW": 7691636204.557,
      "GEWEI": "220"
    },
    {
      "EBELN": "m-17833221",
      "PSPNR": "17833221",
      "EBELP": "33221",
      "UNIQUEID": "IQUEID-17833221",
      "LOEKZ": "1",
      "STATU": "1",
      "AEDAT": "2005-10-12",
      "TXZ01": "TXZ01-17833221",
      "MATNR": "MATNR-17833221",
      "EMATN": "EMATN-17833221",
      "BUKRS": "3221",
      "WERKS": "3221",
      "LGORT": "3221",
      "BEDNR": "R-17833221",
      "MATKL": "-17833221",
      "INFNR": "R-17833221",
      "IDNLF": "IDNLF-17833221",
      "KTMNG": 3493736005.975,
      "MENGE": 7661854521.873,
      "MEINS": "221",
      "BPRME": "221",
      "BPUMZ": 94,
      "BPUMN": 35,
      "UMREZ": 41,
      "UMREN": 83,
      "NETPR": 649624969.37,
      "PEINH": 10,
      "NETWR": 53907127147.16,
      "BRTWR": 2920768822.39,
      "AGDAT": "2016-07-22",
      "WEBAZ": 33,
      "MWSKZ": "21",
      "TXDAT_FROM": "2013-11-03",
      "TXDAT": "2017-10-02",
      "TAX_COUNTRY": "221",
      "BONUS": "21",
      "INSMK": "1",
      "SPINF": "1",
      "PRSDR": "1",
      "SCHPR": "1",
      "MAHNZ": 99,
      "MAHN1": 37,
      "MAHN2": 70,
      "MAHN3": 100,
      "UEBTO": 80.3,
      "UEBTK": "1",
      "UNTTO": 32.5,
      "BWTAR": "R-17833221",
      "BWTTY": "1",
      "ABSKZ": "1",
      "AGMEM": "221",
      "ELIKZ": "1",
      "EREKZ": "1",
      "PSTYP": "1",
      "KNTTP": "1",
      "KZVBR": "1",
      "VRTKZ": "1",
      "TWRKZ": "1",
      "WEPOS": "1",
      "WEUNB": "1",
      "REPOS": "1",
      "WEBRE": "1",
      "KZABS": "1",
      "LABNR": "LABNR-17833221",
      "KONNR": "R-17833221",
      "KTPNR": 44968,
      "ABDAT": "2018-03-04",
      "ABFTZ": 5475190501.852,
      "ETFZ1": 967,
      "ETFZ2": 482,
      "KZSTU": "1",
      "NOTKZ": "1",
      "LMEIN": "221",
      "EVERS": "21",
      "ZWERT": 92068747023.66,
      "NAVNW": 16512322736.55,
      "ABMNG": 3660811518.168,
      "PRDAT": "2016-07-16",
      "BSTYP": "1",
      "EFFWR": 71072656064.48,
      "XOBLR": "1",
      "KUNNR": "R-17833221",
      "ADRNR": "R-17833221",
      "EKKOL": "3221",
      "SKTOF": "1",
      "STAFO": "833221",
      "PLIFZ": 573,
      "NTGEW": 3828384269.861,
      "GEWEI": "221"
    }
  ]
}


### PurchaseDocumentHeader
# @name PurchaseDocumentHeader_PATCH
PATCH {{server}}/odata/v4/projectsys/PurchaseDocumentHeader(EBELN='er-8905257',PSPNR='-8905257')
Content-Type: application/json

{
  "EBELN": "er-8905257",
  "PSPNR": "-8905257",
  "BUKRS": "5257",
  "BSTYP": "7",
  "BSART": "5257",
  "BSAKZ": "7",
  "LOEKZ": "7",
  "STATU": "7",
  "AEDAT": "2021-11-26",
  "ERNAM": "RNAM-8905257",
  "PINCR": "05257",
  "LPONR": "05257",
  "LIFNR": "NR-8905257",
  "SPRAS": "7",
  "ZTERM": "5257",
  "ZBD1T": 468,
  "ZBD2T": 953,
  "ZBD3T": 638,
  "ZBD1P": 9.673,
  "ZBD2P": 82.512,
  "EKORG": "5257",
  "EKGRP": "257",
  "WAERS": "05257",
  "WKURS": 2097.66035,
  "KUFIX": "7",
  "BEDAT": "2013-12-26",
  "KDATB": "2009-12-01",
  "KDATE": "2006-05-11",
  "BWBDT": "2004-06-09",
  "ANGDT": "2019-07-09",
  "BNDDT": "2004-10-25",
  "GWLDT": "2023-05-08",
  "AUSNR": "NR-8905257",
  "ANGNR": "NR-8905257",
  "IHRAN": "2006-06-13",
  "IHREZ": "HREZ-8905257",
  "VERKF": "VERKF-8905257",
  "TELF1": "TELF1-8905257",
  "LLIEF": "EF-8905257",
  "KUNNR": "NR-8905257",
  "KONNR": "NR-8905257",
  "ABGRU": "57",
  "AUTLF": "7",
  "WEAKT": "7",
  "RESWK": "5257",
  "LBLIF": "IF-8905257",
  "INCO1": "257",
  "INCO2": "INCO2-8905257",
  "KTWRT": 2299077102372.99,
  "SUBMI": "MI-8905257",
  "KNUMV": "MV-8905257",
  "KALSM": "905257",
  "STAFO": "905257",
  "LIFRE": "RE-8905257",
  "EXNUM": "UM-8905257",
  "UNSEZ": "NSEZ-8905257",
  "LOGSY": "SY-8905257",
  "UPINC": "05257",
  "STAKO": "7",
  "FRGGR": "57",
  "FRGSX": "57",
  "FRGKE": "7",
  "FRGZU": "-8905257",
  "FRGRL": "7",
  "to_PurchaseOrderItems": [
    {
      "EBELN": "m-17833220",
      "PSPNR": "17833220",
      "EBELP": "33220",
      "UNIQUEID": "IQUEID-17833220",
      "LOEKZ": "0",
      "STATU": "0",
      "AEDAT": "2018-07-19",
      "TXZ01": "TXZ01-17833220",
      "MATNR": "MATNR-17833220",
      "EMATN": "EMATN-17833220",
      "BUKRS": "3220",
      "WERKS": "3220",
      "LGORT": "3220",
      "BEDNR": "R-17833220",
      "MATKL": "-17833220",
      "INFNR": "R-17833220",
      "IDNLF": "IDNLF-17833220",
      "KTMNG": 805598086.73,
      "MENGE": 3928810156.909,
      "MEINS": "220",
      "BPRME": "220",
      "BPUMZ": 5,
      "BPUMN": 49,
      "UMREZ": 72,
      "UMREN": 38,
      "NETPR": 369034930.69,
      "PEINH": 59,
      "NETWR": 82481624563.9,
      "BRTWR": 79757906482.11,
      "AGDAT": "2007-07-27",
      "WEBAZ": 61,
      "MWSKZ": "20",
      "TXDAT_FROM": "2019-07-09",
      "TXDAT": "2014-03-04",
      "TAX_COUNTRY": "220",
      "BONUS": "20",
      "INSMK": "0",
      "SPINF": "0",
      "PRSDR": "0",
      "SCHPR": "0",
      "MAHNZ": 95,
      "MAHN1": 6,
      "MAHN2": 90,
      "MAHN3": 15,
      "UEBTO": 95.3,
      "UEBTK": "0",
      "UNTTO": 6.5,
      "BWTAR": "R-17833220",
      "BWTTY": "0",
      "ABSKZ": "0",
      "AGMEM": "220",
      "ELIKZ": "0",
      "EREKZ": "0",
      "PSTYP": "0",
      "KNTTP": "0",
      "KZVBR": "0",
      "VRTKZ": "0",
      "TWRKZ": "0",
      "WEPOS": "0",
      "WEUNB": "0",
      "REPOS": "0",
      "WEBRE": "0",
      "KZABS": "0",
      "LABNR": "LABNR-17833220",
      "KONNR": "R-17833220",
      "KTPNR": 88534,
      "ABDAT": "2014-07-08",
      "ABFTZ": 3958074775.05,
      "ETFZ1": 706,
      "ETFZ2": 79,
      "KZSTU": "0",
      "NOTKZ": "0",
      "LMEIN": "220",
      "EVERS": "20",
      "ZWERT": 30212173678.07,
      "NAVNW": 45327162009.07,
      "ABMNG": 6637765954.52,
      "PRDAT": "2009-05-14",
      "BSTYP": "0",
      "EFFWR": 58391030694.54,
      "XOBLR": "0",
      "KUNNR": "R-17833220",
      "ADRNR": "R-17833220",
      "EKKOL": "3220",
      "SKTOF": "0",
      "STAFO": "833220",
      "PLIFZ": 108,
      "NTGEW": 7691636204.557,
      "GEWEI": "220"
    },
    {
      "EBELN": "m-17833221",
      "PSPNR": "17833221",
      "EBELP": "33221",
      "UNIQUEID": "IQUEID-17833221",
      "LOEKZ": "1",
      "STATU": "1",
      "AEDAT": "2005-10-12",
      "TXZ01": "TXZ01-17833221",
      "MATNR": "MATNR-17833221",
      "EMATN": "EMATN-17833221",
      "BUKRS": "3221",
      "WERKS": "3221",
      "LGORT": "3221",
      "BEDNR": "R-17833221",
      "MATKL": "-17833221",
      "INFNR": "R-17833221",
      "IDNLF": "IDNLF-17833221",
      "KTMNG": 3493736005.975,
      "MENGE": 7661854521.873,
      "MEINS": "221",
      "BPRME": "221",
      "BPUMZ": 94,
      "BPUMN": 35,
      "UMREZ": 41,
      "UMREN": 83,
      "NETPR": 649624969.37,
      "PEINH": 10,
      "NETWR": 53907127147.16,
      "BRTWR": 2920768822.39,
      "AGDAT": "2016-07-22",
      "WEBAZ": 33,
      "MWSKZ": "21",
      "TXDAT_FROM": "2013-11-03",
      "TXDAT": "2017-10-02",
      "TAX_COUNTRY": "221",
      "BONUS": "21",
      "INSMK": "1",
      "SPINF": "1",
      "PRSDR": "1",
      "SCHPR": "1",
      "MAHNZ": 99,
      "MAHN1": 37,
      "MAHN2": 70,
      "MAHN3": 100,
      "UEBTO": 80.3,
      "UEBTK": "1",
      "UNTTO": 32.5,
      "BWTAR": "R-17833221",
      "BWTTY": "1",
      "ABSKZ": "1",
      "AGMEM": "221",
      "ELIKZ": "1",
      "EREKZ": "1",
      "PSTYP": "1",
      "KNTTP": "1",
      "KZVBR": "1",
      "VRTKZ": "1",
      "TWRKZ": "1",
      "WEPOS": "1",
      "WEUNB": "1",
      "REPOS": "1",
      "WEBRE": "1",
      "KZABS": "1",
      "LABNR": "LABNR-17833221",
      "KONNR": "R-17833221",
      "KTPNR": 44968,
      "ABDAT": "2018-03-04",
      "ABFTZ": 5475190501.852,
      "ETFZ1": 967,
      "ETFZ2": 482,
      "KZSTU": "1",
      "NOTKZ": "1",
      "LMEIN": "221",
      "EVERS": "21",
      "ZWERT": 92068747023.66,
      "NAVNW": 16512322736.55,
      "ABMNG": 3660811518.168,
      "PRDAT": "2016-07-16",
      "BSTYP": "1",
      "EFFWR": 71072656064.48,
      "XOBLR": "1",
      "KUNNR": "R-17833221",
      "ADRNR": "R-17833221",
      "EKKOL": "3221",
      "SKTOF": "1",
      "STAFO": "833221",
      "PLIFZ": 573,
      "NTGEW": 3828384269.861,
      "GEWEI": "221"
    }
  ]
}


### PurchaseDocumentHeader
# @name PurchaseDocumentHeader_DELETE
DELETE {{server}}/odata/v4/projectsys/PurchaseDocumentHeader(EBELN='er-8905257',PSPNR='-8905257')
Content-Type: application/json


### PurchaseOrderItem
# @name PurchaseOrderItem_GET
GET {{server}}/odata/v4/projectsys/PurchaseOrderItem



### PurchaseOrderItem
# @name PurchaseOrderItem_POST
POST {{server}}/odata/v4/projectsys/PurchaseOrderItem
Content-Type: application/json

{
  "EBELN": "m-17833220",
  "PSPNR": "17833220",
  "EBELP": "33220",
  "UNIQUEID": "IQUEID-17833220",
  "LOEKZ": "0",
  "STATU": "0",
  "AEDAT": "2018-07-19",
  "TXZ01": "TXZ01-17833220",
  "MATNR": "MATNR-17833220",
  "EMATN": "EMATN-17833220",
  "BUKRS": "3220",
  "WERKS": "3220",
  "LGORT": "3220",
  "BEDNR": "R-17833220",
  "MATKL": "-17833220",
  "INFNR": "R-17833220",
  "IDNLF": "IDNLF-17833220",
  "KTMNG": 805598086.73,
  "MENGE": 3928810156.909,
  "MEINS": "220",
  "BPRME": "220",
  "BPUMZ": 5,
  "BPUMN": 49,
  "UMREZ": 72,
  "UMREN": 38,
  "NETPR": 369034930.69,
  "PEINH": 59,
  "NETWR": 82481624563.9,
  "BRTWR": 79757906482.11,
  "AGDAT": "2007-07-27",
  "WEBAZ": 61,
  "MWSKZ": "20",
  "TXDAT_FROM": "2019-07-09",
  "TXDAT": "2014-03-04",
  "TAX_COUNTRY": "220",
  "BONUS": "20",
  "INSMK": "0",
  "SPINF": "0",
  "PRSDR": "0",
  "SCHPR": "0",
  "MAHNZ": 95,
  "MAHN1": 6,
  "MAHN2": 90,
  "MAHN3": 15,
  "UEBTO": 95.3,
  "UEBTK": "0",
  "UNTTO": 6.5,
  "BWTAR": "R-17833220",
  "BWTTY": "0",
  "ABSKZ": "0",
  "AGMEM": "220",
  "ELIKZ": "0",
  "EREKZ": "0",
  "PSTYP": "0",
  "KNTTP": "0",
  "KZVBR": "0",
  "VRTKZ": "0",
  "TWRKZ": "0",
  "WEPOS": "0",
  "WEUNB": "0",
  "REPOS": "0",
  "WEBRE": "0",
  "KZABS": "0",
  "LABNR": "LABNR-17833220",
  "KONNR": "R-17833220",
  "KTPNR": 88534,
  "ABDAT": "2014-07-08",
  "ABFTZ": 3958074775.05,
  "ETFZ1": 706,
  "ETFZ2": 79,
  "KZSTU": "0",
  "NOTKZ": "0",
  "LMEIN": "220",
  "EVERS": "20",
  "ZWERT": 30212173678.07,
  "NAVNW": 45327162009.07,
  "ABMNG": 6637765954.52,
  "PRDAT": "2009-05-14",
  "BSTYP": "0",
  "EFFWR": 58391030694.54,
  "XOBLR": "0",
  "KUNNR": "R-17833220",
  "ADRNR": "R-17833220",
  "EKKOL": "3220",
  "SKTOF": "0",
  "STAFO": "833220",
  "PLIFZ": 108,
  "NTGEW": 7691636204.557,
  "GEWEI": "220"
}


### PurchaseOrderItem
# @name PurchaseOrderItem_PATCH
PATCH {{server}}/odata/v4/projectsys/PurchaseOrderItem(EBELN='m-17833220',PSPNR='17833220',EBELP='33220')
Content-Type: application/json

{
  "EBELN": "m-17833220",
  "PSPNR": "17833220",
  "EBELP": "33220",
  "UNIQUEID": "IQUEID-17833220",
  "LOEKZ": "0",
  "STATU": "0",
  "AEDAT": "2018-07-19",
  "TXZ01": "TXZ01-17833220",
  "MATNR": "MATNR-17833220",
  "EMATN": "EMATN-17833220",
  "BUKRS": "3220",
  "WERKS": "3220",
  "LGORT": "3220",
  "BEDNR": "R-17833220",
  "MATKL": "-17833220",
  "INFNR": "R-17833220",
  "IDNLF": "IDNLF-17833220",
  "KTMNG": 805598086.73,
  "MENGE": 3928810156.909,
  "MEINS": "220",
  "BPRME": "220",
  "BPUMZ": 5,
  "BPUMN": 49,
  "UMREZ": 72,
  "UMREN": 38,
  "NETPR": 369034930.69,
  "PEINH": 59,
  "NETWR": 82481624563.9,
  "BRTWR": 79757906482.11,
  "AGDAT": "2007-07-27",
  "WEBAZ": 61,
  "MWSKZ": "20",
  "TXDAT_FROM": "2019-07-09",
  "TXDAT": "2014-03-04",
  "TAX_COUNTRY": "220",
  "BONUS": "20",
  "INSMK": "0",
  "SPINF": "0",
  "PRSDR": "0",
  "SCHPR": "0",
  "MAHNZ": 95,
  "MAHN1": 6,
  "MAHN2": 90,
  "MAHN3": 15,
  "UEBTO": 95.3,
  "UEBTK": "0",
  "UNTTO": 6.5,
  "BWTAR": "R-17833220",
  "BWTTY": "0",
  "ABSKZ": "0",
  "AGMEM": "220",
  "ELIKZ": "0",
  "EREKZ": "0",
  "PSTYP": "0",
  "KNTTP": "0",
  "KZVBR": "0",
  "VRTKZ": "0",
  "TWRKZ": "0",
  "WEPOS": "0",
  "WEUNB": "0",
  "REPOS": "0",
  "WEBRE": "0",
  "KZABS": "0",
  "LABNR": "LABNR-17833220",
  "KONNR": "R-17833220",
  "KTPNR": 88534,
  "ABDAT": "2014-07-08",
  "ABFTZ": 3958074775.05,
  "ETFZ1": 706,
  "ETFZ2": 79,
  "KZSTU": "0",
  "NOTKZ": "0",
  "LMEIN": "220",
  "EVERS": "20",
  "ZWERT": 30212173678.07,
  "NAVNW": 45327162009.07,
  "ABMNG": 6637765954.52,
  "PRDAT": "2009-05-14",
  "BSTYP": "0",
  "EFFWR": 58391030694.54,
  "XOBLR": "0",
  "KUNNR": "R-17833220",
  "ADRNR": "R-17833220",
  "EKKOL": "3220",
  "SKTOF": "0",
  "STAFO": "833220",
  "PLIFZ": 108,
  "NTGEW": 7691636204.557,
  "GEWEI": "220"
}


### PurchaseOrderItem
# @name PurchaseOrderItem_DELETE
DELETE {{server}}/odata/v4/projectsys/PurchaseOrderItem(EBELN='m-17833220',PSPNR='17833220',EBELP='33220')
Content-Type: application/json


### UpsertSalesContract
# @name UpsertSalesContract_POST
POST {{server}}/odata/v4/projectsys/UpsertSalesContractData
Content-Type: application/json

{}

### UpsertSalesContractItem
# @name UpsertSalesContract_POST
POST {{server}}/odata/v4/projectsys/UpsertSalesContractItem
Content-Type: application/json

{}
