@server=http://localhost:4004



# @name UpsertPROJ_POST
POST {{server}}/odata/v4/projectsys/UpsertPROJ
Content-Type: application/json

{}
### UpsertWBS
# @name UpsertWBS_POST
POST {{server}}/odata/v4/projectsys/UpsertWBS
Content-Type: application/json

{}

### UpsertSalesContractData
# @name UpsertSalesContractData_POST
POST {{server}}/odata/v4/projectsys/UpsertSalesContractData
Content-Type: application/json

{}


### LoadPOData
# @name LoadPOData_POST
POST {{server}}/odata/v4/projectsys/LoadPOData
Content-Type: application/json

{}
