namespace ust.buysell.masterdata.purchase;

using ust.buysell.masterdata.projectsys as pj from './projectsys';

/*
Open Questions:
can two purchase order be same of different wbs elements
do we need the client field in the two table
*/
entity PurchaseDocumentHeader {
        // key MANDT                 : String(3)                     @title: 'Client';
    key EBELN                 : String(10)                    @title: 'Purchasing Document Number';
        //to be discussed (can two purchase order of different wbs elements can have same purchase order number);
        PSPNR                 : Association to pj.WBSElements @title: 'Key of WBSElemnt';
        BUKRS                 : String(4)                     @title: 'Company Code';
        BSTYP                 : String(1)                     @title: 'Purchasing Document Category';
        BSART                 : String(4)                     @title: 'Purchasing Document Type';
        BSAKZ                 : String(1)                     @title: 'Control Indicator for Purchasing Document Type';
        LOEKZ                 : String(1)                     @title: 'Deletion Indicator in Purchasing Document';
        STATU                 : String(1)                     @title: 'Status of Purchasing Document';
        AEDAT                 : Date                          @title: 'Date on Which Record Was Created';
        ERNAM                 : String(12)                    @title: 'Name of Person who Created the Object';
        PINCR                 : String(5)                     @title: 'Item Number Interval';
        LPONR                 : String(5)                     @title: 'Last Item Number';
        LIFNR                 : String(10)                    @title: 'Vendor Account Number';
        SPRAS                 : String(1)                     @title: 'Language Key';
        ZTERM                 : String(4)                     @title: 'Terms of Payment Key';
        ZBD1T                 : Decimal(3, 0)                 @title: 'Cash (Prompt Payment) Discount Days 1';
        ZBD2T                 : Decimal(3, 0)                 @title: 'Cash (Prompt Payment) Discount Days 2';
        ZBD3T                 : Decimal(3, 0)                 @title: 'Cash (Prompt Payment) Discount Days 3';
        ZBD1P                 : Decimal(5, 3)                 @title: 'Cash Discount Percentage 1';
        ZBD2P                 : Decimal(5, 3)                 @title: 'Cash Discount Percentage 2';
        EKORG                 : String(4)                     @title: 'Purchasing Organization';
        EKGRP                 : String(3)                     @title: 'Purchasing Group';
        WAERS                 : String(5)                     @title: 'Currency Key';
        WKURS                 : Decimal(9, 5)                 @title: 'Exchange Rate';
        KUFIX                 : String(1)                     @title: 'Indicator: Fixing of Exchange Rate';
        BEDAT                 : Date                          @title: 'Purchasing Document Date';
        KDATB                 : Date                          @title: 'Start of Validity Period';
        KDATE                 : Date                          @title: 'End of Validity Period';
        BWBDT                 : Date                          @title: 'Closing Date for Applications';
        ANGDT                 : Date                          @title: 'Deadline for Submission of Bid/Quotation';
        BNDDT                 : Date                          @title: 'Binding Period for Quotation';
        GWLDT                 : Date                          @title: 'Warranty Date';
        AUSNR                 : String(10)                    @title: 'Bid Invitation Number';
        ANGNR                 : String(10)                    @title: 'Quotation Number';
        IHRAN                 : Date                          @title: 'Quotation Submission Date';
        IHREZ                 : String(12)                    @title: 'Your Reference';
        VERKF                 : String(30)                    @title: 'Responsible Salesperson at Vendor Office';
        TELF1                 : String(16)                    @title: 'Vendor Telephone Number';
        LLIEF                 : String(10)                    @title: 'Supplying Vendor';
        KUNNR                 : String(10)                    @title: 'Customer Number';
        KONNR                 : String(10)                    @title: 'Number of Principal Purchase Agreement';
        ABGRU                 : String(2)                     @title: 'Field Not Used';
        AUTLF                 : String(1)                     @title: 'Complete Delivery Stipulated for Each Purchase Order';
        WEAKT                 : String(1)                     @title: 'Indicator: Goods Receipt Message';
        RESWK                 : String(4)                     @title: 'Supplying (Issuing) Plant in Stock Transport Order';
        LBLIF                 : String(10)                    @title: 'Field Not Used';
        INCO1                 : String(3)                     @title: 'Incoterms (Part 1)';
        INCO2                 : String(28)                    @title: 'Incoterms (Part 2)';
        KTWRT                 : Decimal(15, 2)                @title: 'Target Value for Header Area per Distribution';
        SUBMI                 : String(10)                    @title: 'Collective Number';
        KNUMV                 : String(10)                    @title: 'Number of the Document Condition';
        KALSM                 : String(6)                     @title: 'Procedure (Pricing, Output Control, Acct. Det., Costing)';
        STAFO                 : String(6)                     @title: 'Update Group for Statistics Update';
        LIFRE                 : String(10)                    @title: 'Different Invoicing Party';
        EXNUM                 : String(10)                    @title: 'Number of Foreign Trade Data in MM and SD Documents';
        UNSEZ                 : String(12)                    @title: 'Our Reference';
        LOGSY                 : String(10)                    @title: 'Logical System';
        UPINC                 : String(5)                     @title: 'Item Number Interval for Subitems';
        STAKO                 : String(1)                     @title: 'Document with Time-Dependent Conditions';
        FRGGR                 : String(2)                     @title: 'Release Group';
        FRGSX                 : String(2)                     @title: 'Release Strategy';
        FRGKE                 : String(1)                     @title: 'Release Indicator: Purchasing Document';
        FRGZU                 : String(8)                     @title: 'Release Status';
        FRGRL                 : String(1)                     @title: 'Release Not Yet Completely Effected';
        to_PurchaseOrderItems : Composition of many PurchaseOrderItem
                                    on to_PurchaseOrderItems.EBELN = $self;
};

entity PurchaseOrderItem {
        //to be discussed with guru (do we need the client)
        // key MANDT                     : String(3)      @title: 'Client';
    key EBELP       : String(5)      @title: 'Item Number of Purchasing Document';
    key EBELN       : Association to PurchaseDocumentHeader;
        UNIQUEID    : String(15)     @title: 'Concatenation of EBELN and EBELP';
        LOEKZ       : String(1)      @title: 'Deletion Indicator in Purchasing Document';
        STATU       : String(1)      @title: 'Origin of a Purchasing Document Item';
        AEDAT       : Date           @title: 'Purchasing Document Item Change Date';
        TXZ01       : String(40)     @title: 'Short Text';
        MATNR       : String(40)     @title: 'Material Number';
        EMATN       : String(40)     @title: 'Material number';
        BUKRS       : String(4)      @title: 'Company Code';
        WERKS       : String(4)      @title: 'Plant';
        LGORT       : String(4)      @title: 'Storage Location';
        BEDNR       : String(10)     @title: 'Requirement Tracking Number';
        MATKL       : String(9)      @title: 'Material Group';
        INFNR       : String(10)     @title: 'Purchasing Info Record Number';
        IDNLF       : String(35)     @title: 'Material Number Used by Supplier';
        KTMNG       : Decimal(13, 3) @title: 'Target Quantity';
        MENGE       : Decimal(13, 3) @title: 'Purchase Order Quantity';
        MEINS       : String(3)      @title: 'Purchase Order Unit of Measure';
        BPRME       : String(3)      @title: 'Order Price Unit (Purchasing)';
        BPUMZ       : Integer        @title: 'Numerator for Conversion of Order Price Unit into Order Unit';
        BPUMN       : Integer        @title: 'Denominator for Conv. of Order Price Unit into Order Unit';
        UMREZ       : Integer        @title: 'Numerator for Conversion of Order Unit to Base Unit';
        UMREN       : Integer        @title: 'Denominator for Conversion of Order Unit to Base Unit';
        NETPR       : Decimal(11, 2) @title: 'Net Price in Purchasing Document (in Document Currency)';
        PEINH       : Integer        @title: 'Price Unit';
        NETWR       : Decimal(13, 2) @title: 'Net Order Value in PO Currency';
        BRTWR       : Decimal(13, 2) @title: 'Gross order value in PO currency';
        AGDAT       : Date           @title: 'Deadline for Submission of Bid/Quotation';
        WEBAZ       : Integer        @title: 'Goods receipt processing time in days';
        MWSKZ       : String(2)      @title: 'Tax on sales/purchases code';
        TXDAT_FROM  : Date           @title: 'Valid-From Date of the Tax Rate';
        TXDAT       : Date           @title: 'Date for Determining Tax Rates';
        TAX_COUNTRY : String(3)      @title: 'Tax Reporting Country/Region';
        BONUS       : String(2)      @title: 'Settlement Group 1 (Purchasing)';
        INSMK       : String(1)      @title: 'Stock Type';
        SPINF       : String(1)      @title: 'Indicator: Update Info Record';
        PRSDR       : String(1)      @title: 'Price Printout';
        SCHPR       : String(1)      @title: 'Indicator: Estimated Price';
        MAHNZ       : Integer        @title: 'Number of Reminders/Expediters';
        MAHN1       : Integer        @title: 'Number of Days for First Reminder/Expediter';
        MAHN2       : Integer        @title: 'Number of Days for Second Reminder/Expediter';
        MAHN3       : Integer        @title: 'Number of Days for Third Reminder/Expediter';
        UEBTO       : Decimal(3, 1)  @title: 'Overdelivery Tolerance';
        UEBTK       : String(1)      @title: 'Over delivery Allowed';
        UNTTO       : Decimal(3, 1)  @title: 'Underdelivery Tolerance';
        BWTAR       : String(10)     @title: 'Valuation Type';
        BWTTY       : String(1)      @title: 'Valuation Category';
        ABSKZ       : String(1)      @title: 'RejectionIndicator';
        AGMEM       : String(3)      @title: 'Internal Comment Quotation';
        ELIKZ       : String(1)      @title: 'DeliveryCompletedIndicator';
        EREKZ       : String(1)      @title: 'Final Invoice Indicator';
        PSTYP       : String(1)      @title: 'Item category in Purchasing Document';
        KNTTP       : String(1)      @title: 'Account Assignment Category';
        KZVBR       : String(1)      @title: 'Consumption posting';
        VRTKZ       : String(1)      @title: 'Distribution Indicator for Multiple Account Assignment';
        TWRKZ       : String(1)      @title: 'Partial invoice indicator';
        WEPOS       : String(1)      @title: 'Goods Receipt Indicator';
        WEUNB       : String(1)      @title: 'Goods Receipt, Non-Valuated';
        REPOS       : String(1)      @title: 'Invoice Receipt Indicator';
        WEBRE       : String(1)      @title: 'Indicator: GR-Based Invoice Verification';
        KZABS       : String(1)      @title: 'Order Acknowledgment Requirement';
        LABNR       : String(20)     @title: 'Order Acknowledgment Number';
        KONNR       : String(10)     @title: 'Number of principal purchase agreement';
        KTPNR       : Decimal(5, 0)  @title: 'Item Number of Principal Purchase Agreement'; //DOUBT
        ABDAT       : Date           @title: 'Reconciliation date for agreed cumulative quantity';
        ABFTZ       : Decimal(13, 3) @title: 'Agreed Cumulative Quantity';
        ETFZ1       : Decimal(3, 0)  @title: 'Firm Zone (Go-Ahead for Production)';
        ETFZ2       : Decimal(3, 0)  @title: 'Trade-Off Zone (Go-Ahead for Materials Procurement)';
        KZSTU       : String(1)      @title: 'Firm/Trade-Off Zones Binding with Regard to Mat. Planning';
        NOTKZ       : String(1)      @title: 'Exclusion in Outline Agreement Item with Material Class';
        LMEIN       : String(3)      @title: 'Base Unit of Measure';
        EVERS       : String(2)      @title: 'Shipping Instructions';
        ZWERT       : Decimal(13, 2) @title: 'Target Value for Outline Agreement in Document Currency';
        NAVNW       : Decimal(13, 2) @title: 'Non-deductible input tax';
        ABMNG       : Decimal(13, 3) @title: 'Standard release order quantity';
        PRDAT       : Date           @title: 'Date of Price Determination';
        BSTYP       : String(1)      @title: 'Purchasing Document Category';
        EFFWR       : Decimal(13, 2) @title: 'Effective value of item'; //Doubt
        XOBLR       : String(1)      @title: 'Item affects commitments';
        KUNNR       : String(10)     @title: 'Customer';
        ADRNR       : String(10)     @title: 'Manual address number in purchasing document item';
        EKKOL       : String(4)      @title: 'Condition Group with Supplier';
        SKTOF       : String(1)      @title: 'Item Does Not Qualify for Cash Discount';
        STAFO       : String(6)      @title: 'Update Group for statistics update';
        PLIFZ       : Decimal(3, 0)  @title: 'Planned Delivery Time in Days';
        NTGEW       : Decimal(13, 3) @title: 'Net Weight';
        GEWEI       : String(3)      @title: 'Unit of Weight'
};
